// agnosticui-angular/libs/ui/src/lib/header.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'ag-header-nav',
  template: `<nav>
    <div [ngClass]="classes">
      <ng-content></ng-content>
    </div>
  </nav>`,
  styleUrls: ['./headernav.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class HeaderNavComponent {
  @Input() css?: string;
  public get classes(): string {
    let klasses = ['header-nav', this.css ? `${this.css}` : ''];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ')
  }
}

@Component({
  selector: 'ag-header-nav-item',
  template: `<div [ngClass]="classes"><ng-content></ng-content></div>`,
  styleUrls: ['./headernavitem.css'],
})

export class HeaderNavItemComponent {
  @Input() css?: string;
  public get classes(): string {
    let klasses = ['header-nav-item', this.css ? `${this.css}` : ''];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}

@Component({
  selector: 'ag-header',
  template: `<header [ngClass]="classes">
    <div class="header-content"><ng-content></ng-content></div>
  </header>
  `,
  styleUrls: ['./header.css'],
})

export class HeaderComponent {
  @Input() css?: string;
  @Input() isSkinned?: boolean = true;
  @Input() isSticky?: boolean;
  
  public get classes(): string {
    const baseClass = this.isSkinned ? 'header' : 'header-base';
    const isStickyClass = this.isSticky ? 'header-sticky' : '';
    const overrides = this.css ? `${this.css}` : '';
    let klasses = [
      baseClass,
      isStickyClass,
      overrides,
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}

// agnosticui-react/src/Header.tsx
// import PropTypes from 'prop-types';
import { FC, ReactNode } from 'react';
import styles from './header.module.css';

export interface HeaderNavProps {
  css?: string;
  children: ReactNode;
}

export const HeaderNav: FC<HeaderNavProps> = ({ css = '', children }) => {
  const klasses = [styles.headerNav, css ? `${css}` : ''];
  const classes = klasses.filter((klass) => klass.length).join(' ');
  return (
    <nav>
      <ul className={classes}>{children}</ul>
    </nav>
  );
};

export interface HeaderNavItemProps {
  css?: string;
  children: ReactNode;
}
export const HeaderNavItem: FC<HeaderNavItemProps> = ({ css = '', children }) => {
  const klasses = [styles.headerNavItem, css ? `${css}` : ''];
  const classes = klasses.filter((klass) => klass.length).join(' ');
  return <li className={classes}>{children}</li>;
};

export interface HeaderProps {
  isSticky?: boolean;
  isSkinned?: boolean;
  css?: string;
  children: ReactNode;
}

export const Header: FC<HeaderProps> = ({
  css = '',
  isSticky = false,
  isSkinned = true,
  children,
}) => {
  const klasses = [
    isSkinned ? styles.header : styles.headerBase,
    isSticky ? styles.sticky : '',
    css ? `${css}` : '',
  ];
  const classes = klasses.filter((klass) => klass.length).join(' ');

  return (
    <header className={classes}>
      <div className={styles.headerContent}>{children}</div>
    </header>
  );
};
