// v2/playbooks/onboarding/vue-example/src/SkinSwitcher.vue
<template>
  <div ref="wrapper">
    <div v-if="open" class="skin-panel">
      <div class="skin-panel-section">
        <div class="skin-panel-label">Theme</div>
        <div class="skin-panel-themes">
          <button :class="['skin-theme-btn', { active: !dark }]" @click="setTheme(false)">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>
            Light
          </button>
          <button :class="['skin-theme-btn', { active: dark }]" @click="setTheme(true)">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>
            Dark
          </button>
        </div>
      </div>
      <div class="skin-panel-section">
        <div class="skin-panel-label">Skin</div>
        <button
          v-for="s in SKINS"
          :key="s.id"
          :class="['skin-option', { active: skin === s.id }]"
          @click="setSkin(s.id)"
        >
          <span class="skin-option-radio" />
          <span class="skin-option-label">{{ s.label }}</span>
          <span class="skin-option-swatch" :style="{ background: s.swatch }" />
        </button>
      </div>
    </div>
    <button class="skin-fab" aria-label="Toggle skin switcher" @click="open = !open">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="13.5" cy="6.5" r="0.5" fill="currentColor" /><circle cx="17.5" cy="10.5" r="0.5" fill="currentColor" /><circle cx="8.5" cy="7.5" r="0.5" fill="currentColor" /><circle cx="6.5" cy="12" r="0.5" fill="currentColor" />
        <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2Z"/>
      </svg>
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import {
  SKINS,
  applySkin,
  applyTheme,
  restorePrefs,
} from '../../../../skins/skin-switcher-core.js';

const open = ref(false);
const skin = ref(localStorage.getItem('ag-skin') || '');
const dark = ref(document.documentElement.getAttribute('data-theme') === 'dark');
const wrapper = ref<HTMLElement | null>(null);

function setSkin(id: string) {
  skin.value = id;
  applySkin(id);
}

function setTheme(isDark: boolean) {
  dark.value = isDark;
  applyTheme(isDark);
}

// Restore prefs on load
restorePrefs();

function onClickOutside(e: MouseEvent) {
  if (wrapper.value && !wrapper.value.contains(e.target as Node)) {
    open.value = false;
  }
}

onMounted(() => {
  document.addEventListener('mousedown', onClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('mousedown', onClickOutside);
});
</script>

// v2/playbooks/dashboard/react-example/src/SkinSwitcher.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import {
  SKINS,
  applySkin,
  applyTheme,
  restorePrefs,
} from '../../../../skins/skin-switcher-core.js';

const paletteIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="13.5" cy="6.5" r="0.5" fill="currentColor" /><circle cx="17.5" cy="10.5" r="0.5" fill="currentColor" /><circle cx="8.5" cy="7.5" r="0.5" fill="currentColor" /><circle cx="6.5" cy="12" r="0.5" fill="currentColor" />
    <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2Z"/>
  </svg>
);

const sunIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>
  </svg>
);

const moonIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
  </svg>
);

// Restore on load
restorePrefs();

export function SkinSwitcher() {
  const [open, setOpen] = useState(false);
  const [skin, setSkin] = useState(() => localStorage.getItem('ag-skin') || '');
  const [dark, setDark] = useState(
    () => document.documentElement.getAttribute('data-theme') === 'dark'
  );
  const panelRef = useRef<HTMLDivElement>(null);

  const toggle = useCallback(() => setOpen(o => !o), []);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    function onClick(e: MouseEvent) {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener('mousedown', onClick);
    return () => document.removeEventListener('mousedown', onClick);
  }, [open]);

  function handleSkin(id: string) {
    setSkin(id);
    applySkin(id);
  }

  function handleTheme(isDark: boolean) {
    setDark(isDark);
    applyTheme(isDark);
  }

  return (
    <div ref={panelRef}>
      {open && (
        <div className="skin-panel">
          <div className="skin-panel-section">
            <div className="skin-panel-label">Theme</div>
            <div className="skin-panel-themes">
              <button
                className={`skin-theme-btn${!dark ? ' active' : ''}`}
                onClick={() => handleTheme(false)}
              >
                {sunIcon} Light
              </button>
              <button
                className={`skin-theme-btn${dark ? ' active' : ''}`}
                onClick={() => handleTheme(true)}
              >
                {moonIcon} Dark
              </button>
            </div>
          </div>
          <div className="skin-panel-section">
            <div className="skin-panel-label">Skin</div>
            {SKINS.map(s => (
              <button
                key={s.id}
                className={`skin-option${skin === s.id ? ' active' : ''}`}
                onClick={() => handleSkin(s.id)}
              >
                <span className="skin-option-radio" />
                <span className="skin-option-label">{s.label}</span>
                <span className="skin-option-swatch" style={{ background: s.swatch }} />
              </button>
            ))}
          </div>
        </div>
      )}
      <button className="skin-fab" onClick={toggle} aria-label="Toggle skin switcher">
        {paletteIcon}
      </button>
    </div>
  );
}
