// agnostic-react/src/Drawer.tsx
import { FC, ReactElement } from 'react';
import { Dialog } from './Dialog';

export interface DrawerProps {
  id: string;
  drawerRoot: string;
  placement: 'top' | 'bottom' | 'start' | 'end';
  title: string;
  role?: 'dialog' | 'alertdialog';
  drawerRef?: (instance: any) => void;
  isAnimationFadeIn?: boolean;
}

export const Drawer: FC<DrawerProps> = (props): ReactElement => {
  const {
    id,
    drawerRef,
    drawerRoot,
    placement,
    title,
    role = 'dialog',
    isAnimationFadeIn = true,
  } = props;

  return (
    <Dialog
      id={id}
      dialogRoot={drawerRoot}
      drawerPlacement={placement}
      titleId={`${title.replaceAll(' ', '-').toLowerCase()}-id`}
      title={title}
      role={role}
      dialogRef={drawerRef}
      closeButtonLabel="Close drawer"
      isAnimationFadeIn={isAnimationFadeIn}
    />
  );
};

// agnostic-svelte-ts/src/lib/components/Drawer/Drawer.svelte
<script lang="ts">
  import type { DrawerRoles } from './api';
  import Dialog from "../Dialog/Dialog.svelte";
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  let drawerInstance;
  const assignDrawerRef = (ev) => {
    drawerInstance = ev.detail.instance;
    dispatch("instance", {
      instance: drawerInstance,
    });
  };

  export let id;
  export let drawerRoot;
  export let placement;
  export let title;
  export let role: DrawerRoles = "dialog";
  export let isAnimationFadeIn = true;
</script>
<Dialog
  id={id}
  dialogRoot={drawerRoot}
  drawerPlacement={placement}
  titleId="{`${title.replaceAll(' ', '-').toLowerCase()}-id`}"
  role={role}
  title={title}
  on:instance={assignDrawerRef}
  isAnimationFadeIn={isAnimationFadeIn}
  closeButtonLabel="Close drawer"
>
  <slot />
</Dialog>
