// agnosticui-react/src/stories/FlexGrid/FlexRow.js
import React from 'react';
import PropTypes from 'prop-types';
import getClass from './classNames';
import createProps from './createProps';
import { ViewportSizeType } from './types';

const rowKeys = ['start', 'center', 'end', 'top', 'middle', 'bottom', 'around', 'between'];

const propTypes = {
  reverse: PropTypes.bool,
  start: ViewportSizeType,
  center: ViewportSizeType,
  end: ViewportSizeType,
  top: ViewportSizeType,
  middle: ViewportSizeType,
  bottom: ViewportSizeType,
  around: ViewportSizeType,
  between: ViewportSizeType,
  className: PropTypes.string,
  tagName: PropTypes.string,
  children: PropTypes.node,
};

function getRowClassNames(props) {
  const modifiers = [props.className, getClass('row')];

  for (let i = 0; i < rowKeys.length; ++i) {
    const key = rowKeys[i];
    const value = props[key];
    if (value) {
      modifiers.push(getClass(`${key}-${value}`));
    }
  }

  if (props.reverse) {
    modifiers.push(getClass('reverse'));
  }

  return modifiers;
}

export function getRowProps(props) {
  const rowPropsCreated = createProps(propTypes, props, getRowClassNames(props));
  return rowPropsCreated;
}

const FlexRow = (props) => {
  return React.createElement(props.tagName || 'div', getRowProps(props));
};

FlexRow.propTypes = propTypes;

export default FlexRow;

// agnosticui-vue/src/stories/FlexGrid/FlexRow.vue
<template>
  <component
    :is="tagName"
    :class="classNames"
  >
    <slot />
  </component>
</template>
<script>
import getClass from "./classNames";
import { ViewportSizeTypeProp } from "./types";
const rowKeys = [
  "start",
  "center",
  "end",
  "top",
  "middle",
  "bottom",
  "around",
  "between",
];

export default {
  name: "ag-flexrow",
  computed: {
    classNames() {
      const modifiers = [this.customClasses, getClass("row")];
      for (let i = 0; i < rowKeys.length; ++i) {
        const key = rowKeys[i];
        const value = this[key];
        if (value) {
          modifiers.push(getClass(`${key}-${value}`));
        }
      }

      if (this.reverse) {
        modifiers.push(getClass("reverse"));
      }
      return modifiers;
    },
  },
  props: {
    // see https://roylee0704.github.io/react-flexbox-grid/
    reverse: {
      type: Boolean,
      default: false,
    },
    start: ViewportSizeTypeProp,
    center: ViewportSizeTypeProp,
    end: ViewportSizeTypeProp,
    top: ViewportSizeTypeProp,
    middle: ViewportSizeTypeProp,
    bottom: ViewportSizeTypeProp,
    around: ViewportSizeTypeProp,
    between: ViewportSizeTypeProp,
    customClasses: {
      type: String,
      default: "",
    },
    tagName: {
      type: String,
      default: "div",
    },
  },
};
</script>
