// agnosticui-angular/libs/ui/src/lib/progress.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
@Component({
  selector: 'ag-progress',
  template: `<progress [ngClass]="classes" [attr.value]="value" [attr.max]="max"></progress>`,
  styleUrls: ['./progress.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class ProgressComponent {
  @Input() value: number = 0;
  @Input() max: number = 100;
  @Input() css?: string;
  public get classes(): string {
    console.log(this)
    let klasses = ['progress', this.css?.length ? `${this.css}` : '']
    klasses = klasses.filter((klass) => klass.length)
    return klasses.join(' ')
  }
}

// agnosticui-react/src/stories/Progress.js
import React from 'react';
import PropTypes from 'prop-types';
import styles from './progress.module.css';

const Progress = ({ value, max, css }) => {
  let klasses = [styles.progressBar, css ? `${css}` : ""];
  klasses = klasses.filter(klass => klass.length);
  klasses = klasses.join(" ");
  return (
    <progress className={klasses} value={value} max={max} />
  )
}

Progress.propTypes = {
  value: PropTypes.number,
  max: PropTypes.number.isRequired,
  css: PropTypes.string,
}

Progress.defaultProps = {
  value: 0,
  css: undefined,
}

export default Progress;
