// v2/sdui/demo-lit/src/components/WorkflowPicker.ts
import { LitElement, html, css } from 'lit';
import { property, state } from 'lit/decorators.js';
import '@agnosticui/render-lit';
import { pickerFixture } from '../../../demo/src/fixtures/picker';
import type { AgNode } from '@agnosticui/schema';

export class WorkflowPicker extends LitElement {
  static styles = css`:host { display: block; }`;

  @state() private selected = 'contact-form';

  private get nodes(): AgNode[] {
    return pickerFixture.map(node =>
      node.id === 'picker-group' ? { ...node, value: this.selected } as AgNode : node
    );
  }

  private actions = {
    'workflow-select': (payload: unknown) => {
      const value = (payload as { id: string; value: string }).value;
      this.selected = value;
      this.dispatchEvent(new CustomEvent('workflow-select', {
        detail: value,
        bubbles: true,
        composed: true,
      }));
    },
  };

  render() {
    return html`<ag-dynamic-renderer
      .nodes=${this.nodes}
      .actions=${this.actions}
    ></ag-dynamic-renderer>`;
  }
}

customElements.define('ag-workflow-picker', WorkflowPicker);

// v2/sdui/demo-vue/src/components/WorkflowPicker.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { AgDynamicRenderer } from '@agnosticui/render-vue';
import { pickerFixture } from '../../../demo/src/fixtures/picker';
import type { AgNode } from '@agnosticui/schema';

const emit = defineEmits<{ select: [workflow: string] }>();

const selected = ref('contact-form');

const nodes = computed<AgNode[]>(() =>
  pickerFixture.map(node =>
    node.id === 'picker-group' ? { ...node, value: selected.value } as AgNode : node
  )
);

const actions = {
  'workflow-select': (payload: unknown) => {
    const value = (payload as { id: string; value: string }).value;
    selected.value = value;
    emit('select', value);
  },
};
</script>

<template>
  <AgDynamicRenderer :nodes="nodes" :actions="actions" />
</template>
