// agnostic-vue/src/components/Pagination.vue
<template>
  <nav
    :class="paginationContainerClasses"
    :aria-label="ariaLabel"
  >
    <ul :class="paginationClasses">
      <li
        v-if="isFirstLast"
        :class="[paginationItemClass, isOnFirst() ? paginationItemDisabledClass : '']"
      >
        <button
          :class="paginationButtonClass"
          @click.prevent="handleClick(1)"
          :disabled="isOnFirst()"
          :aria-disabled="isOnFirst()"
          aria-label="Goto page 1"
        >
          {{ String.fromCharCode(171) }} {{ navigationLabels.first }}
        </button>
      </li>
      <li :class="[paginationItemClass, isOnFirst() ? paginationItemDisabledClass : '']">
        <button
          :class="paginationButtonClass"
          @click.prevent="handleClick(current - 1)"
          :disabled="isOnFirst()"
          :aria-disabled="isOnFirst()"
          aria-label="Goto previous page"
        >
          {{ String.fromCharCode(8249) }} {{ navigationLabels.previous }}
        </button>
      </li>
      <li
        v-for="page in pages"
        :key="`page-${page}`"
        :class="[
          paginationItemClass,
          page === current ? paginationItemsActiveClass : '',
          page === '...' ? paginationItemGapClass : '']"
      >
        <button
          v-if="page === current"
          @click.prevent="handleClick(page)"
          :class="paginationButtonClass"
          type="button"
          aria-current="page"
          :aria-label="`Page ${page}, current page`"
        >
          {{ page }}
        </button>
        <span v-else-if="page === '...'">{{ page }}</span>
        <button
          v-else
          @click.prevent="handleClick(page)"
          :class="paginationButtonClass"
          type="button"
          :aria-label="`Goto page ${page}`"
        >
          {{ page }}
        </button>
      </li>

      <li :class="[paginationItemClass, isOnLast() ? paginationItemDisabledClass : '']">
        <button
          :class="paginationButtonClass"
          @click.prevent="handleClick(current + 1)"
          :disabled="isOnLast()"
          :aria-disabled="isOnLast()"
          aria-label="Goto next page"
        >
          {{ navigationLabels.next }} {{ String.fromCharCode(8250) }}
        </button>
      </li>

      <li
        v-if="isFirstLast"
        :class="[paginationItemClass, isOnLast() ? paginationItemDisabledClass : '']"
      >
        <button
          :class="paginationButtonClass"
          @click.prevent="handleClick(getLastPageNumber())"
          :disabled="isOnLast()"
          :aria-disabled="isOnLast()"
          aria-label="Goto last page"
        >
          {{ navigationLabels.last }} {{ String.fromCharCode(187) }}
        </button>
      </li>
    </ul>
  </nav>
</template>

<script>
import { /*ref, */ computed, useCssModule /*, watch */ } from "vue";

// import { usePagination } from "agnostic-helpers/dist/agnostic-helpers.esm";
const defaultLabels = {
  first: "First",
  last: "Last",
  previous: "Previous",
  next: "Next",
};

export default {
  name: "AgPagination",
  props: {
    justify: {
      type: String,
      required: false,
      default: "",
      validator: (value) => ["start", "center", "end", ""].includes(value),
    },
    ariaLabel: {
      type: String,
      required: false,
      default: "pagination",
    },
    current: {
      type: Number,
      required: true,
    },
    pages: {
      type: Array,
      required: true,
    },
    isBordered: {
      type: Boolean,
      required: false,
      default: false,
    },
    isFirstLast: {
      type: Boolean,
      required: false,
      default: true,
    },
    navigationLabels: {
      type: Object,
      default: () => defaultLabels,
    },
  },
  emits: ["update-page"],
  setup(props, { emit }) {
    const styles = useCssModule();

    const paginationContainerClasses = computed(() => {
      return {
        [styles["pagination-container"]]: true,
        [styles[`pagination-${props.justify}`]]: !!props.justify,
      };
    });

    const paginationClasses = computed(() => {
      return {
        [styles["pagination"]]: true,
        [styles["pagination-bordered"]]: !!props.isBordered,
      };
    });

    const paginationButtonClass = computed(() => styles["pagination-button"]);
    const paginationItemClass = computed(() => styles["pagination-item"]);
    const paginationItemsActiveClass = computed(
      () => styles["pagination-item-active"]
    );
    const paginationItemGapClass = computed(
      () => styles["pagination-item-gap"]
    );
    const paginationItemDisabledClass = computed(
      () => styles["pagination-item-disabled"]
    );

    const isOnFirst = () => {
      return props.current === 1;
    };

    const getLastPageNumber = () => {
      return props.pages[props.pages.length - 1];
    };

    const isOnLast = () => {
      return props.current === getLastPageNumber();
    };

    const handleClick = (pageNumber) => {
      emit("update-page", pageNumber);
    };

    return {
      handleClick,
      getLastPageNumber,
      isOnFirst,
      isOnLast,
      paginationButtonClass,
      paginationItemClass,
      paginationItemsActiveClass,
      paginationItemGapClass,
      paginationItemDisabledClass,
      paginationClasses,
      paginationContainerClasses,
    };
  },
};
</script>

<style module>
.pagination-container {
  display: flex;
}

.pagination {
  display: flex;
  list-style: none;
}

.pagination-item {
  padding-inline-start: var(--fluid-2);
  padding-inline-end: var(--fluid-2);
}

.pagination-button {
  --agnostic-pagination-button-color: var(--agnostic-primary);

  color: var(--agnostic-pagination-button-color);
  display: inline-block;
  line-height: var(--fluid-20);
  padding-inline-start: var(--fluid-12);
  padding-inline-end: var(--fluid-12);
  padding-block-start: var(--fluid-6);
  padding-block-end: var(--fluid-6);
  border-radius: var(--agnostic-radius);

  /* We need a border set on both hovered and unhovered so it does not jump around */
  border: 1px solid transparent;
  background-color: transparent;
}

.pagination-button:focus {
  box-shadow: 0 0 0 var(--agnostic-focus-ring-outline-width) var(--agnostic-focus-ring-color);

  /* Needed for High Contrast mode */
  outline:
    var(--agnostic-focus-ring-outline-width) var(--agnostic-focus-ring-outline-style)
    var(--agnostic-focus-ring-outline-color);
  transition: box-shadow var(--agnostic-timing-fast) ease-out;
}

@media (prefers-reduced-motion), (update: slow) {
  .pagination-button:focus {
    transition-duration: 0.001ms !important;
  }
}

.pagination-item-disabled {
  cursor: not-allowed;
}

.pagination-button:disabled,
.pagination-item-disabled .pagination-button {
  color: var(--agnostic-pagination-disabled-bg, var(--agnostic-gray-mid-dark));
  opacity: 80%;
  pointer-events: none;
}

.pagination-item-active .pagination-button {
  background-color: var(--agnostic-primary);
  color: var(--agnostic-light);
}

.pagination-bordered .pagination-item-active .pagination-button {
  background-color: unset;
  border: 1px solid var(--agnostic-primary);
  color: var(--agnostic-primary);
}

.pagination-item:hover .pagination-button {
  text-decoration: none;
}

.pagination-item:not(.pagination-item-active):not(.pagination-item-disabled):hover .pagination-button {
  background-color: var(--agnostic-gray-extra-light);
}

/* For ellipses like [1][2]...[3][4] */
.pagination-item-gap {
  transform: translateY(var(--fluid-6));
}

.pagination-center {
  justify-content: center;
}

.pagination-start {
  justify-content: flex-start;
}

.pagination-end {
  justify-content: flex-end;
}

</style>

// agnostic-svelte/src/lib/components/Pagination/Pagination.svelte
<style>
.pagination-container {
  display: flex;
}

.pagination {
  display: flex;
  list-style: none;
}

.pagination-item {
  padding-inline-start: var(--fluid-2);
  padding-inline-end: var(--fluid-2);
}

.pagination-button {
  --agnostic-pagination-button-color: var(--agnostic-primary);

  color: var(--agnostic-pagination-button-color);
  display: inline-block;
  line-height: var(--fluid-20);
  padding-inline-start: var(--fluid-12);
  padding-inline-end: var(--fluid-12);
  padding-block-start: var(--fluid-6);
  padding-block-end: var(--fluid-6);
  border-radius: var(--agnostic-radius);

  /* We need a border set on both hovered and unhovered so it does not jump around */
  border: 1px solid transparent;
  background-color: transparent;
}

.pagination-button:focus {
  box-shadow: 0 0 0 var(--agnostic-focus-ring-outline-width) var(--agnostic-focus-ring-color);

  /* Needed for High Contrast mode */
  outline:
    var(--agnostic-focus-ring-outline-width) var(--agnostic-focus-ring-outline-style)
    var(--agnostic-focus-ring-outline-color);
  transition: box-shadow var(--agnostic-timing-fast) ease-out;
}

@media (prefers-reduced-motion), (update: slow) {
  .pagination-button:focus {
    transition-duration: 0.001ms !important;
  }
}

.pagination-item-disabled {
  cursor: not-allowed;
}

.pagination-button:disabled,
.pagination-item-disabled .pagination-button {
  color: var(--agnostic-pagination-disabled-bg, var(--agnostic-gray-mid-dark));
  opacity: 80%;
  pointer-events: none;
}

.pagination-item-active .pagination-button {
  background-color: var(--agnostic-primary);
  color: var(--agnostic-light);
}

.pagination-bordered .pagination-item-active .pagination-button {
  background-color: unset;
  border: 1px solid var(--agnostic-primary);
  color: var(--agnostic-primary);
}

.pagination-item:hover .pagination-button {
  text-decoration: none;
}

.pagination-item:not(.pagination-item-active):not(.pagination-item-disabled):hover .pagination-button {
  background-color: var(--agnostic-gray-extra-light);
}

/* For ellipses like [1][2]...[3][4] */
.pagination-item-gap {
  transform: translateY(var(--fluid-6));
}

.pagination-center {
  justify-content: center;
}

.pagination-start {
  justify-content: flex-start;
}

.pagination-end {
  justify-content: flex-end;
}

</style>

<script>
  import { usePagination } from "agnostic-helpers/dist/index.esm";

  /**
   * Pagination component handles presentation only and does two things:
   * 1. Displays paging controls you pass in as `pages` array
   * 2. Applies styles to those paging controls
   *
   * Inversion of control is used such that the consumer is in
   * charge of using the usePagination module to generate and
   * regenerate pages that get passed in here. See ./PaginationExample.svelte
   */

  // can be: 'start', 'center', 'end' (or empty string)
  export let justify = "";
  export let current = 1;
  export let total = 1;
  export let pages = [];
  export let pageGenerator = usePagination({ offset: 1 });
  export let ariaLabel = "pagination";
  export let isBordered = false;
  export let isFirstLast = true;
  export let navigationLabels = {
    first: "First",
    last: "Last",
    previous: "Previous",
    next: "Next",
  };

  function genPages(page) {
    if (pageGenerator) {
      pages = pageGenerator.generate(page, total);
    }
  }

  $: genPages(current);


  // Note that in the template we've bound via bind:this -- essentially this is
  // like a react ref but in Svelte parlance it's a binding. This allows us to
  // interact with the native component; we leverage this to call btn.focus() later
  // Se https://svelte.dev/tutorial/component-this
  let btn;

  const getLastPageNumber = () => pages[pages.length - 1];

  $: paginationItemClassesForPage = (page) => {
    return [
      "pagination-item",
      page === current ? "pagination-item-active" : "",
      page === "..." ? "pagination-item-gap" : "",
    ]
      .filter((kl) => kl)
      .join(" ");
  };

  $: paginationItemClassesForFirst = () => {
    return ["pagination-item", current === 1 ? "pagination-item-disabled" : ""]
      .filter((kl) => kl)
      .join(" ");
  };

  $: paginationItemClassesForLast = () => {
    return [
      "pagination-item",
      current === getLastPageNumber() ? "pagination-item-disabled" : "",
    ]
      .filter((kl) => kl)
      .join(" ");
  };

  $: paginationContainerClasses = [
    "pagination-container",
    justify ? `pagination-${justify}` : "",
  ]
    .filter((cls) => cls)
    .join(" ");

  $: paginationClasses = [
    "pagination",
    isBordered ? "pagination-bordered" : "",
  ]
    .filter((cls) => cls)
    .join(" ");

  const handleClick = async (pageNumber) => {
    current = pageNumber;

    btn.focus();
  };
</script>

<nav class={paginationContainerClasses} aria-label={ariaLabel}>
  <ul class={paginationClasses}>
    {#if isFirstLast}
      <li class={paginationItemClassesForFirst}>
        <button
          class="pagination-button"
          on:click={() => handleClick(1)}
          disabled={current === 1}
          aria-disabled={current === 1}
          aria-label="Goto page 1"
        >
          {String.fromCharCode(171)}
          {" "}
          {navigationLabels.first}
        </button>
      </li>
    {/if}
    <li class={paginationItemClassesForFirst}>
      <button
        class="pagination-button"
        on:click={() => handleClick(current - 1)}
        disabled={current === 1}
        aria-disabled={current === 1}
        aria-label="Goto previous page"
      >
        {String.fromCharCode(8249)}
        {" "}
        {navigationLabels.previous}
      </button>
    </li>
    {#each pages as page}
      {#if page === "..."}
        <li class="pagination-item pagination-item-gap"><span>{page}</span></li>
      {:else}
        <li class={paginationItemClassesForPage(page)}>
          {#if current === page}
            <button
              bind:this={btn}
              on:click={() => handleClick(page)}
              type="button"
              class="pagination-button"
              aria-current="page"
              aria-label={'Page ' + current + ', current page'}
            >
              {page}
            </button>
          {:else}
            <button
              on:click={handleClick(page)}
              type="button"
              class="pagination-button"
              aria-label={'Goto page' + page}
            >
              {page}
            </button>
          {/if}
        </li>
      {/if}
    {/each}
    <li class={paginationItemClassesForLast}>
      <button
        class="pagination-button"
        on:click={handleClick(current + 1)}
        disabled={current === getLastPageNumber()}
        aria-disabled={current === getLastPageNumber()}
        aria-label="Goto nextpage"
      >
        {navigationLabels.next}
        {" "}
        {String.fromCharCode(8250)}
      </button>
    </li>
    {#if isFirstLast}
      <li class={paginationItemClassesForLast}>
        <button
          class="pagination-button"
          on:click={() => handleClick(getLastPageNumber())}
          disabled={current === getLastPageNumber()}
          aria-disabled={current === getLastPageNumber()}
          aria-label="Goto last page"
        >
          {navigationLabels.last}
          {" "}
          {String.fromCharCode(187)}
        </button>
      </li>
    {/if}
  </ul>
</nav>
