// agnostic-vue/src/components/Drawer.vue
<template>
  <Dialog
    :id="id"
    :dialog-root="drawerRoot"
    :drawer-placement="placement"
    :title-id="`${title.replaceAll(' ', '-').toLowerCase()}-id`"
    @instance="assignDrawerRef"
    close-button-label="Close drawer"
    :is-animation-fade-in="isAnimationFadeIn"
  >
    <template #title>
      {{ title }}
    </template>
    <slot />
  </Dialog>
</template>
<script setup>
import Dialog from "./Dialog.vue";
const emit = defineEmits(["instance"]);

const assignDrawerRef = (instance) => {
  emit("instance", instance);
};
defineProps({
  id: {
    type: String,
    required: true,
  },
  drawerRoot: {
    type: String,
    required: true,
  },
  placement: {
    type: String,
    required: true,
  },
  title: {
    type: String,
    default: "",
  },
  isAnimationFadeIn: {
    type: Boolean,
    required: false,
    default: true,
  },
});
</script>
<script>
export default {
  name: "AgDrawer",
};
</script>

// agnostic-svelte/src/lib/components/Drawer/Drawer.svelte
<script>
  import Dialog from "../Dialog/Dialog.svelte";
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  let drawerInstance;
  const assignDrawerRef = (ev) => {
    drawerInstance = ev.detail.instance;
    dispatch("instance", {
      instance: drawerInstance,
    });
  };

  export let id;
  export let drawerRoot;
  // dialog | alertdialog
  export let placement;
  export let title = "";
  export let role = "dialog";
  export let isAnimationFadeIn = true;
</script>
<Dialog
  id={id}
  dialogRoot={drawerRoot}
  drawerPlacement={placement}
  titleId="{`${title.replaceAll(' ', '-').toLowerCase()}-id`}"
  role={role}
  on:instance={assignDrawerRef}
  isAnimationFadeIn={isAnimationFadeIn}
  closeButtonLabel="Close drawer"
>
  <slot name="title">
    {title}
  </slot>
  <slot />
</Dialog>
