// agnosticui-angular/src/stories/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'ag-button',
  template: `<button
    [type]="getType"
    (click)="onClick.emit($event)"
    [disabled]="getDisabled"
    [ngClass]="classes"
  >
    <ng-content></ng-content>
  </button>`,
  styleUrls: ['./button.css'],
})

export default class ButtonComponent {
  @Input() mode: 'primary' | 'secondary' | undefined = undefined;
  @Input() type?: 'button' | 'reset' | 'submit' = 'button';
  @Input() size?: 'small' | 'medium' | 'large' = 'medium';
  @Input() css?: string;
  @Input() isDisabled?: true | false = false;
  @Input() isSkinned?: boolean;
  @Input() isBlank?: boolean;
  @Input() isRaised?: boolean;
  @Input() isCircle?: boolean;
  @Input() isBlock?: boolean;
  @Input() isBordered?: boolean;
  @Input() isRounded?: boolean;
  @Output() onClick = new EventEmitter<boolean>();
  
  public get classes(): string {
    const baseClass = this.isSkinned !== false ? `btn` : `btn-base`;
    const modeClass = this.mode? `btn-${this.mode}` : '';
    const isBlankClass = this.isBlank === true ? 'btn-blank' : '';
    const isBorderedClass = this.isBordered === true ? 'btn-bordered' : '';
    const isRaisedClass = this.isRaised === true ? 'btn-raised' : '';
    const isCircleClass = this.isCircle === true ? 'btn-circle' : '';
    const isBlockClass = this.isBlock === true ? 'btn-block' : '';
    const isRoundedClass = this.isRounded === true ? 'btn-rounded' : '';
    const overrides = this.css ? `${this.css}` : '';
    const sizeClass = this.size ? `btn-${this.size}` : 'btn-medium';

    return [
      baseClass, 
      modeClass,
      isBlankClass,
      sizeClass,
      isBorderedClass,
      isCircleClass,
      isRoundedClass,
      isRaisedClass,
      isBlockClass,
      overrides,
    ].join(' ');
  }
  
  public get getDisabled(): boolean {
    return this.isDisabled || false;
  }

  public get getType(): string {
    return this.type ? this.type : 'button';
  }
}

// agnostic-react/src/Button.tsx
import { FC, HTMLAttributes, ReactNode } from 'react';
import styles from './button.module.css';

export interface ButtonProps extends HTMLAttributes<HTMLButtonElement> {
  mode?: string;
  size?: 'large' | 'small' | '';
  isSkinned?: boolean;
  isBordered?: boolean;
  isRounded?: boolean;
  isCircle?: boolean;
  isDisabled?: boolean;
  isRaised?: boolean;
  isBlock?: boolean;
  isBlank?: boolean;
  css?: string;
  role?: string;
  type?: 'faux' | 'button' | 'reset' | 'submit';
  children?: ReactNode;
}

export const Button: FC<ButtonProps> = ({
  children,
  mode = '',
  size = '',
  isSkinned = true,
  isBordered = false,
  isRounded = false,
  isCircle = false,
  isDisabled = false,
  isRaised = false,
  isBlock = false,
  isBlank = false,
  css,
  type = 'button',
  ...rest
}) => {
  const klasses = [
    // By default, we provide both btn-base and btn-skin. However,
    // folks can opt-out by setting `isSkinned: false`, in which case
    // we will only include the base button styles so they can skin.
    isSkinned ? styles.btn : styles.btnBase,
    mode ? styles[`${mode}`] : '',
    size ? styles[`${size}`] : '',
    isBordered ? styles.bordered : '',
    isRounded ? styles.rounded : '',
    isCircle ? styles.circle : '',
    isDisabled ? styles.disabled : '',
    isRaised ? styles.raised : '',
    isBlock ? styles.block : '',
    isBlank ? styles.blank : '',
    css ? `${css}` : '',
  ];
  const classes = klasses.filter((klass) => klass.length).join(' ');

  return type === 'faux' ? (
    <div className={classes}>{children}</div>
  ) : (
    <button type={type} className={classes} disabled={isDisabled} {...rest}>
      {children}
    </button>
  );
};

export interface ButtonGroupProps {
  ariaLabel: string;
  css?: string;
  children: ReactNode;
}

export const ButtonGroup: FC<ButtonGroupProps> = ({ ariaLabel, children, css = '' }) => {
  const props = {
    className: `${styles.group} ${css}`,
    role: 'group',
    ...(ariaLabel && { 'aria-label': ariaLabel }),
  };
  return <div {...props}>{children}</div>;
};
