// agnosticui-angular/libs/ag/src/lib/input.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'ag-input',
  template: `<div className="width-full">
    <label [class]="labelClasses()" [for]="id">
      {{ label }}
    </label>
    <ng-container *ngIf="type === 'textarea'; else noTextarea">
      <textarea
        *ngIf="type === 'textarea'"
        [id]="id"
        [name]="id"
        [value]="defaultValue || ''"
        [disabled]="isDisabled"
        [class]="inputClasses()"
        [placeholder]="placeholder ? placeholder : ''"
        [attr.rows]="rows"
        [attr.cols]="cols"
        (change)="(handleChange)"
        (focus)="(handleFocus)"
        (blur)="(handleBlur)"
      ></textarea>
    </ng-container>
    <ng-template #noTextarea>
      <div
        class="input-addon-container"
        *ngIf="hasLeftAddon || hasRightAddon; else inputOnly"
      >
        <ng-content select="[addOnLeft]"></ng-content>
        <input
          [id]="id"
          [name]="id"
          [value]="defaultValue || ''"
          [type]="type"
          [disabled]="isDisabled"
          [class]="inputClasses()"
          [placeholder]="placeholder ? placeholder : ''"
          (change)="(handleChange)"
          (focus)="(handleFocus)"
          (blur)="(handleBlur)"
        />
        <ng-content select="[addOnRight]"></ng-content>
      </div>
      <ng-template #inputOnly>
        <input
          [id]="id"
          [name]="id"
          [value]="defaultValue || ''"
          [type]="type"
          [disabled]="isDisabled"
          [class]="inputClasses()"
          [placeholder]="placeholder ? placeholder : ''"
          (change)="(handleChange)"
          (focus)="(handleFocus)"
          (blur)="(handleBlur)"
        />
      </ng-template>
    </ng-template>
    <span
      *ngIf="isInvalid; else helpHint"
      [class]="invalidClasses()"
      role="status"
      aria-live="polite"
    >
      {{ invalidText }}
    </span>
    <ng-template #helpHint>
      <span [class]="helpClasses()" role="status" aria-live="polite">
        {{ helpText }}
      </span>
    </ng-template>
  </div>`,
  styleUrls: ['./input.css', './inputaddon-hack.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InputComponent {
  @Input() helpText?: string = '';
  @Input() invalidText?: string = '';
  @Input() isInvalid?: boolean = false;
  @Input() isSkinned?: boolean = true;
  @Input() isRounded?: boolean = false;
  @Input() isUnderlined?: boolean = false;
  @Input() isInline?: boolean = false;
  @Input() isDisabled?: boolean = false;
  @Input() hasLeftAddon?: boolean = false;
  @Input() hasRightAddon?: boolean = false;
  @Input() isUnderlinedWithBackground?: boolean = false;
  @Input() id!: string;
  @Input() label!: string;
  @Input() labelCss?: string;
  @Input() css?: string;
  @Input() placeholder?: string;
  @Input() defaultValue?: string;
  @Input() size?: 'small' | 'large' | '' = '';
  @Input() type!:
    | 'text'
    | 'password'
    | 'email'
    | 'number'
    | 'url'
    | 'tel'
    | 'search'
    | 'textarea';
  // It appears we can't have arbitrary props in Angular and they all have to be defined
  // as an @Input. React has ...rest, Vue has v-bind="$attrs", Svelte has  {...$$restProps} ¯\_(ツ)_/¯
  // https://github.com/angular/angular/issues/14545
  @Input() rows?: number;
  @Input() cols?: number;

  helpClasses() {
    const klasses = [
      !this.size ? 'field-help' : '',
      this.size ? `field-help-${this.size}` : '',
    ];
    return klasses.filter((klass) => klass.length).join(' ');
  }
  invalidClasses() {
    const klasses = [
      !this.size ? 'field-error' : '',
      this.size ? `field-error-${this.size}` : '',
    ];
    return klasses.filter((klass) => klass.length).join(' ');
  }
  labelClasses() {
    const labelKlasses = [
      'label',
      this.isInvalid ? 'label-error' : '',
      this.isInline ? 'label-inline' : '',
      this.size ? `label-${this.size}` : '',
      this.labelCss ? this.labelCss : '',
    ];
    return labelKlasses.filter((klass) => klass.length).join(' ');
  }
  inputClasses() {
    let klasses = [
      this.isSkinned ? 'input' : 'input-base',
      this.isRounded ? 'input-rounded' : '',
      this.isUnderlined ? 'input-underlined' : '',
      this.isDisabled ? 'disabled' : '',
      this.isInline ? 'input-inline' : '',
      this.hasLeftAddon ? 'input-has-left-addon' : '',
      this.hasRightAddon ? 'input-has-right-addon' : '',
      this.isInvalid ? 'input-error' : '',
      this.isUnderlinedWithBackground ? 'input-underlined-bg' : '',
      this.css ? `${this.css}` : '',
      this.size ? `input-${this.size}` : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
  handleChange(ev: Event) {
    console.log('handleChange not yet implemented...');
  }
  handleFocus(ev: Event) {
    console.log('handleFocus not yet implemented...');
  }
  handleBlur(ev: Event) {
    console.log('handleBlur not yet implemented...');
  }
}

// agnostic-react/src/Input.tsx
import { FC, ReactNode, HTMLAttributes } from 'react';
import styles from './input.module.css';

export interface InputProps extends HTMLAttributes<HTMLInputElement | HTMLTextAreaElement> {
  id: string;
  label: string;
  size?: 'small' | 'large';
  labelCss?: string;
  placeholder?: string;
  helpText?: string;
  invalidText?: string;
  addOnLeft?: ReactNode;
  addOnRight?: ReactNode;
  hasLeftAddon?: boolean;
  hasRightAddon?: boolean;
  css?: string;
  isInvalid?: boolean;
  isRounded?: boolean;
  isDisabled?: boolean;
  isInline?: boolean;
  isSkinned?: boolean;
  isUnderlined?: boolean;
  isUnderlinedWithBackground?: boolean;
  defaultValue?: string;
  type?: 'text' | 'password' | 'email' | 'number' | 'url' | 'tel' | 'search' | 'textarea';
  // Only useful if type is textarea
  rows?: number;
  cols?: number;
}

export const Input: FC<InputProps> = ({
  id,
  label,
  size = '',
  labelCss = '',
  placeholder = '',
  helpText = '',
  invalidText = '',
  addOnLeft = '',
  addOnRight = '',
  hasLeftAddon = false,
  hasRightAddon = false,
  css = '',
  isInvalid = false,
  isRounded = false,
  isDisabled = false,
  isInline = false,
  isSkinned = true,
  isUnderlined = false,
  isUnderlinedWithBackground = false,
  defaultValue = '',
  type = 'text',
  onChange,
  onFocus,
  onBlur,
  rows,
  cols,
  ...rest
}) => {
  const capitalize = (str: string) => str.charAt(0).toUpperCase() + str.slice(1);

  const inputClasses = [
    isSkinned ? styles.input : styles.inputBase,
    isRounded ? styles.rounded : '',
    isUnderlined ? styles.underlined : '',
    isDisabled ? styles.disabled : '',
    isInline ? styles.inputInline : '',
    hasLeftAddon ? styles.inputHasLeftAddon : '',
    hasRightAddon ? styles.inputHasRightAddon : '',
    isInvalid ? styles.invalid : '',
    isUnderlinedWithBackground ? styles.underlinedWithBackground : '',
    css ? `${css}` : '',
    size ? styles[`input${capitalize(size)}`] : '',
  ];
  const inputClassesJoined = inputClasses
    .filter((klass) => (klass ? klass.length : null))
    .join(' ');

  const labelClasses = [
    styles.label,
    isInvalid ? styles.labelError : '',
    isInline ? styles.labelInline : '',
    size ? styles[`label${capitalize(size)}`] : '',
    labelCss,
  ];
  const labelClassesJoined = labelClasses.filter((klass) => klass.length).join(' ');

  const invalidClasses = size ? styles[`fieldError${capitalize(size)}`] : styles.fieldError;
  const helpClasses = size ? styles[`fieldHelp${capitalize(size)}`] : styles.fieldHelp;
  const addonContainerClasses = styles.inputAddonContainer;

  const renderInput = () => (
    <input
      id={id}
      name={id}
      defaultValue={defaultValue}
      type={type}
      disabled={isDisabled}
      className={inputClassesJoined}
      placeholder={placeholder}
      onChange={onChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...rest}
    />
  );

  const renderAddonsOrInputs = () => {
    if (hasLeftAddon || hasRightAddon) {
      return (
        <div className={addonContainerClasses}>
          {addOnLeft && <div className={styles.leftAddon}>{addOnLeft}</div>}
          {renderInput()}
          {addOnRight && <div className={styles.rightAddon}>{addOnRight}</div>}
        </div>
      );
    }
    return renderInput();
  };

  return (
    <div className="width-full">
      <label className={labelClassesJoined} htmlFor={id}>
        {label}
      </label>
      {type === 'textarea' ? (
        <textarea
          id={id}
          name={id}
          placeholder={placeholder}
          defaultValue={defaultValue}
          className={inputClassesJoined}
          disabled={isDisabled}
          onChange={onChange}
          onFocus={onFocus}
          onBlur={onBlur}
          rows={rows}
          cols={cols}
        />
      ) : (
        renderAddonsOrInputs()
      )}
      {isInvalid && (
        <span role="status" aria-live="polite" className={invalidClasses}>
          {invalidText}
        </span>
      )}
      {helpText && <span className={helpClasses}>{helpText}</span>}
    </div>
  );
};
