// agnostic-angular/libs/ag/src/lib/select.component.ts
import { Input, Output, ChangeDetectionStrategy, Component, EventEmitter } from '@angular/core';
export interface SelectOptions {
  value: string,
  label: string,
}

@Component({
  selector: 'ag-select',
  template: `<label class="screenreader-only" [attr.for]="uniqueId">{{labelCopy}}</label>
  <select
    [id]="uniqueId"
    [name]="name"
    [ngClass]="selectClasses()"
    [disabled]="isDisabled"
    [multiple]="isMultiple"
    [size]="isMultiple && multipleSize"
    (change)="changeSelection($event)"
  >
    <option *ngIf="showDefaultOption()" [value]="null" disabled selected> {{ defaultOptionLabel }}</option>
    <option *ngFor="let option of options" [value]="option.value">
      {{ option.label }}
    </option>
  </select>`,
  styleUrls: ['./select.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectComponent {
  private selected = '';

  @Input() uniqueId!: string;
  @Input() labelCopy!: string;
  @Input() defaultOptionLabel?: string = "Please select an option";
  @Input() name!: string;
  @Input() options!: SelectOptions[];
  @Input() isDisabled?: boolean = false;
  @Input() isMultiple?: boolean = false;
  @Input() multipleSize?: number = 1;
  @Input() size?: 'small' | 'large' | '' = '';

  @Output()
  changed = new EventEmitter();

  showDefaultOption() {
    return !this.isMultiple;
  }

  changeSelection(ev: Event) {
    const option = ev.target as HTMLOptionElement;
    this.selected = option.value;
    this.changed.emit(this.selected);
  }

  selectClasses() {
    return [
      'select',
      this.size ? `select-${this.size}` : ''
    ].filter(c => c).join(' ');
  }
}

// agnostic-react/src/Select.tsx
import { FC } from 'react';
import styles from './select.module.css';

export interface SelectOptions {
  value: string;
  label: string;
}

export interface SelectProps {
  uniqueId: string;
  name: string;
  labelCopy: string;
  options: SelectOptions[];
  size?: 'small' | 'large' | '';
  multipleSize?: number;
  isMultiple?: boolean;
  defaultOptionLabel?: string;
  isDisabled?: boolean;
  isSkinned?: boolean;
  css?: string;
}

export const Select: FC<SelectProps> = ({
  uniqueId,
  name,
  labelCopy,
  options,
  size = '',
  multipleSize,
  isMultiple = false,
  defaultOptionLabel = 'Please select an option',
  isDisabled,
  isSkinned = true,
  css = '',
}): JSX.Element => {
  const sizeCapitalized = size ? `${size.slice(0, 1).toUpperCase()}${size.slice(1)}` : '';

  const classes = [
    isSkinned ? styles.select : styles.selectBase,
    size ? styles[`select${sizeCapitalized}`] : '',
    css ? `${css}` : '',
  ]
    .filter((cl) => cl)
    .join(' ');

  const showDefaultOption = !isMultiple;

  return (
    <>
      <label className="screenreader-only" htmlFor={uniqueId}>
        {labelCopy}
      </label>
      <select
        className={classes}
        id={uniqueId}
        name={name}
        disabled={isDisabled}
        multiple={isMultiple}
        size={multipleSize}
        defaultValue={showDefaultOption ? 'select-option' : undefined}
      >
        {showDefaultOption && (
          <option value="select-option" disabled>
            {defaultOptionLabel}
          </option>
        )}
        {options.map(({ value, label }, i) => (
          // eslint-disable-next-line react/no-array-index-key
          <option key={i} value={value}>
            {label}
          </option>
        ))}
      </select>
    </>
  );
};
