// agnostic-angular/libs/ag/src/lib/spinner.component.ts
import { Input, ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'ag-spinner',
  template: `<div [class]="spinnerClasses" role="status" attr.aria-live="polite" [attr.aria-busy]="true">
    <span class="screenreader-only">{{ariaLabel}}</span>
  </div>`,
  styleUrls: ['./spinner.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpinnerComponent {
  @Input() size: 'small' | 'large' | 'xlarge' | '' = '';
  @Input() ariaLabel: string = 'Loading…';

  public get spinnerClasses() {
    return [
      'spinner',
      `spinner-${this.size}`,
    ].filter((cl) => cl).join(' ');
  }
}

// agnostic-react/src/Spinner.tsx
import { FC, ReactElement } from 'react';
import styles from './spinner.module.css';

export interface SpinnerProps {
  size?: 'small' | 'large' | 'xlarge' | '';
  ariaLabel?: string;
}

export const Spinner: FC<SpinnerProps> = ({ ariaLabel = 'Loading…', size = '' }): ReactElement => {
  const sizeCapitalized = size ? `${size.slice(0, 1).toUpperCase()}${size.slice(1)}` : '';
  const spinnerClasses = [styles.spinner, size ? styles[`spinner${sizeCapitalized}`] : '']
    .filter((cls) => cls)
    .join(' ');

  return (
    <div className={spinnerClasses} role="status" aria-live="polite" aria-busy="true">
      <span className="screenreader-only">{ariaLabel}</span>
    </div>
  );
};
