// agnostic-angular/libs/ag/src/lib/table.component.ts
import {
  Input,
  ChangeDetectionStrategy,
  Component,
  TemplateRef,
  ViewChild,
  OnInit,
} from '@angular/core';
import { combineLatest, BehaviorSubject } from 'rxjs';

export interface TableHeaderCell {
  label: string;
  key: string;
  sortable?: boolean;
  width?: string;
  /**
   * Custom sorting `compareFunction` which will take the values from the
   * two respective row cells being compared.
   * See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description
   */
  sortFn?: (cellLeft: any, cellRight: any) => -1 | 0 | 1;
}

@Component({
  selector: 'ag-table',
  template: `<div [class]="tableResponsiveClasses">
    <table [class]="tableClasses">
      <caption [class]="captionClasses">
        {{ caption }}
      </caption>
      <thead>
        <tr>
          <th
            *ngFor="let headerCol of headers"
            [attr.aria-sort]="getSortDirectionFor(headerCol.key)"
            scope="col"
            [style.width]="headerCol.width ? headerCol.width : 'auto'"
          >
            <div
              class="table-header-container"
              *ngIf="headerCol.sortable; else unsortable"
            >
              <span class="table-sort-label">{{ headerCol.label }}</span>
              <button
                type="button"
                class="table-sort"
                (click)="handleSortClicked(headerCol.key)"
              >
                <span class="screenreader-only">{{ headerCol.label }}</span>
                <span [class]="getSortingClassesFor(headerCol.key)"></span>
              </button>
            </div>
            <ng-template #unsortable>
              {{ headerCol.label }}
            </ng-template>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let row of rows$ | async; index as i">
          <td *ngFor="let col of row | keyvalue: preserveOriginalOrder; index as cIndex">
            <ng-template #defaultRow>
              {{ row[col.key] }}
            </ng-template>
            <ng-container
              [ngTemplateOutlet]="rowRenderTemplate ? rowRenderTemplate : defaultRow"
              [ngTemplateOutletContext]="{ $implicit: row[col.key], index: cIndex }"
            >
            </ng-container>
          </td>
        </tr>
      </tbody>
    </table>
  </div>`,
  styleUrls: ['./table.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableComponent implements OnInit {
  /**
   * If consumer passes rowRenderTemplate, we project into td cell's template outlet.
   */
  @Input()
  public rowRenderTemplate?: TemplateRef<any>;

  @Input() headers!: TableHeaderCell[];
  @Input() rows!: any[];
  @Input() caption!: string;
  @Input() captionPosition?: 'top' | 'bottom' | 'end' | 'hidden' = 'hidden';
  @Input() isUppercasedHeaders?: boolean = false;
  @Input() isBordered?: boolean = false;
  @Input() isBorderless?: boolean = false;
  @Input() isStriped?: boolean = false;
  @Input() isHoverable?: boolean = false;
  @Input() isStacked?: boolean = false;
  @Input() tableSize?: '' | 'small' | 'large' | 'xlarge' = '';
  @Input() responsiveSize?: '' | 'small' | 'medium' | 'large' | 'xlarge';

  /**
   * This keeps our reactively sorted rows; reacts to changes made to
   * sortingKey$ or direction$ below.
   */
  private rows$;
  private sortingKey$ = new BehaviorSubject<string>('');
  private direction$ = new BehaviorSubject<'none' | 'ascending' | 'descending'>('none');


  constructor() {
    this.rows$ = new BehaviorSubject<any[]>(this.rows);
  }

  /**
   * Using keyvalue by default with sort our columns alphabetically and we
   * want to preserve the original ordering of Object.keys(A_ROW_OBJECT)
   * *ngFor="let col of row | keyvalue: preserveOriginalOrder;
   */
  preserveOriginalOrder = (a: any, b: any) => {
    return a;
  }

  /**
  * This function first checks if there is a corresponding custom sort function
  * that was supplied in a header cell with key" of `sortingKey` named `.sortFn`
  * per the API. If it finds, it will delegate to that for actual sort comparison.
  * Otherwise, the function supplies its own fallback default (naive) sorting logic.
  */
  internalSort(rowLeft: any, rowRight: any) {
    /**
     * Pluck out our columns so we can compare.
     */
    let colLeft =
      rowLeft[this.sortingKey$.value] === null ||
        rowLeft[this.sortingKey$.value] === undefined
        ? -Infinity
        : rowLeft[this.sortingKey$.value];
    let colRight =
      rowRight[this.sortingKey$.value] === null ||
        rowRight[this.sortingKey$.value] === undefined
        ? -Infinity
        : rowRight[this.sortingKey$.value];

    /**
     * Check if corresponding header cell has a custom sort method. If so,
     * we use that. Otherwise, we proceed with our default sort implementation.
     */
    const headerWithCustomSortFunction = this.headers.find(
      (h) => h.key === this.sortingKey$.value && !!h.sortFn
    );
    if (headerWithCustomSortFunction && headerWithCustomSortFunction.sortFn) {
      return headerWithCustomSortFunction.sortFn(colLeft, colRight);
    }

    /**
     * No custom sort method for the header cell, so we continue with our own fallback.
     * Strings converted to lowercase; dollar currency etc. stripped (not yet i18n safe!)
     */
    colLeft =
      typeof colLeft === "string"
        ? colLeft.toLowerCase().replace(/(^\$|,)/g, "")
        : colLeft;

    colRight =
      typeof colRight === "string"
        ? colRight.toLowerCase().replace(/(^\$|,)/g, "")
        : colRight;

    /**
     * If the raw value represents a number, explicitly set it to a Number
     */
    colLeft = !Number.isNaN(Number(colLeft)) ? Number(colLeft) : colLeft;
    colRight = !Number.isNaN(Number(colRight)) ? Number(colRight) : colRight;

    if (colLeft > colRight) {
      return 1;
    }
    if (colLeft < colRight) {
      return -1;
    }
    return 0;
  };

  // Just flips the sign of results of an ascending sort (internalSort)
  descendingSort(row1: any, row2: any) {
    return this.internalSort(row1, row2) * -1;
  }

  ngOnInit() {
    /**
     * Listens for any changes to our sorting key (which table header was last clicked), and
     * the sort direction (asc, desc, none). Then sorts and places results in this.row$.next
     */
    combineLatest([this.sortingKey$, this.direction$])
      .subscribe(value => {
        let rows = [...this.rows];
        const [_, direction] = value;
        if (direction === 'ascending') {
          rows.sort((a, b) => this.internalSort(a, b));
        } else if (direction === "descending") {
          rows.sort((a, b) => this.descendingSort(a, b));
        } else {
          rows = [...this.rows];
        }
        this.rows$.next(rows);
      })
  }

  handleSortClicked(headerKey: string) {
    /**
     * User's clicked a different header cell, so we change the sorting key
     * and set the initial direction to 'none'
     */
    if (this.sortingKey$.value !== headerKey) {
      this.direction$.next('none');
      this.sortingKey$.next(headerKey);
    }

    switch (this.direction$.value) {
      case 'ascending':
        this.direction$.next('descending');
        break;
      case 'descending':
        this.direction$.next('none');
        break;
      case 'none':
        this.direction$.next('ascending');
        break;
      default:
        /* eslint-disable-next-line no-console */
        console.warn('Table sorting only supports directions: ascending | descending | none');
    }
  };

  getSortingClassesFor(headerKey: string) {
    // If it's the header currently being sorting on, add direction-based classes
    if (this.sortingKey$.value === headerKey) {
      return [
        'icon-sort',
        this.direction$.value !== 'none' ? `icon-sort-${this.direction$.value}` : '',
      ].filter((c) => c.length).join(' ');
    }
    return 'icon-sort';
  }

  getSortDirectionFor(headerKey: string) {
    if (this.sortingKey$.value !== headerKey) {
      return "none";
    } else {
      return this.direction$.value;
    }
  }

  public get captionClasses() {
    return [
      this.captionPosition === 'hidden' ? 'screenreader-only' : '',
      this.captionPosition !== 'hidden'
        ? `caption-${this.captionPosition}`
        : '',
    ]
      .filter((cl) => cl)
      .join(' ');
  }

  public get tableResponsiveClasses(): string {
    return this.responsiveSize
      ? `table-responsive-${this.responsiveSize}`
      : 'table-responsive';
  }

  public get tableClasses(): string {
    return [
      'table',
      this.tableSize ? `table-${this.tableSize}` : '',
      this.isUppercasedHeaders ? 'table-caps' : '',
      this.isBordered ? 'table-bordered' : '',
      this.isBorderless ? 'table-borderless' : '',
      this.isStriped ? 'table-striped' : '',
      this.isHoverable ? 'table-hoverable' : '',
      this.isStacked ? 'table-stacked' : '',
    ]
      .filter((cl) => cl)
      .join(' ');
  }
}

// agnostic-react/src/Table.tsx
import React, { FC, useState } from 'react';
import styles from './table.module.css';

export interface TableHeaderCell {
  label: string;
  key: string;
  sortable?: boolean;
  width?: string;
  // TODO -- in our loop we can then check if headers[cIndex].renderFn then use
  // renderFn?: (rowValue: string) => React.ReactElement,
  /**
   * Custom sorting `compareFunction` which will take the values from the
   * two respective row cells being compared.
   * See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description
   */
  sortFn?: (cellLeft: any, cellRight: any) => -1 | 0 | 1;
}

/**
 * Header Cell Components
 * A th cell that only has a label like <th scope="col">foo</th>
 */
export interface HeaderCellProps {
  headerCell: TableHeaderCell;
}

export const HeaderCell: FC<HeaderCellProps> = ({ headerCell }) => (
  <th scope="col" key={headerCell.key} style={headerCell.width ? { width: headerCell.width } : {}}>
    {headerCell.label}
  </th>
);

/**
 * Sortable Header Cell Components
 * A th cell that has sorting enabled and thus a table sort button to sort
 * the rows by this column's key.
 */
export type Direction = 'ascending' | 'descending' | 'none';
export interface SortableHeaderCellProps extends HeaderCellProps {
  sortHandler: (key: string) => void;
  iconSortClasses: string;
  direction: Direction;
}

export const SortableHeaderCell: FC<SortableHeaderCellProps> = ({
  headerCell,
  sortHandler,
  direction,
  iconSortClasses,
}) => (
  <th
    aria-sort={direction}
    scope="col"
    key={headerCell.key}
    style={headerCell.width ? { width: headerCell.width } : {}}
  >
    <div className={styles.tableHeaderContainer}>
      <span className={styles.tableSortLabel}>{headerCell.label}</span>
      <button
        type="button"
        className={styles.tableSort}
        onClick={() => sortHandler(headerCell.key)}
      >
        <span className="screenreader-only">{headerCell.label}</span>
        <span className={iconSortClasses} />
      </button>
    </div>
  </th>
);

/**
 * Main Table Component
 */
export interface TableProps {
  headers: TableHeaderCell[];
  rows: any[];
  tableSize?: '' | 'small' | 'large' | 'xlarge';
  responsiveSize?: '' | 'small' | 'medium' | 'large' | 'xlarge';
  captionPosition?: 'top' | 'bottom' | 'end' | 'hidden';
  caption: string;
  isUppercasedHeaders?: boolean;
  isBordered?: boolean;
  isBorderless?: boolean;
  isStriped?: boolean;
  isHoverable?: boolean;
  isStacked?: boolean;
}

export const Table: FC<TableProps> = ({
  headers,
  rows,
  caption,
  captionPosition = 'hidden',
  responsiveSize = '',
  tableSize = '',
  isUppercasedHeaders = false,
  isBordered = false,
  isBorderless = false,
  isStriped = false,
  isHoverable = false,
  isStacked = false,
}) => {
  const [direction, setDirection] = useState<Direction>('none');
  const [sortingKey, setSortingKey] = useState('');

  /**
   * Plucks the columns from rows by key of the current sortingKey; sortingKey
   * reflects the currently being sorted column due to user interaction e.g. they
   * have clicked on that columns table header cell.
   *
   * Since we want to sort rows but by column comparisons, we need to "pluck out"
   * these columns from the two rows. If we cannot find the columns in rows by the
   * `sortingKey`, then we set these to `-Infinity`.
   *
   * @param rowLeft left row to compare
   * @param rowRight right row to compare
   * @returns Normalized columns from both rows in form of { a:a, b:b }
   */
  const pluckColumnToSort = (rowLeft: any, rowRight: any) => {
    const colLeft = rowLeft[sortingKey] === null || rowLeft[sortingKey] === undefined
      ? -Infinity
      : rowLeft[sortingKey];
    const colRight = rowRight[sortingKey] === null || rowRight[sortingKey] === undefined
      ? -Infinity
      : rowRight[sortingKey];
    return {
      colLeft,
      colRight,
    };
  };

  /**
   * This function first checks if there is a corresponding custom sort function
   * that was supplied in a header cell with key" of `sortingKey` named `.sortFn`
   * per the API. If it finds, it will delegate to that for actual sort comparison.
   * Otherwise, the function supplies its own fallback default (naive) sorting logic.
   * @param rowLeft left row to compare
   * @param rowRight right row to compare
   * @returns Standard `Array.sort`'s `compareFunction` return of 0, -1, or 1
   */
  const internalSort = (rowLeft: any, rowRight: any) => {
    let { colLeft, colRight } = pluckColumnToSort(rowLeft, rowRight);
    /**
     * First check if the corresponding header cell has a custom sort
     * method. If so, we use that, else we proceed with our default one.
     */
    const headerWithCustomSortFunction = headers.find(
      (h: TableHeaderCell) => h.key === sortingKey && !!h.sortFn,
    );
    if (headerWithCustomSortFunction && headerWithCustomSortFunction.sortFn) {
      return headerWithCustomSortFunction.sortFn(colLeft, colRight);
    }

    // No custom sort method for the header cell, so we continue with our own.
    // Strings converted to lowercase; dollar currency etc. stripped (not yet i18n safe!)
    colLeft = typeof colLeft === 'string' ? colLeft.toLowerCase().replace(/(^\$|,)/g, '') : colLeft;
    colRight = typeof colRight === 'string' ? colRight.toLowerCase().replace(/(^\$|,)/g, '') : colRight;

    // If raw value represents a number explicitly set to Number
    colLeft = !Number.isNaN(Number(colLeft)) ? Number(colLeft) : colLeft;
    colRight = !Number.isNaN(Number(colRight)) ? Number(colRight) : colRight;

    if (colLeft > colRight) {
      return 1;
    }
    if (colLeft < colRight) {
      return -1;
    }
    return 0;
  };

  // Simply flips the sign of results of the ascending sort
  const descendingSort = (r: any, r2: any) => internalSort(r, r2) * -1;
  /**
   * This memoized function is what actually sorts the array of items. It relies
   * on state updates, but just delegates to the other sorting routines.
   */
  const sortedRows = React.useMemo(() => {
    const sortableItems = [...rows];
    if (direction === 'ascending') {
      sortableItems.sort(internalSort);
    } else if (direction === 'descending') {
      sortableItems.sort(descendingSort);
    }
    // If direction was 'none' this will be the original unadultrated rows
    return sortableItems;
  }, [rows, sortingKey, direction]);

  /**
   * Updates sorting states: `direction` and `sortingKey` when a `SortableHeaderCell` clicked
   * @param headerKey the key of this header cell
   */
  const handleSortClicked = (headerKey: string): void => {
    // Our last direction state starts as the "latest direction". But, we have to account
    // for when the user clicks an entirely different sort header from the last one. In
    // this case, we always want to start anew with direction set as 'none'.
    let latestDirection = direction;
    if (sortingKey !== headerKey) {
      latestDirection = 'none';
      setSortingKey(headerKey);
    }

    switch (latestDirection) {
      case 'ascending':
        setDirection('descending');
        break;
      case 'descending':
        setDirection('none');
        break;
      case 'none':
        setDirection('ascending');
        break;
      default:
        /* eslint-disable-next-line no-console */
        console.warn('Table sorting only supports directions: ascending | descending | none');
    }
  };

  /**
   * Generates th header cell classes on `SortableHeaderCell`'s which are used to
   * display the appropriate sorting icons.
   * @param headerKey the key of this header cell
   * @returns CSS classes appropriate for the `SortableHeaderCell`'s current sorting state
   */
  const getSortingClassesFor = (headerKey: string) => {
    // If it's the header currently being sorting on, add direction-based classes
    if (sortingKey === headerKey) {
      const directionCapitalized = direction
        ? `${direction.slice(0, 1).toUpperCase()}${direction.slice(1)}`
        : '';
      return [
        styles.iconSort,
        direction && direction !== 'none' ? styles[`iconSort${directionCapitalized}`] : '',
      ]
        .filter((c) => c.length)
        .join(' ');
    }
    // If not currently being sorted apply base class only
    return styles.iconSort;
  };

  /**
   * CSS class generation routines
   */
  const captionPositionCapitalized = captionPosition
    ? `${captionPosition.slice(0, 1).toUpperCase()}${captionPosition.slice(1)}`
    : '';

  let captionClasses;
  if (captionPosition === 'hidden') {
    captionClasses = 'screenreader-only';
  } else {
    captionClasses = styles[`tableResponsive${captionPositionCapitalized}`];
  }

  const tableResponsiveSizeCapitalized = responsiveSize
    ? `${responsiveSize.slice(0, 1).toUpperCase()}${responsiveSize.slice(1)}`
    : '';

  const tableResponsiveClasses = responsiveSize
    ? styles[`tableResponsive${tableResponsiveSizeCapitalized}`]
    : styles.tableResponsive;

  const tableSizeCapitalized = tableSize
    ? `${tableSize.slice(0, 1).toUpperCase()}${tableSize.slice(1)}`
    : '';

  const tableClasses = [
    styles.table,
    tableSize ? styles[`table${tableSizeCapitalized}`] : '',
    isUppercasedHeaders ? styles.tableCaps : '',
    isBordered ? styles.tableBordered : '',
    isBorderless ? styles.tableBorderless : '',
    isStriped ? styles.tableStriped : '',
    isHoverable ? styles.tableHoverable : '',
    isStacked ? styles.tableStacked : '',
  ]
    .filter((cl) => cl)
    .join(' ');

  return (
    <div className={tableResponsiveClasses}>
      <table className={tableClasses}>
        <caption className={captionClasses}>{caption}</caption>
        <thead>
          <tr>
            {headers.map((headerCell: TableHeaderCell) => (headerCell.sortable ? (
              <SortableHeaderCell
                key={headerCell.key}
                headerCell={headerCell}
                sortHandler={handleSortClicked}
                direction={direction}
                iconSortClasses={getSortingClassesFor(headerCell.key)}
              />
            ) : (
              <HeaderCell headerCell={headerCell} />
            )))}
          </tr>
        </thead>
        <tbody>
          {sortedRows.map((row, i) => (
            // eslint-disable-next-line react/no-array-index-key
            <tr key={i}>
              {Object.keys(row).map((key, cIndex) => (
                // eslint-disable-next-line react/no-array-index-key
                <td key={cIndex}>{row[key]}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
