// agnosticui-react/src/stories/Header.js
import React from 'react';
import PropTypes from 'prop-types';
import styles from './header.module.css';

export const HeaderNav = ({ children, css }) => {
  let klasses = [
    styles.headerNav,
    css ? `${css}` : "",
  ];
  klasses = klasses.filter((klass) => klass.length);
  klasses = klasses.join(" ");
  return (
    <nav>
      <ul className={klasses}>
        {children}
      </ul>
    </nav>
  )
}

export const HeaderNavItem = ({ children, css }) => {
  let klasses = [
    styles.headerNavItem,
    css ? `${css}` : "",
  ];
  klasses = klasses.filter((klass) => klass.length);
  klasses = klasses.join(" ");
  return (
    <li className={klasses}>
      {children}
    </li>
  )
}

const Header = ({ children, css, isSticky, isSkinned }) => {
  let klasses = [
    isSkinned ? styles.header : styles.headerBase,
    isSticky ? styles.sticky : '',
    css ? `${css}` : "",
  ];
  klasses = klasses.filter((klass) => klass.length);
  klasses = klasses.join(" ");

  return (
    <header className={klasses}>
      <div className={styles['headerContent']}>
        {children}
      </div>
    </header>
  )
}

Header.propTypes = {
  css: PropTypes.string,
  isSticky: PropTypes.bool,
  isSkinned: PropTypes.bool,
}

Header.defaultProps = {
  css: undefined,
  isSticky: false,
  isSkinned: true,
}

export default Header;

// agnosticui-angular/src/stories/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'ag-header-nav',
  template: `<nav>
    <ul [ngClass]="classes">
      <ng-content></ng-content>
    </ul>
  </nav>`,
  styleUrls: ['./headernav.css'],
})

export class HeaderNav {
  @Input() css?: string;
  public get classes(): string {
    let klasses = ['header-nav', this.css ? `${this.css}` : ''];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ')
  }
}

@Component({
  selector: 'ag-header-nav-item',
  template: `<li [ngClass]="classes"><ng-content></ng-content></li>`,
  styleUrls: ['./headernavitem.css'],
})

export class HeaderNavItem {
  @Input() css?: string;
  public get classes(): string {
    let klasses = ['header-nav', this.css ? `${this.css}` : ''];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}

@Component({
  selector: 'ag-header',
  template: `<header [ngClass]="classes">
    <div class="header-content"><ng-content></ng-content></div>
  </header>
  `,
  styleUrls: ['./header.css'],
})

export default class Header {
  @Input() css?: string;
  @Input() isSkinned?: boolean = true;
  @Input() isSticky?: boolean;
  
  public get classes(): string {
    const baseClass = this.isSkinned ? 'header' : 'header-base';
    const isStickyClass = this.isSticky ? 'header-sticky' : '';
    const overrides = this.css ? `${this.css}` : '';
    let klasses = [
      baseClass,
      isStickyClass,
      overrides,
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}
