// v2/playbooks/grid/react-example-v2/src/App.tsx
import { useState, useEffect } from 'react'
import { Sun, Moon } from 'lucide-react'
import { ReactHeader } from './components/ag/Header/react/ReactHeader'
import { ReactBreadcrumb } from './components/ag/Breadcrumb/react/ReactBreadcrumb'
import { ReactAvatar } from './components/ag/Avatar/react/ReactAvatar'
import { ReactSpinner } from './components/ag/Spinner/react/ReactSpinner'
import { SkinSwitcher } from './SkinSwitcher'
import { products } from './data/products'
import { TanstackPanel } from './panels/TanstackPanel'

export default function App() {
  const [isLoading, setIsLoading] = useState(true)
  const [isDark, setIsDark] = useState(
    () => document.documentElement.getAttribute('data-theme') === 'dark'
  )

  useEffect(() => {
    const t = setTimeout(() => setIsLoading(false), 1000)
    return () => clearTimeout(t)
  }, [])

  function toggleTheme() {
    const html = document.documentElement
    const dark = html.getAttribute('data-theme') === 'dark'
    if (dark) { html.removeAttribute('data-theme'); setIsDark(false) }
    else { html.setAttribute('data-theme', 'dark'); setIsDark(true) }
  }

  const breadcrumbItems = [
    { label: 'Home', href: '/' },
    { label: 'Inventory', current: true },
  ]

  return (
    <>
      <SkinSwitcher />
      <ReactHeader contentJustify="between">
        <span slot="logo" style={{ fontWeight: 700, fontSize: '1.125rem', color: 'var(--ag-primary)' }}>
          AgnosticUI
        </span>
        <button className="theme-toggle" aria-label="Toggle theme" onClick={toggleTheme}>
          {isDark ? <Sun size={18} /> : <Moon size={18} />}
        </button>
        <ReactAvatar text="AB" variant="info" />
      </ReactHeader>

      <main className="app-main">
        <ReactBreadcrumb items={breadcrumbItems} type="slash" />

        <div className="page-title-row">
          <h1 className="page-title">Inventory</h1>
        </div>

        {isLoading ? (
          <div className="page-loading">
            <ReactSpinner size="large" aria-label="Loading inventory…" />
          </div>
        ) : (
          <TanstackPanel products={products} />
        )}
      </main>
    </>
  )
}

// v2/playbooks/grid/vue-example-v2/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Sun, Moon } from 'lucide-vue-next'
import VueHeader from './components/ag/Header/vue/VueHeader.vue'
import VueBreadcrumb from './components/ag/Breadcrumb/vue/VueBreadcrumb.vue'
import VueAvatar from './components/ag/Avatar/vue/VueAvatar.vue'
import VueSpinner from './components/ag/Spinner/vue/VueSpinner.vue'
import SkinSwitcher from './SkinSwitcher.vue'
import { products } from './data/products'
import TanstackPanel from './panels/TanstackPanel.vue'

const isLoading = ref(true)
const isDark = ref(document.documentElement.getAttribute('data-theme') === 'dark')

let loadTimer: ReturnType<typeof setTimeout> | null = null

onMounted(() => {
  loadTimer = setTimeout(() => { isLoading.value = false }, 1000)
})

onUnmounted(() => {
  if (loadTimer) clearTimeout(loadTimer)
})

function toggleTheme() {
  const html = document.documentElement
  const dark = html.getAttribute('data-theme') === 'dark'
  if (dark) { html.removeAttribute('data-theme'); isDark.value = false }
  else { html.setAttribute('data-theme', 'dark'); isDark.value = true }
}

const breadcrumbItems = [
  { label: 'Home', href: '/' },
  { label: 'Inventory', current: true },
]
</script>

<template>
  <SkinSwitcher />
  <VueHeader content-justify="between">
    <template #logo>
      <span style="font-weight: 700; font-size: 1.125rem; color: var(--ag-primary)">AgnosticUI</span>
    </template>
    <button class="theme-toggle" aria-label="Toggle theme" @click="toggleTheme">
      <Sun v-if="isDark" :size="18" />
      <Moon v-else :size="18" />
    </button>
    <VueAvatar text="AB" variant="info" />
  </VueHeader>

  <main class="app-main">
    <VueBreadcrumb :items="breadcrumbItems" type="slash" />

    <div class="page-title-row">
      <h1 class="page-title">Inventory</h1>
    </div>

    <div v-if="isLoading" class="page-loading">
      <VueSpinner size="large" aria-label="Loading inventory…" />
    </div>
    <TanstackPanel v-else :products="products" />
  </main>
</template>
