// agnosticui-react/src/ChoiceInput.tsx
import React, { FC, useState } from 'react';
import { v4 as uuidv4 } from 'uuid';
import styles from './choice-input.module.css';

export interface ChoiceProps {
  id: string;
  name: string;
  value?: string;
  disabled?: boolean;
  classes?: string;
  type?: 'checkbox' | 'radio';
  checked?: boolean;
  onChange: React.ChangeEventHandler<HTMLInputElement> | undefined;
}

export const Choice: FC<ChoiceProps> = ({
  id,
  name,
  value,
  disabled = false,
  classes = '',
  type = 'checkbox',
  checked = false,
  onChange,
}) => (
  <>
    <label className="screenreader-only" htmlFor={id}>{`Choice input ${name}`}</label>
    <input
      id={id}
      className={classes}
      type={type}
      name={name}
      value={value}
      checked={checked}
      onChange={onChange}
      disabled={disabled}
    />
  </>
);

export interface ChoiceInputProps {
  id: string;
  css?: string;
  legendLabel: string;
  isInline?: boolean;
  isSkinned?: boolean;
  isFieldset?: boolean;
  isDisabled?: boolean;
  type?: 'checkbox' | 'radio';
  size?: 'small' | 'large' | '';
  // TODO Type all these options
  options: any[];
  disabledOptions?: any[];
  checkedOptions?: any[];
  onChange: (checkedItems: any[]) => void; // eslint-disable-line no-unused-vars
}

export const ChoiceInput: FC<ChoiceInputProps> = ({
  id,
  css,
  isInline = false,
  legendLabel,
  isFieldset = true,
  isSkinned = true,
  isDisabled = false,
  options,
  disabledOptions = [],
  checkedOptions = [],
  size = '',
  type = 'checkbox',
  onChange,
}) => {
  const precheckedOptions = Array.from(checkedOptions);
  const [checked, setChecked] = useState(precheckedOptions);

  const handleChange = (e: React.ChangeEvent) => {
    const element = e.currentTarget as HTMLInputElement;
    const value = element.value as string;

    if (type === 'checkbox') {
      let checkedItemsUpdated;
      if (checked.includes(value)) {
        checkedItemsUpdated = checked.filter((item) => item !== value);
        setChecked(checkedItemsUpdated);
      } else {
        checkedItemsUpdated = [...checked, value];
        setChecked(checkedItemsUpdated);
        // Since useState is async we use the value directly here
      }
      if (onChange) {
        onChange(checkedItemsUpdated);
      }
      // Type is radio. We ignore if they're trying to check the currently
      // checked radio
    } else if (!checked.includes(value)) {
      // Since you can only have one checked radio at a time, we simply
      // set to the new radio to be checked
      setChecked([value]);
      if (onChange) {
        onChange([value]);
      }
    }
  };

  const legendClasses = () => {
    // If consumer sets is skinned to false we don't style the legend
    const skin = isSkinned ? styles[`${type}-legend`] : '';
    const klasses = [
      skin,
      // .screenreader-only is expected to be globally available via common.min.css
      isFieldset === false ? 'screenreader-only' : null,
    ];
    return klasses.join(' ');
  };

  const labelClasses = () => {
    let klasses = [
      styles[`${type}-label-wrap`],
      isInline ? styles[`${type}-label-wrap-inline`] : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  };

  const labelSpanClasses = () => {
    let klasses = [
      styles[`${type}-label`],
      size ? styles[`${type}-label-${size}`] : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  };

  const fieldsetClasses = () => {
    // If consumer sets is skinned to false we don't style the fieldset
    const skin = isSkinned ? styles[`${type}-group`] : '';

    // we only add the fieldset class for large (not small) e.g. radio|checkbox-group-large
    const sizeSkin = isSkinned && size === 'large' ? styles[`${type}-group-${size}`] : '';
    let klasses = [
      css || '',
      skin,
      sizeSkin,
      isFieldset === false ? styles[`${type}-group-hidden`] : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  };

  const inputClasses = () => {
    let inputKlasses = [
      styles[`${type}`],
      size ? styles[`${type}-${size}`] : '',
      isDisabled ? 'disabled' : '',
    ];
    inputKlasses = inputKlasses.filter((klass) => klass.length);
    return inputKlasses.join(' ');
  };

  return (
    <fieldset className={fieldsetClasses()}>
      <legend className={legendClasses()}>{legendLabel}</legend>
      {options.map(({ name, value, label }, i) => (
        <label key={uuidv4()} htmlFor={`${id}-${name}-${i}`} className={labelClasses()}>
          <Choice
            id={`${id}-${name}-${i}`}
            classes={inputClasses()}
            type={type}
            name={name}
            value={value}
            aria-hidden="true"
            disabled={isDisabled || disabledOptions.includes(value)}
            checked={checked.includes(value)}
            onChange={handleChange}
          />
          <span className={labelSpanClasses()}>{label}</span>
        </label>
      ))}
    </fieldset>
  );
};

// agnosticui-angular/libs/ag/src/lib/choice-input.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from '@angular/core';

@Component({
  selector: 'ag-choice-input',
  template: `<fieldset [ngClass]="fieldsetClass()">
    <legend [ngClass]="legendClasses()">{{ legendLabel }}</legend>
    <ng-container *ngFor="let option of options">
      <label
        [attr.disabled]="isDisabled || disabledOptions?.includes(option.value)"
        [ngClass]="labelClasses()"
      >
        <input
          [ngClass]="inputClasses()"
          [type]="type"
          [name]="option.name"
          [value]="option.value"
          [disabled]="isDisabled || disabledOptions?.includes(option.value)"
          [checked]="checkedOptions?.includes(option.value) || false"
          (change)="this.handleChange($event)"
          aria-hidden="true"
        />
        <span [ngClass]="labelSpanClasses()">{{ option.label }}</span>
      </label>
    </ng-container>
  </fieldset>`,
  styleUrls: ['./choice-input.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChoiceInputComponent {
  @Input() isInline?: boolean = false;
  @Input() isFieldset?: boolean = true;
  @Input() isSkinned?: boolean = true;
  @Input() isDisabled?: boolean = false;
  @Input() options?: any[] = [];
  @Input() disabledOptions?: string[];

  private _checkedOptions: any[] = [];
  get checkedOptions(): any[] {
    return this._checkedOptions;
  }
  @Input()
  set checkedOptions(val: any[]) {
    this._checkedOptions = val;
  }

  @Input() css?: string;
  @Input() legendLabel = '';
  @Input() type!: 'radio' | 'checkbox' = 'checkbox';
  // Medium is default so we just use empty string
  @Input() size: 'small' | 'large' | '' = '';
  // TODO type this
  @Output() selected = new EventEmitter<any>();

  labelSpanClasses() {
    let klasses = [
      this.type ? `${this.type}-label` : '',
      this.size ? `${this.type}-label-${this.size}` : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
  handleChange(ev: Event) {
    const el = ev.target as HTMLInputElement;
    const value = el.value;
    if (this.type === 'checkbox') {
      let checkedItemsUpdated;
      if (this.checkedOptions?.includes(value)) {
        checkedItemsUpdated = this.checkedOptions?.filter(
          (item) => item !== value
        );
        this.checkedOptions = checkedItemsUpdated;
      } else {
        checkedItemsUpdated = [...this.checkedOptions, value];
        this.checkedOptions = checkedItemsUpdated;
      }
      this.selected.emit(checkedItemsUpdated);
    } else {
      // Type is radio. We ignore if they're trying to check the currently checked
      if (this.checkedOptions?.includes(value)) {
        // Since you can only have one checked radio at a time, we simply
        // set to the new radio to be checked
        this.checkedOptions = [value];
        this.selected.emit(this.checkedOptions);
      }
    }
  }
  inputClasses() {
    let inputKlasses = [
      `${this.type}`,
      this.size ? `${this.size}` : '',
      this.isDisabled ? 'disabled' : '',
    ];
    inputKlasses = inputKlasses.filter((klass) => klass.length);
    return inputKlasses.join(' ');
  }
  fieldsetClass() {
    // If consumer sets is skinned to false we don't style the fieldset
    const skin = this.isSkinned ? `${this.type}-group` : '';

    // we only add the fieldset class for large (not small) e.g. radio|checkbox-group-large
    const sizeSkin =
      this.isSkinned && this.size === 'large'
        ? `${this.type}-group-${this.size}`
        : '';

    const overrides = this.css ? `${this.css}` : '';
    const klasses = [
      overrides ? overrides : '',
      skin,
      sizeSkin,
      this.isFieldset === false ? `${this.type}-group-hidden` : '',
    ];
    return klasses.filter((klass) => klass.length);
  }
  legendClasses() {
    const skin = this.isSkinned ? `${this.type}-legend` : '';
    const klasses = [
      skin,
      // .screenreader-only is expected to be globally available via common.min.css
      this.isFieldset === false ? 'screenreader-only' : null,
    ];
    return klasses.join(' ');
  }
  labelClasses() {
    let klasses = [
      this.type ? `${this.type}-label-wrap` : '',
      this.isInline ? `${this.type}-label-wrap-inline` : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}
