// agnostic-angular/libs/ag/src/lib/switch.component.ts
import { Component, EventEmitter, Input, ChangeDetectionStrategy, Output } from '@angular/core';

@Component({
  selector: 'ag-switch',
  template: `<label [ngClass]="switchContainer()">
    <span *ngIf="labelPosition === 'left'" class="switch-label">{{
      label
    }}</span>
    <input
      type="checkbox"
      [checked]="isChecked"
      class="switch-input"
      [disabled]="isDisabled"
      role="switch"
      (change)="toggleChecked($event)"
    />
    <span [ngClass]="switchSpan()" aria-hidden="true"></span>
    <span *ngIf="labelPosition === 'right'" class="switch-label">{{
      label
    }}</span>
  </label>`,
  styleUrls: ['./switch.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent {
  @Input() label!: string;
  @Input() css?: string;
  @Input() labelPosition = 'left';
  @Input() isDisabled?: boolean = false;
  @Input() isAction?: boolean = false;
  @Input() isBordered?: boolean = false;
  @Input() size? = '';

  private switchChecked!: boolean;
  get isChecked(): boolean {
    return this.switchChecked;
  }

  @Input()
  set isChecked(val: boolean) {
    this.switchChecked = val;
  }

  @Output() selected = new EventEmitter<boolean>();

  toggleChecked(ev: Event) {
    const el = ev.target as HTMLInputElement;
    if (el.getAttribute('aria-checked') == 'true') {
      el.setAttribute('aria-checked', 'false');
      this.switchChecked = false;
    } else {
      el.setAttribute('aria-checked', 'true');
      this.switchChecked = true;
    }
    this.selected.emit(this.switchChecked);
  }
  switchContainer() {
    let klasses = [
      'switch-container',
      this.css ? this.css : '',
      this.labelPosition === 'right' ? 'switch-right' : '',
      this.isDisabled ? 'disabled' : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
  switchSpan() {
    let klasses = [
      'switch',
      this.isBordered ? 'switch-border' : '',
      this.isAction ? 'switch-action' : '',
      this.size ? `switch-${this.size}` : '',
    ];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}

// agnosticui-react-ts/src/Switch.tsx
import { FC, HTMLAttributes, useState, KeyboardEvent, MouseEvent } from 'react';
import styles from './switch.module.css';

export interface SwitchProps extends HTMLAttributes<HTMLInputElement> {
  id: string;
  label: string;
  labelPosition?: 'left' | 'right';
  size?: 'small' | 'large' | '';
  isChecked?: boolean;
  isAction?: boolean;
  isBordered?: boolean;
  isDisabled?: boolean;
}

export const Switch: FC<SwitchProps> = ({
  id,
  label,
  labelPosition = 'left',
  size = '',
  isChecked = false,
  isDisabled = false,
  isBordered = false,
  isAction = false,
  onChange,
}) => {
  const [checked, setChecked] = useState(isChecked);

  const switchSpan = () => {
    const klasses = [
      styles.switch,
      isBordered ? styles['switch-border'] : '',
      isAction ? styles['switch-action'] : '',
      size ? styles[`switch-${size}`] : '',
    ];
    return klasses.filter((klass) => klass.length).join(' ');
  };

  const switchContainer = () => {
    const klasses = [
      styles['switch-container'],
      labelPosition === 'right' ? styles['switch-right'] : '',
      isDisabled ? styles.disabled : '',
    ];
    return klasses.filter((klass) => klass.length).join(' ');
  };

  const switchLabel = () => styles['switch-label'];

  const switchInput = () => styles['switch-input'];

  const handleClick = (evt: MouseEvent<HTMLInputElement>) => {
    const el = evt.target as HTMLInputElement;
    if (el.getAttribute('aria-checked') === 'true') {
      el.setAttribute('aria-checked', 'false');
      setChecked(false);
    } else {
      el.setAttribute('aria-checked', 'true');
      setChecked(true);
    }
  };

  const handleKeypress = (evt: KeyboardEvent<HTMLInputElement>) => {
    const keyCode = evt.keyCode || evt.which;
    if (keyCode === 13) {
      evt.preventDefault();
      const target = evt.target as HTMLElement;
      target.click();
    }
  };

  return (
    <label className={switchContainer()} htmlFor={id}>
      {labelPosition === 'left' && <span className={switchLabel()}>{label}</span>}
      <input
        type="checkbox"
        className={switchInput()}
        id={id}
        checked={checked}
        disabled={isDisabled}
        onChange={onChange}
        onClick={handleClick}
        onKeyPress={handleKeypress}
        role="switch"
      />
      <span className={switchSpan()} aria-hidden="true" />
      {labelPosition === 'right' && <span className={switchLabel()}>{label}</span>}
    </label>
  );
};
