// agnostic-vue/examples/src/App.vue
<script>
// Import the required AgnosticUI global common and component CSS
import "agnostic-vue/dist/common.min.css";
import "agnostic-vue/dist/index.css";
import {
  Alert,
  Avatar,
  AvatarGroup,
  Breadcrumb,
  Button,
  Card,
  ChoiceInput,
  Close,
  Disclose,
  Header,
  HeaderNav,
  HeaderNavItem,
  Icon,
  Input,
  InputAddonItem,
  Select,
  Switch,
  Tabs,
  Tag,
} from "agnostic-vue";

import IconExOcticons from "./components/IconExOcticons.vue";

export default {
  name: "App",
  components: {
    Alert,
    AvatarGroup,
    Avatar,
    Breadcrumb,
    Button,
    Card,
    ChoiceInput,
    Close,
    Disclose,
    Header,
    HeaderNav,
    HeaderNavItem,
    Icon,
    IconExOcticons,
    Input,
    InputAddonItem,
    Select,
    Switch,
    Tabs,
    Tag,
  },
  data() {
    return {
      disabledOptions: ["tab-1", "tab-3"],
      tennisRoutes: [
        {
          label: "Tennis",
          url: "#tennis",
        },
        {
          label: "Superstars",
          url: "#tennis-superstars",
        },
        {
          label: "Serena Williams",
          url: "#tennis-superstars-serena",
        },
      ],
    };
  },
};
</script>
<template>
  <div id="app">
    <h1>AgnosticUI Vue</h1>
  </div>
  <h2>Select</h2>
  <div class="mbs12 mbe16">
    <Select
      :options="[{ value: 'andre', label: 'Andre Agassi' }, { value: 'serena', label: 'Serena Williams'} , { value: 'mac', label: 'John McEnroe'}, { value: 'borg', label: 'Bjorn Borg'}, { value: 'althea', label: 'Althea Gibson'}, { value: 'roger', label: 'Roger Federer'}]"
      unique-id="sel1"
      name="select1"
      label-copy="Select the best tennis player of all time"
    />
  </div>
  <h2>Disabled select</h2>
  <div class="mbs12 mbe16">
    <Select
      is-disabled
      :options="[]"
      unique-id="sel2"
      name="select2"
      label-copy="Select -- example disabled"
    />
  </div>
  <h2>Small select</h2>
  <div class="mbs12 mbe16">
    <Select
      size="small"
      :options="[{ value: 'andre', label: 'Andre Agassi' }, { value: 'serena', label: 'Serena Williams'} , { value: 'mac', label: 'John McEnroe'}, { value: 'borg', label: 'Bjorn Borg'}, { value: 'althea', label: 'Althea Gibson'}, { value: 'roger', label: 'Roger Federer'}]"
      unique-id="sel3"
      name="select3"
      label-copy="Select the best tennis player of all time"
    />
  </div>
  <h2>Large select</h2>
  <div class="mbs12 mbe16">
    <Select
      size="large"
      :options="[{ value: 'andre', label: 'Andre Agassi' }, { value: 'serena', label: 'Serena Williams'} , { value: 'mac', label: 'John McEnroe'}, { value: 'borg', label: 'Bjorn Borg'}, { value: 'althea', label: 'Althea Gibson'}, { value: 'roger', label: 'Roger Federer'}]"
      unique-id="sel4"
      name="select4"
      label-copy="Select the best tennis player of all time"
    />
  </div>
  <h2>Multiple select size 4</h2>
  <div class="mbs12 mbe16">
    <Select
      :is-multiple="true"
      multiple-size="4"
      :options="[{ value: 'andre', label: 'Andre Agassi' }, { value: 'serena', label: 'Serena Williams'} , { value: 'mac', label: 'John McEnroe'}, { value: 'borg', label: 'Bjorn Borg'}, { value: 'althea', label: 'Althea Gibson'}, { value: 'roger', label: 'Roger Federer'}]"
      unique-id="sel4"
      name="select4"
      label-copy="Select the best tennis player of all time"
    />
  </div>
  <h2>Breadcrumbs</h2>
  <div class="mbs24 mbe16">
    <Breadcrumb :routes="tennisRoutes" />
    <Breadcrumb
      type="slash"
      :routes="tennisRoutes"
    />
    <Breadcrumb
      type="bullet"
      :routes="tennisRoutes"
    />
    <Breadcrumb
      type="arrow"
      :routes="tennisRoutes"
    />
    <Breadcrumb :routes="[{ label: 'A single route will look *linkless*' }]" />
    <Breadcrumb :routes="[{label: 'First', url: '#foo'}, { label: 'Second', url: '#bar' }]" />
  </div>
  <h2>Tabs</h2>
  <div class="mbs24 mbe16">
    <Tabs>
      <template #tab-1>
        Tab 1
      </template>
      <template #panel-1>
        <p>
          Tab 1 content (no padding or margins so consumer can control desired
          gutters) (no padding or margins so consumer can control desired
          gutters)
        </p>
        <p>
          Try tabbing into this. You'll be able to tab through the links, and
          then shift-tab back out. To get to the next tab you use the arrow key
          and enter|space to select. This is consistent with wai-aria practices
          <a href="https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html">
            aria manual activation example</a>.
        </p>
        <p>
          Random <a href="www.yahoo.com">yahoo link 1</a> and random
          <a href="www.yahoo.com">yahoo link 2</a>. Just testing some links out
          :)
        </p>
      </template>
      <template #tab-2>
        Tab 2
      </template>
      <template #panel-2>
        <p>
          Random <a href="www.yahoo.com">yahoo link 1</a> and random
          <a href="www.yahoo.com">yahoo link 2</a>. Just testing some links out
          :)
        </p>
      </template>
      <template #tab-foo>
        Tab Foo
      </template>
      <template #panel-foo>
        Panel Foo content (no padding or margins so consumer can control desired
        gutters)
      </template>
      <template #tab-bar>
        Tab Bar
      </template>
      <template #panel-bar>
        Panel Bar
      </template>
    </Tabs>
  </div>
  <div class="mbs32 mbe16">
    <Tabs size="large">
      <template #tab-11>
        Tab 1
      </template>
      <template #panel-11>
        Panel 1
      </template>
      <template #tab-21>
        Tab 2
      </template>
      <template #panel-21>
        Panel 2
      </template>
    </Tabs>
  </div>
  <h2>Vertical Tabs</h2>
  <div class="mbs48 mbe16">
    <Tabs is-vertical>
      <template #tab-12>
        Tab 1
      </template>
      <template #panel-12>
        <p>
          Vertical tab 1 content (no padding or margins so consumer can control
          desired gutters) (no padding or margins so consumer can control
          desired gutters)
        </p>
        <p>
          Now you'll use the up and down arrows. Home and end still work the
          same. Random <a href="www.yahoo.com">yahoo link 1</a> and random
          <a href="www.yahoo.com">yahoo link 2</a>. Just testing some links out
          :)
        </p>
      </template>
      <template #tab-22>
        Tab 2
      </template>
      <template #panel-22>
        Vertical tab 2 content (no padding or margins so consumer can control
        desired gutters)
      </template>
    </Tabs>
  </div>
  <h2>Disabled Tabs</h2>
  <div class="mbs48 mbe16">
    <Tabs is-disabled>
      <template #tab-13>
        Tab 1
      </template>
      <template #panel-13>
        Panel 1
      </template>
      <template #tab-23>
        Tab 1
      </template>
      <template #panel-23>
        Panel 2
      </template>
    </Tabs>
  </div>
  <h2>Disabled Options</h2>
  <div class="mbs12 mbe16">
    <Tabs :disabled-options="disabledOptions">
      <template #tab-14>
        Tab 1
      </template>
      <template #panel-14>
        Disabled options only make sense if you do NOT supply isDisabled (as
        that disabled all the tab buttons), and you wish to selectively disable
        certain buttons. Here we've obviously disabled the first and third tab.
      </template>
      <template #tab-24>
        Tab 2
      </template>
      <template #panel-24>
        Panel 2
      </template>
      <template #tab-34>
        Tab 3
      </template>
      <template #panel-34>
        Panel 3
      </template>
      <template #tab-44>
        Tab 4
      </template>
      <template #panel-44>
        Panel 4
      </template>
    </Tabs>
  </div>
  <div class="mbs12 mbe16">
    <div>
      <p class="mbe12">
        Custom tabs using an AgnosticUI button requires two things:
      </p>
      <ul class="mbe24">
        <li>
          You need to use the <code>tabType="custom"</code> prop on the tab
        </li>
        <li>
          You need to use the <code>type="faux"</code> prop on the button. This
          is required because the tabs are already buttons so you'd have a
          nested button a11y violation otherwise.
        </li>
      </ul>
      <Tabs tab-type="custom">
        <template #tab-15>
          <Button
            type="faux"
            mode="primary"
            is-bordered
          >
            Tab One
          </Button>
        </template>
        <template #panel-15>
          <p>
            Tab 1 content (no padding or margins so consumer can control desired
            gutters) (no padding or margins so consumer can control desired
            gutters)
          </p>
          <p>
            Try tabbing into this. You'll be able to tab through the links, and
            then shift-tab back out. To get to the next tab you use the arrow
            key and enter|space to select. This is consistent with wai-aria
            practices
            <a href="https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html">
              aria manual activation example</a>.
          </p>
          <p>
            Random <a href="www.yahoo.com">yahoo link 1</a> and random
            <a href="www.yahoo.com">yahoo link 2</a>. Just testing some links
            out :)
          </p>
        </template>
        <template #tab-25>
          <Button
            type="faux"
            mode="primary"
            is-bordered
          >
            Tab Two
          </Button>
        </template>
        <template #panel-25>
          Tab 2 content (no padding or margins so consumer can control desired
          gutters)
        </template>
      </Tabs>
    </div>
  </div>
  <div class="mbs12 mbe16">
    <Avatar
      text="RL"
      size="small"
    />
    <Avatar text="AB" />
    <Avatar
      text="RL"
      size="large"
    />
    <Avatar
      text="RL"
      size="xlarge"
    />
    <Avatar
      is-square
      type="error"
      text="Sq"
    />
  </div>
  <div class="mbs12 mbe16">
    <h2>Icon</h2>
    <p class="mbs24 mbe40">
      Test this in Safari! We need to ensure that the component is actually
      applying a
      <code>width</code> to the SVG itself else Safari the icon won't be visible
    </p>
    <div class="mbe16">
      <Icon :size="14">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="16">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="18">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="20">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="24">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="32">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="36">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="40">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="48">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="56">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbe16">
      <Icon :size="64">
        <IconExOcticons />
      </Icon>
    </div>
    <div class="mbs12 mbe16">
      <h2>Avatars</h2>
      <Avatar>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M12 2.5a5.5 5.5 0 00-3.096 10.047 9.005 9.005 0 00-5.9 8.18.75.75 0 001.5.045 7.5 7.5 0 0114.993 0 .75.75 0 101.499-.044 9.005 9.005 0 00-5.9-8.181A5.5 5.5 0 0012 2.5zM8 8a4 4 0 118 0 4 4 0 01-8 0z"
          />
        </svg>
      </Avatar>
      <Avatar type="info">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M12 2.5a5.5 5.5 0 00-3.096 10.047 9.005 9.005 0 00-5.9 8.18.75.75 0 001.5.045 7.5 7.5 0 0114.993 0 .75.75 0 101.499-.044 9.005 9.005 0 00-5.9-8.181A5.5 5.5 0 0012 2.5zM8 8a4 4 0 118 0 4 4 0 01-8 0z"
          />
        </svg>
      </Avatar>
    </div>
    <div class="mbs12 mbe16">
      <Avatar img-url="https://joeschmoe.io/api/v1/random" />
      <Avatar
        is-transparent
        img-url="https://joeschmoe.io/api/v1/random"
      />
      <Avatar
        type="success"
        img-url="https://joeschmoe.io/api/v1/random"
      />
      <Avatar
        type="info"
        img-url="https://joeschmoe.io/api/v1/random"
      />
    </div>
    <div class="mbs12 mbe16">
      <span class="mie6">
        <Avatar
          type="success"
          text="S"
        />
      </span>
      <span class="mie6">
        <Avatar
          type="info"
          text="I"
        />
      </span>
      <span class="mie6">
        <Avatar
          type="warning"
          text="W"
        />
      </span>
      <span class="mie6">
        <Avatar
          type="error"
          text="E"
        />
      </span>
    </div>
    <h2 class="mbe16">
      Groups
    </h2>
    <div class="mbe16">
      <AvatarGroup>
        <Avatar text="AB" />
        <Avatar text="CD" />
        <Avatar text="WX" />
        <Avatar text="YZ" />
      </AvatarGroup>
    </div>
    <div class="mbe16">
      <AvatarGroup>
        <Avatar img-url="https://joeschmoe.io/api/v1/random" />
        <Avatar
          type="success"
          text="Yes"
        />
        <Avatar img-url="https://joeschmoe.io/api/v1/random" />
        <Avatar
          type="info"
          text="We"
        />
        <Avatar img-url="https://joeschmoe.io/api/v1/random" />
        <Avatar
          type="success"
          text="Can"
        />
      </AvatarGroup>
    </div>

    <div class="mbs12 mbe16">
      <Alert>Default</Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert is-rounded>
        Rounded
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert is-border-all>
        Border all
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert is-border-left>
        Border left
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert type="success">
        Success
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert type="info">
        Info
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert type="warning">
        Warning
      </Alert>
    </div>
    <div class="mbs12 mbe16">
      <Alert type="error">
        Error
      </Alert>
    </div>
    <h2>Switch</h2>
    <div class="mbs12 mbe16">
      <Switch
        id="sw1"
        label="Switch small"
        size="small"
      />
      <Switch
        id="sw2"
        label="Switch default (medium)"
      />
      <Switch
        id="sw3"
        label="Switch large"
        size="large"
      />
      <Switch
        id="sw4"
        is-checked
        label="Switch large prechecked"
        size="large"
      />
      <Switch
        id="sw5"
        is-disabled
        label="Switch disabled"
        size="large"
      />
      <Switch
        id="sw6"
        is-bordered
        label="Switch bordered"
      />
      <Switch
        id="sw7"
        is-action
        is-checked
        label="Switch action prechecked"
        size="large"
      />
      <Switch
        id="sw8"
        is-action
        is-bordered
        label="Switch action bordered"
      />
    </div>
    <h2>Switch label on right</h2>
    <div>
      <Switch
        id="sw9"
        label-position="right"
        label="Switch label on right"
      />
    </div>
    <h2>Default Buttons</h2>
    <section>
      <Button is-bordered>
        Go
      </Button>
      <Button is-blank>
        Go
      </Button>
      <Button is-block>
        Go
      </Button>
      <Button is-rounded>
        Go
      </Button>
      <Button
        is-raised
        is-rounded
      >
        Go
      </Button>
      <Button
        is-bordered
        is-rounded
      >
        Go
      </Button>
    </section>
    <h2>Primary</h2>
    <section>
      <Button mode="primary">
        Go
      </Button>
      <Button
        mode="primary"
        :is-bordered="true"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-blank
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-block
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-rounded
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-raised
        is-rounded
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-bordered
        is-rounded
      >
        Go
      </Button>
    </section>
    <h2>Secondary</h2>
    <section>
      <Button mode="secondary">
        Go
      </Button>
      <Button
        mode="secondary"
        :is-bordered="true"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-blank
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-block
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-rounded
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-raised
        is-rounded
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-bordered
        is-rounded
      >
        Go
      </Button>
    </section>
    <h2>Misc</h2>
    <section>
      <Button :is-disabled="true">
        Go
      </Button>
      <Button
        mode="primary"
        is-disabled
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-disabled
      >
        Go
      </Button>
      <Button size="small">
        Go
      </Button>
      <Button size="large">
        Go
      </Button>
      <Button :is-skinned="false">
        No Skin
      </Button>
    </section>
    <section>
      <Card>
        <div style="padding: 24px">
          Default
        </div>
        <div style="padding: 24px">
          Card
        </div>
      </Card>
      <Card is-stacked>
        <div style="padding: 24px">
          Stacked
        </div>
        <div style="padding: 24px">
          Card
        </div>
      </Card>
      <Card
        is-stacked
        is-animated
      >
        <div style="padding: 24px">
          Stacked & Animated
        </div>
        <div style="padding: 24px">
          Card
        </div>
      </Card>
      <Card is-skinned>
        <div style="padding: 24px">
          Base Card
        </div>
        <div style="padding: 24px">
          No Skin
        </div>
      </Card>
      <Card css="addition-classes">
        <div style="padding: 24px">
          Custom CSS Class Overrides
        </div>
        <div style="padding: 24px">
          Inspect to see additional-classes
        </div>
      </Card>
    </section>
    <section>
      <ChoiceInput
        type="radio"
        legend-label="Radio"
        :options="[{ name: 'solo', value: 'stevie', label: 'Stevie Wonder'}, { name: 'solo', value: 'whitney', label: 'Whitney Houston' }, { name: 'solo', value: 'charlie', label: 'Charlie Wilson' }]"
      />

      <ChoiceInput
        type="checkbox"
        :options="[{ name: 'bands', value: 'bonjovi', label: 'Bon Jovi'}, { name: 'bands', value: 'stones', label: 'Rolling Stones' }, { name: 'bands', value: 'isleybros', label: 'Isley Brothers' }]"
        legend-label="Large"
        size="large"
        is-inline
      />
    </section>
    <section>
      <Input
        id="in1"
        size="small"
        placeholder="Enter name…"
        label="Small input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in2"
        placeholder="Enter name…"
        label="Default input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in3"
        size="large"
        placeholder="Enter name…"
        label="Large input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in4"
        is-inline
        placeholder="Enter name…"
        label="Inline input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in4b"
        is-rounded
        placeholder="Enter name…"
        label="Rounded input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in6"
        is-underlined
        placeholder="Enter name…"
        label="Underlined input"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in7"
        is-underlined
        is-underlined-with-background
        placeholder="Enter name…"
        label="Underlined with background"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in10"
        help-text="Some useful help text can go here"
        placeholder="Enter something…"
        label="Help text"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in9"
        is-invalid
        invalid-text="It's impossible to have a string that is cool enough for this field."
        placeholder="Enter a very cool string…"
        label="Cool factor"
        type="text"
      />
    </section>
    <section>
      <Input
        id="in8"
        has-left-addon
        has-right-addon
        label="Input with addons"
      >
      <template #addonLeft>
        <InputAddonItem addon-left>
          <Icon
            :size="18"
            type="success"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M21.03 5.72a.75.75 0 010 1.06l-11.5 11.5a.75.75 0 01-1.072-.012l-5.5-5.75a.75.75 0 111.084-1.036l4.97 5.195L19.97 5.72a.75.75 0 011.06 0z"
              />
            </svg>
          </Icon>
        </InputAddonItem>
      </template>
      <template #addonRight>
        <InputAddonItem addon-right>
          <Icon
            :size="18"
            type="info"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <path d="M13 7.5a1 1 0 11-2 0 1 1 0 012 0zm-3 3.75a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v4.25h.75a.75.75 0 010 1.5h-3a.75.75 0 010-1.5h.75V12h-.75a.75.75 0 01-.75-.75z" />
              <path
                fill-rule="evenodd"
                d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zM2.5 12a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z"
              />
            </svg>
          </Icon>
        </InputAddonItem>
      </template>
      </Input>
    </section>
    <section class="mbe24">
      <Input
        id="in11"
        label="Textarea"
        type="textarea"
      />
    </section>
    <section class="mbe24">
      <Input
        id="in12"
        label="Textarea small"
        type="textarea"
        size="small"
        :rows="10"
        :cols="5"
      />
    </section>
    <section class="mbe24">
      <Input
        id="in13"
        label="Textarea large"
        type="textarea"
        size="large"
        :rows="10"
        cols="5"
      />
    </section>
    <section>
      <h2>Default close</h2>
      <Close />
      <h2>Sizes</h2>
      <Close />
      <Close size="small" />
      <Close size="large" />
      <Close size="xlarge" />
    </section>
    <section>
      <h2>Tags</h2>
      <Tag>unknown</Tag>
      <Tag is-uppercase>
        UpperCasE
      </Tag>
      <Tag
        shape="round"
        is-uppercase
      >
        round
      </Tag>
      <Tag shape="pill">
        pill badge
      </Tag>
      <Tag
        shape="circle"
        type="error"
      >
        2
      </Tag>
      <Tag type="success">
        success
      </Tag>
      <Tag type="info">
        info
      </Tag>
      <Tag type="warning">
        warning
      </Tag>
    </section>
    <section>
      <Disclose
        is-open
        title="Roger Federer"
      >
        Roger Federer is a Swiss professional tennis player. He is ranked No. 11
        in the world by the Association of Tennis Professionals. He has won 20
        Grand Slam men&apos;s singles titles, an all-time record shared with
        Rafael Nadal and Novak Djokovic (Wikipedia).
      </Disclose>
      <Disclose title="Serena Williams">
        Serena Jameka Williams is an American professional tennis player. She
        has won 23 Grand Slam singles titles, the most by any player in the Open
        Era, and the second-most of all time behind Margaret Court. The
        Women&apos;s Tennis Association ranked her singles world No. 1 on eight
        separate occasions between 2002 and 2017.(Wikipedia).
      </Disclose>
      <Disclose title="Stefi Graf">
        Stefanie Maria Graf is a German former professional tennis player. She
        was ranked world No. 1 for a record 377 weeks and won 22 Grand Slam
        singles titles, which is the second-most since the introduction of the
        Open Era in 1968 and third-most of all-time behind Margaret Court and
        Serena Williams (Wikipedia).
      </Disclose>
      <Disclose title="Andre Agassi">
        Andre Kirk Agassi is an American former world No. 1 tennis player. He is
        an eight-time major champion and a 1996 Olympic gold medalist, as well
        as a runner-up in seven other Grand Slam tournaments. Agassi was the
        first man to win four Australian Open singles titles in the Open Era
        (Wikipedia).
      </Disclose>
    </section>

    <section>
      <h2 class="mbe12">
        Header defaults to space between
      </h2>
      <Header>
        <template #logoleft>
          <a href="https://web.dev/">web.dev</a>
        </template>
        <template #headernav>
          <HeaderNav>
            <HeaderNavItem>
              <a href="https://css-tricks.com/">CSS-Tricks</a>
            </HeaderNavItem>
            <HeaderNavItem>
              <a href="https://developer.mozilla.org/en-US/">MDN</a>
            </HeaderNavItem>
          </HeaderNav>
        </template>
        <template #logoright>
          <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
        </template>
      </Header>
      <h2 class="mbe12">
        Header content justify left
      </h2>
      <p class="mbe16">
        Pass in <code>isHeaderContentStart</code> and apply a global CSS class
        with <code>flex-grow: 0</code> on mobile (so it will stack as column),
        and <code>flex-grow: 1</code> at a breakpoint of your choosing to push
        other content over. Inspect <code>.header-flex-fill</code>
        in devtools to see an example.
      </p>
      <Header is-header-content-start>
        <template #logoleft>
          <a href="https://web.dev/">web.dev</a>
        </template>
        <template #headernav>
          <HeaderNav css="header-flex-fill">
            <HeaderNavItem>
              <a href="https://css-tricks.com/">CSS-Tricks</a>
            </HeaderNavItem>
            <HeaderNavItem>
              <a href="https://developer.mozilla.org/en-US/">MDN</a>
            </HeaderNavItem>
          </HeaderNav>
        </template>
        <template #logoright>
          <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
        </template>
      </Header>
      <h2 class="mbe12">
        Header content justify right
      </h2>
      <p class="mbe16">
        Pass in <code>isHeaderContentEnd</code> and apply
        <code>flex-fill</code> to the <code>logoleft</code> content so grows
        (pushes content over).
      </p>
      <Header is-header-content-end>
        <template #logoleft>
          <a
            class="flex-fill"
            href="https://web.dev/"
          >web.dev</a>
        </template>
        <template #headernav>
          <HeaderNav css="header-mbe16">
            <HeaderNavItem>
              <a href="https://css-tricks.com/">CSS-Tricks</a>
            </HeaderNavItem>
            <HeaderNavItem>
              <a href="https://developer.mozilla.org/en-US/">MDN</a>
            </HeaderNavItem>
          </HeaderNav>
        </template>
        <template #logoright>
          <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
        </template>
      </Header>
    </section>
  </div>
</template>
<style>
/* these styles are purely demonstration related styles only */
body {
  width: 600px;
  margin: 40px auto;
}
h1,
h3 {
  display: block;
  margin-top: 2rem;
  margin-bottom: 1rem;
}
button:not(:first-child) {
  margin-left: 0.25rem;
}
section {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  margin-bottom: 40px;
}

details {
  width: 100%;
}

/**
 * Header Examples
 */
.header-flex-fill {
  flex-grow: 0;
}
.header-flex-fill {
  margin-inline-start: 0;
}

.header-mbe16 {
  margin-inline-end: 0;
}

@media (min-width: 970px) {
  .header-flex-fill {
    flex-grow: 1;
    margin-inline-start: var(--fluid-16);
  }

  .header-mbe16 {
    margin-inline-end: var(--fluid-16);
  }
}
</style>

// agnostic-angular/apps/examples/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
@Component({
  selector: 'ag-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  // We're using some globals in example so don't apply encapsulation
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  title = 'examples';
}

<main>
  <h1>AgnosticUI Angular (Beta) — Kitchen Sink</h1>
  <section>
    <h2>Alerts</h2>
    <div class="mbe16">
      <ag-alert>This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isRounded]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderAll]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isRounded]="true"
                [isBorderAll]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="success">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="info">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="warning">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="error">This is an alert</ag-alert>
    </div>
  </section>
  <section>
    <h2>Icons</h2>
    <p class="mbs24 mbe40">
      Test this in Safari! We need to ensure that the component is actually applying a
      <code>width</code> to the SVG itself else Safari the icon won't be visible
    </p>
    <div class="mie8">
      <ag-icon>
        <svg xmlns="http://www.w3.org/2000/svg"
             enable-background="new 0 0 24 24"
             viewBox="0 0 24 24">
          <g>
            <rect fill="none"
                  height="24"
                  width="24" />
          </g>
          <g>
            <path d="M19,9.3V4h-3v2.6L12,3L2,12h2v8h6v-6h2v6h6v-8h2L19,9.3z M17,18h-2v-6H9v6H7v-7.81l5-4.5l5,4.5V18z" />
            <path d="M10,10h4c0-1.1-0.9-2-2-2S10,8.9,10,10z" />
          </g>
        </svg>
      </ag-icon>
      <ag-icon [size]="64"
               type="info">
        <svg xmlns="http://www.w3.org/2000/svg"
             enable-background="new 0 0 24 24"
             viewBox="0 0 24 24">
          <g>
            <rect fill="none"
                  height="24"
                  width="24" />
          </g>
          <g>
            <path d="M19,9.3V4h-3v2.6L12,3L2,12h2v8h6v-6h2v6h6v-8h2L19,9.3z M17,18h-2v-6H9v6H7v-7.81l5-4.5l5,4.5V18z" />
            <path d="M10,10h4c0-1.1-0.9-2-2-2S10,8.9,10,10z" />
          </g>
        </svg>
      </ag-icon>
    </div>
  </section>
  <section>
    <h2>Avatars</h2>
    <ag-avatar text="RL"
               size="small"></ag-avatar>
    <ag-avatar text="AB"></ag-avatar>
    <ag-avatar text="RL"
               size="large"></ag-avatar>
    <ag-avatar text="RL"
               size="xlarge"></ag-avatar>
    <ag-avatar text="Sq"
               type="error"
               [isSquare]="true"></ag-avatar>
  </section>
  <h2>Default Buttons</h2>
  <section>
    <ag-button>Go</ag-button>
    <ag-button [isBordered]="true">Go</ag-button>
    <ag-button [isBlank]="true">Go</ag-button>
    <ag-button [isBlock]="true">Go</ag-button>
    <ag-button [isRounded]="true">Go</ag-button>
    <ag-button [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Primary</h2>
  <section>
    <ag-button mode="primary">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Secondary</h2>
  <section>
    <ag-button mode="secondary">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Misc</h2>
  <section>
    <ag-button [isDisabled]="true">Go</ag-button>
    <ag-button mode="primary"
               [isDisabled]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isDisabled]="true">Go</ag-button>
    <ag-button size="small">Go</ag-button>
    <ag-button size="large">Go</ag-button>
    <ag-button [isSkinned]="false">No Skin</ag-button>
  </section>

  <section>
    <h2>Button Groups</h2>
    <ag-button-group ariaLabel="A useful ariaLabel">
      <div class="btn-first-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 1</ag-button>
      </div>
      <ag-button mode="primary"
                 [isBordered]="true">Button 2</ag-button>
      <ag-button mode="primary"
                 [isBordered]="true">Button 3</ag-button>
      <div class="btn-last-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 4</ag-button>
      </div>
    </ag-button-group>
  </section>
  <section>
    <h2>Cards</h2>
    <ag-card>
      <div style="padding: 24px;">Default</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true">
      <div style="padding: 24px;">Stacked</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true"
             [isAnimated]="true">
      <div style="padding: 24px;">Stacked & Animated</div>
      <div style="padding: 24px;">This card will animate upwards by default.</div>
    </ag-card>
    <ag-card [isStacked]="true"
             [isAnimated]="true"
             css="animation-override">
      <div style="padding: 24px;">Stacked & Animated</div>
      <div style="padding: 24px;">We've overriden the animation direction. Inspect to see .animation-override</div>
    </ag-card>
    <ag-card [isSkinned]="false">
      <div style="padding: 24px;">Base Card</div>
      <div style="padding: 24px;">No Skin</div>
    </ag-card>
    <ag-card css="additional-classes">
      <div style="padding: 24px;">Custom CSS Class Overrides</div>
      <div style="padding: 24px;">Inspect to see additional-classes</div>
    </ag-card>
  </section>
  <section>
    <h2>Breadcrumbs</h2>
    <ag-breadcrumb
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb type="bullet"
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb type="arrow"
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb [routes]="[{ label: 'A single route will look *linkless*' }]"></ag-breadcrumb>
    <ag-breadcrumb [routes]="[{label: 'First', url: '#foo'}, { label: 'Second', url: '#bar' }]"></ag-breadcrumb>
  </section>
  <section>
    <h2>Choice Inputs</h2>
    <ag-choice-input type="radio"
                     [options]="[{ name: 'solo', value: 'stevie', label: 'Stevie Wonder'}, { name: 'solo', value: 'whitney', label: 'Whitney Houston' }, { name: 'solo', value: 'charlie', label: 'Charlie Wilson' }]">
    </ag-choice-input>

    <ag-choice-input type="checkbox"
                     [options]="[{ name: 'bands', value: 'bonjovi', label: 'Bon Jovi'}, { name: 'bands', value: 'stones', label: 'Rolling Stones' }, { name: 'bands', value: 'isleybros', label: 'Isley Brothers' }]"
                     legendLabel="Large"
                     size="large"
                     [isInline]="true"></ag-choice-input>
  </section>
  <section>
    <h2>Close button</h2>
    <ag-close></ag-close>
    <ag-close size="small"></ag-close>
    <ag-close size="large"></ag-close>
    <ag-close size="xlarge"></ag-close>
  </section>
  <section>
    <div class="mbe48">
      <h2>Multiple Disclose</h2>
      <p class="mbs16 mbe24">Multiple disclose elements can be stacked to achieve a
        progressively disclosed pattern that resembles an Accordion pattern. Further,
        individual disclosed elements may be open by default if we supply the
        <code>[isOpen]="true"</code> prop as we do in the first disclose element below:
      </p>
      <ag-disclose [isOpen]="true"
                   title="Roger Federer">
        Roger Federer is a Swiss professional tennis player. He is ranked No. 11 in the world by the Association of
        Tennis
        Professionals. He has won 20 Grand Slam men's singles titles, an all-time record shared with Rafael Nadal and
        Novak
        Djokovic (Wikipedia).
      </ag-disclose>
      <ag-disclose title="Serena Williams">
        Serena Jameka Williams is an American professional tennis player. She has won 23 Grand Slam singles titles,
        the
        most
        by any player in the Open Era, and the second-most of all time behind Margaret Court. The Women's Tennis
        Association
        ranked her singles world No. 1 on eight separate occasions between 2002 and 2017.(Wikipedia).
      </ag-disclose>
      <ag-disclose title="Stefi Graf">
        Stefanie Maria Graf is a German former professional tennis player. She was ranked world No. 1 for a record 377
        weeks
        and won 22 Grand Slam singles titles, which is the second-most since the introduction of the Open Era in 1968
        and
        third-most of all-time behind Margaret Court and Serena Williams (Wikipedia).
      </ag-disclose>
      <ag-disclose title="Andre Agassi">
        Andre Kirk Agassi is an American former world No. 1 tennis player. He is an eight-time major champion and a
        1996
        Olympic gold medalist, as well as a runner-up in seven other Grand Slam tournaments. Agassi was the first man
        to
        win
        four Australian Open singles titles in the Open Era (Wikipedia).
      </ag-disclose>
    </div>
  </section>

  <section>
    <h2>HTML5 Compatible Inputs</h2>
    <ag-input id="in1"
              size="small"
              placeholder="Enter name…"
              label="Small input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in2"
              placeholder="Enter name…"
              label="Default input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in3"
              size="large"
              placeholder="Enter name…"
              label="Large input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in4"
              [isRounded]="true"
              placeholder="Enter name…"
              label="Rounded input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in5"
              [isUnderlined]="true"
              placeholder="Enter name…"
              label="Underlined input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in6"
              [isUnderlined]="true"
              [isUnderlinedWithBackground]="true"
              placeholder="Enter name…"
              label="Underlined with background"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in7"
              helpText="Some useful help text can go here"
              placeholder="Enter name…"
              label="Help text"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in8"
              [isInvalid]="true"
              invalidText="It's impossible to have a string that is cool enough for this field."
              placeholder="Enter a very cool string…"
              label="Cool factor"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in9"
              [hasLeftAddon]="true"
              [hasRightAddon]="true"
              label="Input with addons"
              type="text">
      <div addOnLeft
           class="addOnLeft">
        <ag-icon [size]="18"
                 type="error">
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="currentColor">
            <path fill-rule="evenodd"
                  d="M21.03 5.72a.75.75 0 010 1.06l-11.5 11.5a.75.75 0 01-1.072-.012l-5.5-5.75a.75.75 0 111.084-1.036l4.97 5.195L19.97 5.72a.75.75 0 011.06 0z" />
          </svg>
        </ag-icon>
      </div>
      <div addOnRight
           class="addOnRight">
        <ag-icon [size]="18"
                 type="info">
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="currentColor">
            <path
                  d="M13 7.5a1 1 0 11-2 0 1 1 0 012 0zm-3 3.75a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v4.25h.75a.75.75 0 010 1.5h-3a.75.75 0 010-1.5h.75V12h-.75a.75.75 0 01-.75-.75z" />
            <path fill-rule="evenodd"
                  d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zM2.5 12a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z" />
          </svg>
        </ag-icon>
      </div>
    </ag-input>
  </section>
  <section>
    <ag-input id="in10"
              placeholder="Enter something…"
              label="Textarea"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in11"
              placeholder="Enter something…"
              label="Textarea small"
              size="small"
              [rows]="10"
              [cols]="5"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in12"
              placeholder="Enter something…"
              label="Textarea large"
              size="large"
              [rows]="10"
              [cols]="5"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in13"
              placeholder="Enter something…"
              label="Textarea"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <h2>Tabs</h2>
    <ag-tabs>
      <ag-tab-panel panelId="panel1"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel2"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <ag-tabs [isVerticalOrientation]="true">
      <ag-tab-panel panelId="panel3"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel4"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <ag-tabs size="xlarge"
             [disabledOptions]="['Tab 2', 'Tab 4']">
      <ag-tab-panel panelId="panel11"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel12"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel13"
                    tabButtonTitle="Tab 3">
        Tab 3 content
      </ag-tab-panel>
      <ag-tab-panel panelId="panel14"
                    tabButtonTitle="Tab 4">
        Tab 4 content
      </ag-tab-panel>
      <ag-tab-panel panelId="panel15"
                    tabButtonTitle="Tab 5">
        Tab 5 content
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <h2>Tags</h2>
    <ag-tag>unknown</ag-tag>
    <ag-tag shape="round">rounded</ag-tag>
    <ag-tag shape="pill">badge</ag-tag>
    <ag-tag type="info"
            [isUppercase]="true">info</ag-tag>
    <ag-tag type="success"
            [isUppercase]="true">success</ag-tag>
    <ag-tag type="warning"
            [isUppercase]="true">warning</ag-tag>
    <ag-tag type="error"
            [isUppercase]="true">error</ag-tag>
    <ag-tag type="error"
            shape="circle">2</ag-tag>
  </section>
  <section>
    <h2>Select</h2>
    <ag-select uniqueId="sel1"
               name="select1"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' },
      { value: 'serena', label: 'Serena Williams' },
      { value: 'mac', label: 'John McEnroe' },
      { value: 'borg', label: 'Bjorn Borg' },
      { value: 'althea', label: 'Althea Gibson' },
      { value: 'roger', label: 'Roger Federer' },
      ]"></ag-select>
  </section>
  <section>
    <h2>Select first option custom label</h2>
    <ag-select uniqueId="sel2"
               name="select2"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' },
      { value: 'serena', label: 'Serena Williams' },
      { value: 'mac', label: 'John McEnroe' },
      { value: 'borg', label: 'Bjorn Borg' },
      { value: 'althea', label: 'Althea Gibson' },
      { value: 'roger', label: 'Roger Federer' },
      ]"></ag-select>
  </section>
  <section>
    <h2>Select disabled</h2>
    <ag-select uniqueId="sel3"
               name="select3"
               [isDisabled]="true"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' }
      ]"></ag-select>
  </section>
  <section>
    <h2>Select small</h2>
    <ag-select uniqueId="sel4"
               name="select4"
               size="small"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]"></ag-select>
  </section>
  <section>
    <h2>Select large</h2>
    <ag-select uniqueId="sel5"
               name="select5"
               size="large"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]"></ag-select>
  </section>
  <section>
    <h2>Select multiple</h2>
    <ag-select uniqueId="sel6"
               name="select6"
               size="large"
               [isMultiple]="true"
               [multipleSize]="4"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]">
    </ag-select>
  </section>
  <section>
    <h2>Switch</h2>
    <ag-switch label="Switch small"
               size="small"></ag-switch>
    <ag-switch label="Switch default (medium)"></ag-switch>
    <ag-switch label="Switch large"
               size="large"></ag-switch>
    <ag-switch [isChecked]="true"
               label="Switch prechecked"></ag-switch>
    <ag-switch [isDisabled]="true"
               label="Switch disabled"></ag-switch>
    <ag-switch [isBordered]="true"
               label="Switch bordered"></ag-switch>
    <ag-switch [isAction]="true"
               [isChecked]="true"
               label="Switch action prechecked"></ag-switch>
    <ag-switch [isAction]="true"
               [isBordered]="true"
               label="Switch action bordered"></ag-switch>
    <h2 class="mbs24 mbe24">Switch label on right</h2>
    <ag-switch label="Small label on right"
               size="small"
               labelPosition="right"></ag-switch>
  </section>
  <section>
    <h2>Headers</h2>
    <ag-header>
      <a href="https://web.dev/">web.dev</a>
      <ag-header-nav>
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item class="mis12 mie16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
    <ag-header [isHeaderContentStart]="true">
      <a href="https://web.dev/">web.dev</a>
      <ag-header-nav class="header-flex-fill">
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item class="mis12 mie16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
    <ag-header [isHeaderContentEnd]="true">
      <a class="flex-fill"
         href="https://web.dev/">web.dev</a>
      <ag-header-nav>
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item css="header-mbe16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
  </section>
</main>
