// agnostic-svelte/examples/src/App.svelte
<script>
	import "../node_modules/agnostic-svelte/dist/common.min.css";
	import {
    Alert,
    Avatar,
    AvatarGroup,
    Breadcrumb,
		Button,
		Card,
		ChoiceInput,
    Close,
    Disclose,
		Header,
		HeaderNav,
		HeaderNavItem,
		Input,
    InputAddonItem,
		Icon,
		Progress,
		Select,
		Switch,
    Tag,
    Tabs,
	} from 'agnostic-svelte';

  import Tab1 from "../../src/stories/TabPanel1.svelte";
  import Tab2 from "../../src/stories/TabPanel2.svelte";
  import Tab3 from "../../src/stories/TabPanel3.svelte";
  import Tab4 from "../../src/stories/TabPanel3.svelte";

	const opts = [
		{
			name: "frequency",
			value: "daily",
			label: "Daily",
		},
		{
			name: "frequency",
			value: "weekly",
			label: "Weekly",
		},
		{
			name: "frequency",
			value: "monthly",
			label: "Monthly",
		},
	];
  let alertMessage = 'Alerts should be used for timely information.';

  const trailOfTennisRoutes = [
    {
      label: "Tennis",
      url: "#tennis",
    },
    {
      label: "Superstars",
      url: "#tennis-superstars",
    },
    {
      label: "Serena Williams",
      url: "#tennis-superstars-serena",
    },
  ];

  const tennisOptions = [
    { value: 'andre', label: 'Andre Agassi' },
    { value: 'serena', label: 'Serena Williams' },
    { value: 'mac', label: 'John McEnroe' },
    { value: 'borg', label: 'Bjorn Borg' },
    { value: 'althea', label: 'Althea Gibson' },
    { value: 'roger', label: 'Roger Federer' },
  ];
</script>
<style>
  
	.container {
		margin: 2rem 5rem;
	}
	.component-container {
		width: 100%;
		padding: 1rem 2rem;
	}

</style>

<div class="container">
  

  <div class="mbe32"></div>

	<Header>
		<div slot="logoleft">logo left</div>
		<HeaderNav css="nav-overrides">
			<HeaderNavItem><a href="#home">Home</a></HeaderNavItem>
			<HeaderNavItem><a href="#products">Products</a></HeaderNavItem>
			<HeaderNavItem><a href="#services">Services</a></HeaderNavItem>
			<HeaderNavItem><a href="#about">About</a></HeaderNavItem>
		</HeaderNav>
		<div slot="logoright">logo right</div>
	</Header>
</div>
<div class="container">
  <h3 class="mbs40 mbe12">Header content justify left</h3>
  <p class="mbe24">Pass in <code>isHeaderContentStart</code> and apply a global CSS class with
    <code>flex-grow: 0</code> on mobile (so it will stack as column), and <code>flex-grow: 1</code>
    at a breakpoint of your choosing to push other content over. Inspect <code>.header-flex-fill</code>
    in devtools to see an example.
  </p>	
  <Header isHeaderContentStart="{true}">
    <div slot="logoleft"><a href="https://www.w3.org/">w3</a></div>
    <HeaderNav css="header-flex-fill">
      <HeaderNavItem><a href="https://web.dev/">web.dev</a></HeaderNavItem>
      <HeaderNavItem>
        <a href="https://css-tricks.com/">CSS-Tricks</a>
      </HeaderNavItem>
      <HeaderNavItem>
        <a href="https://developer.mozilla.org/en-US/">MDN</a>
      </HeaderNavItem>
      <HeaderNavItem>
        <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
      </HeaderNavItem>
    </HeaderNav>
    <div slot="logoright">
      <a href="https://www.w3.org/TR/wai-aria-practices-1.1/">wai-aria</a>
    </div>
  </Header>
</div>
<div class="container">
  <h3 class="mbs40 mbe12">Header content justify right</h3>
  <p class="mbe24">Pass in <code>isHeaderContentEnd</code> and apply
    <code>flex-fill</code> to the <code>logoleft</code> content so grows (pushes content over).
  </p>
  <Header isHeaderContentEnd="{true}">
    <a class="flex-fill" href="https://web.dev/">web.dev</a>
    <HeaderNav css="header-mbe16">
      <HeaderNavItem><a href="https://web.dev/">web.dev</a></HeaderNavItem>
      <HeaderNavItem>
        <a href="https://css-tricks.com/">CSS-Tricks</a>
      </HeaderNavItem>
      <HeaderNavItem>
        <a href="https://developer.mozilla.org/en-US/">MDN</a>
      </HeaderNavItem>
      <HeaderNavItem>
        <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
      </HeaderNavItem>
    </HeaderNav>
    <div slot="logoright">
      <a href="https://www.w3.org/TR/wai-aria-practices-1.1/">wai-aria</a>
    </div>
  </Header>
</div>
<div class="container">
  <h2 class="mbs40 mbe24">Breadcrumbs</h2>
  <div class="mbs24 mbe16">
    <Breadcrumb routes={ trailOfTennisRoutes } />
    <Breadcrumb
      type="slash"
      routes={ trailOfTennisRoutes }
    />
    <Breadcrumb
      type="bullet"
      routes={ trailOfTennisRoutes }
    />
    <Breadcrumb
      type="arrow"
      routes={ trailOfTennisRoutes }
    />
    <Breadcrumb routes={[{ label: 'A single route will look *linkless*' }]} />
    <Breadcrumb routes={[{label: 'First', url: '#foo'}, { label: 'Second', url: '#bar' }]} />
  </div>
</div>

<div class="container">
  <h3 class="mbs40 mbe24">Tabs</h3>
  <Tabs size="large" tabs={[
    {
      title: "Tab 1",
      ariaControls: "panel-1",
      tabPanelComponent: Tab1,
    },
    {
      title: "Tab 2",
      ariaControls: "panel-2",
      tabPanelComponent: Tab2,
    },
    {
      title: "Tab 3",
      ariaControls: "panel-3",
      tabPanelComponent: Tab3,
    },
    {
      title: "Tab 4",
      ariaControls: "panel-4",
      tabPanelComponent: Tab4,
    },
  ]}></Tabs>
</div>
<div class="container">
  <section class="mbe24">
    <h3>Tags</h3>
    <Tag>unknown</Tag>
    <Tag shape="round">Rounded</Tag>
    <Tag shape="pill">Badge</Tag>
    <Tag type="success" isUppercase="true">success</Tag>
    <Tag type="info" isUppercase="true">info</Tag>
    <Tag type="warning" isUppercase="true">warning</Tag>
    <Tag type="error" isUppercase="true">error</Tag>
    <Tag type="error" shape="circle">2</Tag>
  </section>
  <section class="mbe24">
    <h3>Default close</h3>
    <Close />
    <h3 class="mbs12">Sizes</h3>
    <Close />
    <Close size="small" />
    <Close size="large" />
    <Close size="xlarge" />
  </section>
  <section class="mbe24">
    <h3>Icons</h3>
    <p class="mbs24 mbe40">
      Test this in Safari! We need to ensure that the component is actually applying a
      <code>width</code> to the SVG itself else Safari the icon won't be visible
    </p>
    <div class="mie8">
      <Icon>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          enable-background="new 0 0 24 24"
          viewBox="0 0 24 24"
        >
          <g>
            <rect
              fill="none"
              height="24"
              width="24"
            />
          </g>
          <g>
            <path d="M19,9.3V4h-3v2.6L12,3L2,12h3v8h6v-6h2v6h6v-8h3L19,9.3z M17,18h-2v-6H9v6H7v-7.81l5-4.5l5,4.5V18z" />
            <path d="M10,10h4c0-1.1-0.9-2-2-2S10,8.9,10,10z" />
          </g>
        </svg>
      </Icon>
    </div>
    <div class="mie8">
      <Icon>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M11.03 2.59a1.5 1.5 0 011.94 0l7.5 6.363a1.5 1.5 0 01.53 1.144V19.5a1.5 1.5 0 01-1.5 1.5h-5.75a.75.75 0 01-.75-.75V14h-2v6.25a.75.75 0 01-.75.75H4.5A1.5 1.5 0 013 19.5v-9.403c0-.44.194-.859.53-1.144l7.5-6.363zM12 3.734l-7.5 6.363V19.5h5v-6.25a.75.75 0 01.75-.75h3.5a.75.75 0 01.75.75v6.25h5v-9.403L12 3.734z"
          />
        </svg>
      </Icon>
    </div>
    <div class="mie8">
      <Icon>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 576 512"
        >
          <path d="M280.37 148.26L96 300.11V464a16 16 0 0 0 16 16l112.06-.29a16 16 0 0 0 15.92-16V368a16 16 0 0 1 16-16h64a16 16 0 0 1 16 16v95.64a16 16 0 0 0 16 16.05L464 480a16 16 0 0 0 16-16V300L295.67 148.26a12.19 12.19 0 0 0-15.3 0zM571.6 251.47L488 182.56V44.05a12 12 0 0 0-12-12h-56a12 12 0 0 0-12 12v72.61L318.47 43a48 48 0 0 0-61 0L4.34 251.47a12 12 0 0 0-1.6 16.9l25.5 31A12 12 0 0 0 45.15 301l235.22-193.74a12.19 12.19 0 0 1 15.3 0L530.9 301a12 12 0 0 0 16.9-1.6l25.5-31a12 12 0 0 0-1.7-16.93z" />
        </svg>
      </Icon>
    </div>
  </section>

  <section class="mbe24">
    <h2>Disclose</h2> 
    <Disclose
      is-open
      title="Roger Federer"
    >
      Roger Federer is a Swiss professional tennis player. He is ranked No. 11 in the world by the
      Association of Tennis Professionals. He has won 20 Grand Slam men&apos;s singles titles, an
      all-time record shared with Rafael Nadal and Novak Djokovic (Wikipedia).
    </Disclose>
    <Disclose title="Serena Williams">
      Serena Jameka Williams is an American professional tennis player. She has won 23 Grand Slam
      singles titles, the most by any player in the Open Era, and the second-most of all time behind
      Margaret Court. The Women&apos;s Tennis Association ranked her singles world No. 1 on eight
      separate occasions between 2002 and 2017.(Wikipedia).
    </Disclose>
    <Disclose title="Stefi Graf">
      Stefanie Maria Graf is a German former professional tennis player. She was ranked world No. 1
      for a record 377 weeks and won 22 Grand Slam singles titles, which is the second-most since
      the introduction of the Open Era in 1968 and third-most of all-time behind Margaret Court and
      Serena Williams (Wikipedia).
    </Disclose>
    <Disclose title="Andre Agassi">
      Andre Kirk Agassi is an American former world No. 1 tennis player. He is an eight-time major
      champion and a 1996 Olympic gold medalist, as well as a runner-up in seven other Grand Slam
      tournaments. Agassi was the first man to win four Australian Open singles titles in the Open
      Era (Wikipedia).
    </Disclose>
  </section>
  <section class="mbe24">
    <h2 class="mbe24">Disclose with background</h2> 
    <Disclose isBackground title="Roger Federer">
      Roger Federer is a Swiss professional tennis player. He is ranked No. 11 in the world by the
      Association of Tennis Professionals. He has won 20 Grand Slam men&apos;s singles titles, an
      all-time record shared with Rafael Nadal and Novak Djokovic (Wikipedia).
    </Disclose>
    <Disclose isBackground title="Serena Williams">
      Serena Jameka Williams is an American professional tennis player. She has won 23 Grand Slam
      singles titles, the most by any player in the Open Era, and the second-most of all time behind
      Margaret Court. The Women&apos;s Tennis Association ranked her singles world No. 1 on eight
      separate occasions between 2002 and 2017.(Wikipedia).
    </Disclose>
    <Disclose isBackground title="Stefi Graf">
      Stefanie Maria Graf is a German former professional tennis player. She was ranked world No. 1
      for a record 377 weeks and won 22 Grand Slam singles titles, which is the second-most since
      the introduction of the Open Era in 1968 and third-most of all-time behind Margaret Court and
      Serena Williams (Wikipedia).
    </Disclose>
    <Disclose isBackground title="Andre Agassi">
      Andre Kirk Agassi is an American former world No. 1 tennis player. He is an eight-time major
      champion and a 1996 Olympic gold medalist, as well as a runner-up in seven other Grand Slam
      tournaments. Agassi was the first man to win four Australian Open singles titles in the Open
      Era (Wikipedia).
    </Disclose>
  </section>

  <section class="mbs40 mbe32">
    <h2>Alerts</h2>
    <div class="mbe16">
      <Alert>{ alertMessage }</Alert>
    </div>
    <div class="mbe16">
      <Alert isRounded>{ alertMessage }</Alert>
    </div>
    <div class="mbe16">
      <Alert isBorderAll>Border all</Alert>
    </div>
    <div class="mbe16">
      <Alert isBorderLeft>Border left</Alert>
    </div>
    <div class="mbe16">
      <Alert type="success">{ alertMessage }</Alert>
    </div>
    <div class="mbe16">
      <Alert type="info">{ alertMessage }</Alert>
    </div>
    <div class="mbe16">
      <Alert type="warning">{ alertMessage }</Alert>
    </div>
    <div class="mbe16">
      <Alert type="error">{ alertMessage }</Alert>
    </div>
  </section>
  <Card>
    <section class="component-container">
      <h2>Buttons</h2>
      <Button>Go</Button>
      <Button mode="primary">Go</Button>
      <Button mode="primary" isRounded>Go</Button>
      <Button mode="primary" isRounded isBordered>Go</Button>
      <Button size="large">Go</Button>
      <Button isBlock>Go</Button>
      <Button isCircle>Go</Button>
      <Button isRaised>Go</Button>
      <Button mode="primary" isRaised>Go</Button>
      <Button mode="secondary" isRaised>Go</Button>
      <Button isBlank>Blank button</Button>
      <Button isDisabled>Disabled</Button>
    </section>
  </Card>
  <Card>
    <section class="component-container">
      <h2>Input</h2>
      <Input uniqueId="1" label="Default input" />
      <Input uniqueId="2" isRounded label="Rounded input" />
      <Input uniqueId="3" isUnderlined label="Underlined input" />
      <Input uniqueId="4" isUnderlined isUnderlinedWithBackground label="Underlined with background" />
      <Input uniqueId="5" isInline label="Inline input" />
      <Input uniqueId="6" size="small" label="Small input" />
      <Input uniqueId="7" size="large" label="Large input" />
      <Input uniqueId="8" helpText="Some useful help hint…" label="Large input" />
      <Input uniqueId="9" isInvalid invalidText="Some error hint…" label="Large input" />
      <Input
        hasLeftAddon="{true}"
        hasRightAddon="{true}"
        id="10"
        label="Input with addons"
      >
        <div slot="addonLeft">
          <InputAddonItem addonLeft="{true}"><span>L</span></InputAddonItem>
        </div>
        <div slot="addonRight">
          <InputAddonItem addonRight="{true}"><span>R</span></InputAddonItem>
        </div>
      </Input>
    </section>
  </Card>
  <Card>
      <section class="component-container">
        <h2>Checkbox</h2>
        <ChoiceInput type="checkbox" isInline options={opts} />
        <h2>Radio</h2>
        <ChoiceInput type="radio" isInline options={opts} />
      </section>
  </Card>
  <Card>
      <section class="component-container">
        <h2>Switch</h2>
        <Switch id="switch-1" label="Switch default" />
        <Switch id="switch-small" size="small" label="Switch small" />
        <Switch id="switch-lg" size="large" label="Switch large" />
        <Switch
          id="switch-prechecked"
          isChecked={true}
          size="large"
          label="Prechecked"
        />
        <Switch id="switch-disabled" isDisabled={true} label="Disabled" />
        <Switch id="switch-bordered" isBordered={true} label="Bordered" />
        <Switch id="switch-action" isAction={true} label="Action" />
        <Switch id="switch-action-bordered"
          isAction={true}
          isBordered={true}
          label="Action bordered"
        />
        <Switch
          id="switch-right"
          labelPosition="right"
          label="Label on right"
        />
        <Switch id="switch-right-bordered"
          isBordered={true}
          labelPosition="right"
          label="Label on right bordered"
        />
      </section>
  </Card>
  <Card>
    <section class="component-container">
      <h2>Progress</h2>
      <Progress value="30" max="100" />
    </section>
  </Card>
  <Card>
    <section class="component-container">
      <h2>Avatars</h2>
      <div class="mbs16 mbe24">
        <Avatar class="mie12" text="RL" />
        <Avatar class="mie12" type="success" text="RL" />
        <Avatar class="mie12" type="info" text="RL" />
        <Avatar class="mie12" type="warning" text="RL" />
        <Avatar class="mie12" type="error" text="RL" />
        <Avatar class="mie12" size="small" text="S" />
        <Avatar class="mie12" size="large" text="L" />
        <Avatar class="mie12" size="xlarge" text="XL" />
        <Avatar class="mie12" isSquare size="large" text="SQ" />
      </div>
      <div class="mbe24">
        <Avatar class="mie12">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fill-rule="evenodd"
              d="M12 2.5a5.5 5.5 0 00-3.096 10.047 9.005 9.005 0 00-5.9 8.18.75.75 0 001.5.045 7.5 7.5 0 0114.993 0 .75.75 0 101.499-.044 9.005 9.005 0 00-5.9-8.181A5.5 5.5 0 0012 2.5zM8 8a4 4 0 118 0 4 4 0 01-8 0z"
            />
          </svg>
        </Avatar>

        <Avatar class="mie12" imgUrl="https://joeschmoe.io/api/v1/random" />
        <Avatar
          class="mie12" 
          isTransparent
          imgUrl="https://joeschmoe.io/api/v1/random"
        />
        <Avatar
          class="mie12" 
          type="success"
          imgUrl="https://joeschmoe.io/api/v1/random"
        />
        <Avatar
          class="mie12" 
          type="info"
          imgUrl="https://joeschmoe.io/api/v1/random"
        />
      </div>
      <div>
        <AvatarGroup>
          <Avatar type="success" text="SC" />
          <Avatar type="info" text="IN" />
          <Avatar type="warning" text="WN" />
          <Avatar type="error" text="ER" />
        </AvatarGroup>
      </div>
    </section>
    <section class="component-container">
      <h2>Select default</h2>
      <Select
        uniqueId="sel1"
        name="select1"
        labelCopy="Select the best tennis player of all time"
        options={tennisOptions}
      />
      <h2>Select default option customized</h2>
      <Select
        uniqueId="sel2"
        name="select2"
        labelCopy="Select the best tennis player of all time"
        defaultOptionLabel="Select your favorite tennis player of all-time"
        options={tennisOptions}
      />
      <h2>Select disabled</h2>
      <Select
        uniqueId="sel3"
        name="select3"
        isDisabled={true}
        labelCopy="Select the best tennis player of all time"
        defaultOptionLabel="Select your favorite tennis player of all-time"
        options={tennisOptions}
      />
      <h2>Select small</h2>
      <Select
        uniqueId="sel3"
        name="select3"
        size="small"
        labelCopy="Select the best tennis player of all time"
        defaultOptionLabel="Select your favorite tennis player of all-time"
        options={tennisOptions}
      />
      <h2>Select large</h2>
      <Select
        uniqueId="sel3"
        name="select3"
        size="large"
        labelCopy="Select the best tennis player of all time"
        defaultOptionLabel="Select your favorite tennis player of all-time"
        options={tennisOptions}
      />
    </section>
  </Card>

</div>

// agnostic-angular/apps/examples/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
@Component({
  selector: 'ag-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  // We're using some globals in example so don't apply encapsulation
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  title = 'examples';
}

<main>
  <h1>AgnosticUI Angular (Beta) — Kitchen Sink</h1>
  <section>
    <h2>Alerts</h2>
    <div class="mbe16">
      <ag-alert>This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isRounded]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderAll]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isRounded]="true"
                [isBorderAll]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="success">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="info">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="warning">This is an alert</ag-alert>
    </div>
    <div class="mbe16">
      <ag-alert [isBorderLeft]="true"
                type="error">This is an alert</ag-alert>
    </div>
  </section>
  <section>
    <h2>Icons</h2>
    <p class="mbs24 mbe40">
      Test this in Safari! We need to ensure that the component is actually applying a
      <code>width</code> to the SVG itself else Safari the icon won't be visible
    </p>
    <div class="mie8">
      <ag-icon>
        <svg xmlns="http://www.w3.org/2000/svg"
             enable-background="new 0 0 24 24"
             viewBox="0 0 24 24">
          <g>
            <rect fill="none"
                  height="24"
                  width="24" />
          </g>
          <g>
            <path d="M19,9.3V4h-3v2.6L12,3L2,12h2v8h6v-6h2v6h6v-8h2L19,9.3z M17,18h-2v-6H9v6H7v-7.81l5-4.5l5,4.5V18z" />
            <path d="M10,10h4c0-1.1-0.9-2-2-2S10,8.9,10,10z" />
          </g>
        </svg>
      </ag-icon>
      <ag-icon [size]="64"
               type="info">
        <svg xmlns="http://www.w3.org/2000/svg"
             enable-background="new 0 0 24 24"
             viewBox="0 0 24 24">
          <g>
            <rect fill="none"
                  height="24"
                  width="24" />
          </g>
          <g>
            <path d="M19,9.3V4h-3v2.6L12,3L2,12h2v8h6v-6h2v6h6v-8h2L19,9.3z M17,18h-2v-6H9v6H7v-7.81l5-4.5l5,4.5V18z" />
            <path d="M10,10h4c0-1.1-0.9-2-2-2S10,8.9,10,10z" />
          </g>
        </svg>
      </ag-icon>
    </div>
  </section>
  <section>
    <h2>Avatars</h2>
    <ag-avatar text="RL"
               size="small"></ag-avatar>
    <ag-avatar text="AB"></ag-avatar>
    <ag-avatar text="RL"
               size="large"></ag-avatar>
    <ag-avatar text="RL"
               size="xlarge"></ag-avatar>
    <ag-avatar text="Sq"
               type="error"
               [isSquare]="true"></ag-avatar>
  </section>
  <h2>Default Buttons</h2>
  <section>
    <ag-button>Go</ag-button>
    <ag-button [isBordered]="true">Go</ag-button>
    <ag-button [isBlank]="true">Go</ag-button>
    <ag-button [isBlock]="true">Go</ag-button>
    <ag-button [isRounded]="true">Go</ag-button>
    <ag-button [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Primary</h2>
  <section>
    <ag-button mode="primary">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Secondary</h2>
  <section>
    <ag-button mode="secondary">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h2>Misc</h2>
  <section>
    <ag-button [isDisabled]="true">Go</ag-button>
    <ag-button mode="primary"
               [isDisabled]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isDisabled]="true">Go</ag-button>
    <ag-button size="small">Go</ag-button>
    <ag-button size="large">Go</ag-button>
    <ag-button [isSkinned]="false">No Skin</ag-button>
  </section>

  <section>
    <h2>Button Groups</h2>
    <ag-button-group ariaLabel="A useful ariaLabel">
      <div class="btn-first-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 1</ag-button>
      </div>
      <ag-button mode="primary"
                 [isBordered]="true">Button 2</ag-button>
      <ag-button mode="primary"
                 [isBordered]="true">Button 3</ag-button>
      <div class="btn-last-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 4</ag-button>
      </div>
    </ag-button-group>
  </section>
  <section>
    <h2>Cards</h2>
    <ag-card>
      <div style="padding: 24px;">Default</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true">
      <div style="padding: 24px;">Stacked</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true"
             [isAnimated]="true">
      <div style="padding: 24px;">Stacked & Animated</div>
      <div style="padding: 24px;">This card will animate upwards by default.</div>
    </ag-card>
    <ag-card [isStacked]="true"
             [isAnimated]="true"
             css="animation-override">
      <div style="padding: 24px;">Stacked & Animated</div>
      <div style="padding: 24px;">We've overriden the animation direction. Inspect to see .animation-override</div>
    </ag-card>
    <ag-card [isSkinned]="false">
      <div style="padding: 24px;">Base Card</div>
      <div style="padding: 24px;">No Skin</div>
    </ag-card>
    <ag-card css="additional-classes">
      <div style="padding: 24px;">Custom CSS Class Overrides</div>
      <div style="padding: 24px;">Inspect to see additional-classes</div>
    </ag-card>
  </section>
  <section>
    <h2>Breadcrumbs</h2>
    <ag-breadcrumb
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb type="bullet"
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb type="arrow"
                   [routes]="[{ label: 'Tennis', url: '#tennis'}, { label: 'Superstars', url: '#tennis-superstars' }, { label: 'Serena Williams', url: '#tennis-superstars-serena' }]">
    </ag-breadcrumb>
    <ag-breadcrumb [routes]="[{ label: 'A single route will look *linkless*' }]"></ag-breadcrumb>
    <ag-breadcrumb [routes]="[{label: 'First', url: '#foo'}, { label: 'Second', url: '#bar' }]"></ag-breadcrumb>
  </section>
  <section>
    <h2>Choice Inputs</h2>
    <ag-choice-input type="radio"
                     [options]="[{ name: 'solo', value: 'stevie', label: 'Stevie Wonder'}, { name: 'solo', value: 'whitney', label: 'Whitney Houston' }, { name: 'solo', value: 'charlie', label: 'Charlie Wilson' }]">
    </ag-choice-input>

    <ag-choice-input type="checkbox"
                     [options]="[{ name: 'bands', value: 'bonjovi', label: 'Bon Jovi'}, { name: 'bands', value: 'stones', label: 'Rolling Stones' }, { name: 'bands', value: 'isleybros', label: 'Isley Brothers' }]"
                     legendLabel="Large"
                     size="large"
                     [isInline]="true"></ag-choice-input>
  </section>
  <section>
    <h2>Close button</h2>
    <ag-close></ag-close>
    <ag-close size="small"></ag-close>
    <ag-close size="large"></ag-close>
    <ag-close size="xlarge"></ag-close>
  </section>
  <section>
    <div class="mbe48">
      <h2>Multiple Disclose</h2>
      <p class="mbs16 mbe24">Multiple disclose elements can be stacked to achieve a
        progressively disclosed pattern that resembles an Accordion pattern. Further,
        individual disclosed elements may be open by default if we supply the
        <code>[isOpen]="true"</code> prop as we do in the first disclose element below:
      </p>
      <ag-disclose [isOpen]="true"
                   title="Roger Federer">
        Roger Federer is a Swiss professional tennis player. He is ranked No. 11 in the world by the Association of
        Tennis
        Professionals. He has won 20 Grand Slam men's singles titles, an all-time record shared with Rafael Nadal and
        Novak
        Djokovic (Wikipedia).
      </ag-disclose>
      <ag-disclose title="Serena Williams">
        Serena Jameka Williams is an American professional tennis player. She has won 23 Grand Slam singles titles,
        the
        most
        by any player in the Open Era, and the second-most of all time behind Margaret Court. The Women's Tennis
        Association
        ranked her singles world No. 1 on eight separate occasions between 2002 and 2017.(Wikipedia).
      </ag-disclose>
      <ag-disclose title="Stefi Graf">
        Stefanie Maria Graf is a German former professional tennis player. She was ranked world No. 1 for a record 377
        weeks
        and won 22 Grand Slam singles titles, which is the second-most since the introduction of the Open Era in 1968
        and
        third-most of all-time behind Margaret Court and Serena Williams (Wikipedia).
      </ag-disclose>
      <ag-disclose title="Andre Agassi">
        Andre Kirk Agassi is an American former world No. 1 tennis player. He is an eight-time major champion and a
        1996
        Olympic gold medalist, as well as a runner-up in seven other Grand Slam tournaments. Agassi was the first man
        to
        win
        four Australian Open singles titles in the Open Era (Wikipedia).
      </ag-disclose>
    </div>
  </section>

  <section>
    <h2>HTML5 Compatible Inputs</h2>
    <ag-input id="in1"
              size="small"
              placeholder="Enter name…"
              label="Small input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in2"
              placeholder="Enter name…"
              label="Default input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in3"
              size="large"
              placeholder="Enter name…"
              label="Large input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in4"
              [isRounded]="true"
              placeholder="Enter name…"
              label="Rounded input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in5"
              [isUnderlined]="true"
              placeholder="Enter name…"
              label="Underlined input"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in6"
              [isUnderlined]="true"
              [isUnderlinedWithBackground]="true"
              placeholder="Enter name…"
              label="Underlined with background"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in7"
              helpText="Some useful help text can go here"
              placeholder="Enter name…"
              label="Help text"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in8"
              [isInvalid]="true"
              invalidText="It's impossible to have a string that is cool enough for this field."
              placeholder="Enter a very cool string…"
              label="Cool factor"
              type="text"></ag-input>
  </section>
  <section>
    <ag-input id="in9"
              [hasLeftAddon]="true"
              [hasRightAddon]="true"
              label="Input with addons"
              type="text">
      <div addOnLeft
           class="addOnLeft">
        <ag-icon [size]="18"
                 type="error">
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="currentColor">
            <path fill-rule="evenodd"
                  d="M21.03 5.72a.75.75 0 010 1.06l-11.5 11.5a.75.75 0 01-1.072-.012l-5.5-5.75a.75.75 0 111.084-1.036l4.97 5.195L19.97 5.72a.75.75 0 011.06 0z" />
          </svg>
        </ag-icon>
      </div>
      <div addOnRight
           class="addOnRight">
        <ag-icon [size]="18"
                 type="info">
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="currentColor">
            <path
                  d="M13 7.5a1 1 0 11-2 0 1 1 0 012 0zm-3 3.75a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v4.25h.75a.75.75 0 010 1.5h-3a.75.75 0 010-1.5h.75V12h-.75a.75.75 0 01-.75-.75z" />
            <path fill-rule="evenodd"
                  d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zM2.5 12a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z" />
          </svg>
        </ag-icon>
      </div>
    </ag-input>
  </section>
  <section>
    <ag-input id="in10"
              placeholder="Enter something…"
              label="Textarea"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in11"
              placeholder="Enter something…"
              label="Textarea small"
              size="small"
              [rows]="10"
              [cols]="5"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in12"
              placeholder="Enter something…"
              label="Textarea large"
              size="large"
              [rows]="10"
              [cols]="5"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <ag-input id="in13"
              placeholder="Enter something…"
              label="Textarea"
              type="textarea">
    </ag-input>
  </section>
  <section>
    <h2>Tabs</h2>
    <ag-tabs>
      <ag-tab-panel panelId="panel1"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel2"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <ag-tabs [isVerticalOrientation]="true">
      <ag-tab-panel panelId="panel3"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel4"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters) (no padding or margins so
        consumer
        can control desired gutters)
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <ag-tabs size="xlarge"
             [disabledOptions]="['Tab 2', 'Tab 4']">
      <ag-tab-panel panelId="panel11"
                    tabButtonTitle="Tab 1">
        Tab 1 content (no padding or margins so consumer can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel12"
                    tabButtonTitle="Tab 2">
        Tab 2 content (no padding or margins so consumer can control desired gutters)
      </ag-tab-panel>
      <ag-tab-panel panelId="panel13"
                    tabButtonTitle="Tab 3">
        Tab 3 content
      </ag-tab-panel>
      <ag-tab-panel panelId="panel14"
                    tabButtonTitle="Tab 4">
        Tab 4 content
      </ag-tab-panel>
      <ag-tab-panel panelId="panel15"
                    tabButtonTitle="Tab 5">
        Tab 5 content
      </ag-tab-panel>
    </ag-tabs>
  </section>
  <section>
    <h2>Tags</h2>
    <ag-tag>unknown</ag-tag>
    <ag-tag shape="round">rounded</ag-tag>
    <ag-tag shape="pill">badge</ag-tag>
    <ag-tag type="info"
            [isUppercase]="true">info</ag-tag>
    <ag-tag type="success"
            [isUppercase]="true">success</ag-tag>
    <ag-tag type="warning"
            [isUppercase]="true">warning</ag-tag>
    <ag-tag type="error"
            [isUppercase]="true">error</ag-tag>
    <ag-tag type="error"
            shape="circle">2</ag-tag>
  </section>
  <section>
    <h2>Select</h2>
    <ag-select uniqueId="sel1"
               name="select1"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' },
      { value: 'serena', label: 'Serena Williams' },
      { value: 'mac', label: 'John McEnroe' },
      { value: 'borg', label: 'Bjorn Borg' },
      { value: 'althea', label: 'Althea Gibson' },
      { value: 'roger', label: 'Roger Federer' },
      ]"></ag-select>
  </section>
  <section>
    <h2>Select first option custom label</h2>
    <ag-select uniqueId="sel2"
               name="select2"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' },
      { value: 'serena', label: 'Serena Williams' },
      { value: 'mac', label: 'John McEnroe' },
      { value: 'borg', label: 'Bjorn Borg' },
      { value: 'althea', label: 'Althea Gibson' },
      { value: 'roger', label: 'Roger Federer' },
      ]"></ag-select>
  </section>
  <section>
    <h2>Select disabled</h2>
    <ag-select uniqueId="sel3"
               name="select3"
               [isDisabled]="true"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
      { value: 'andre', label: 'Andre Agassi' }
      ]"></ag-select>
  </section>
  <section>
    <h2>Select small</h2>
    <ag-select uniqueId="sel4"
               name="select4"
               size="small"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]"></ag-select>
  </section>
  <section>
    <h2>Select large</h2>
    <ag-select uniqueId="sel5"
               name="select5"
               size="large"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]"></ag-select>
  </section>
  <section>
    <h2>Select multiple</h2>
    <ag-select uniqueId="sel6"
               name="select6"
               size="large"
               [isMultiple]="true"
               [multipleSize]="4"
               defaultOptionLabel="Select your favorite tennis player"
               labelCopy="Select the best tennis player of all time"
               [options]="[
               { value: 'andre', label: 'Andre Agassi' },
               { value: 'serena', label: 'Serena Williams' },
               { value: 'mac', label: 'John McEnroe' },
               { value: 'borg', label: 'Bjorn Borg' },
               { value: 'althea', label: 'Althea Gibson' },
               { value: 'roger', label: 'Roger Federer' },
               ]">
    </ag-select>
  </section>
  <section>
    <h2>Switch</h2>
    <ag-switch label="Switch small"
               size="small"></ag-switch>
    <ag-switch label="Switch default (medium)"></ag-switch>
    <ag-switch label="Switch large"
               size="large"></ag-switch>
    <ag-switch [isChecked]="true"
               label="Switch prechecked"></ag-switch>
    <ag-switch [isDisabled]="true"
               label="Switch disabled"></ag-switch>
    <ag-switch [isBordered]="true"
               label="Switch bordered"></ag-switch>
    <ag-switch [isAction]="true"
               [isChecked]="true"
               label="Switch action prechecked"></ag-switch>
    <ag-switch [isAction]="true"
               [isBordered]="true"
               label="Switch action bordered"></ag-switch>
    <h2 class="mbs24 mbe24">Switch label on right</h2>
    <ag-switch label="Small label on right"
               size="small"
               labelPosition="right"></ag-switch>
  </section>
  <section>
    <h2>Headers</h2>
    <ag-header>
      <a href="https://web.dev/">web.dev</a>
      <ag-header-nav>
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item class="mis12 mie16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
    <ag-header [isHeaderContentStart]="true">
      <a href="https://web.dev/">web.dev</a>
      <ag-header-nav class="header-flex-fill">
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item class="mis12 mie16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
    <ag-header [isHeaderContentEnd]="true">
      <a class="flex-fill"
         href="https://web.dev/">web.dev</a>
      <ag-header-nav>
        <ag-header-nav-item class="mie12">
          <a href="https://css-tricks.com/">CSS-Tricks</a>
        </ag-header-nav-item>
        <ag-header-nav-item css="header-mbe16">
          <a href="https://developer.mozilla.org/en-US/">MDN</a>
        </ag-header-nav-item>
      </ag-header-nav>
      <a href="https://www.freecodecamp.org/">freeCodeCamp</a>
    </ag-header>
  </section>
</main>
