// agnostic-svelte-ts/src/lib/components/Button/ButtonGroup.svelte
<style>
/**
 * Button Groups. See also button-core.css which has btn-grouped which needs to be
 * applied to the buttons that are projected within a button group.
 */
.btn-group {
  display: inline-flex;
  flex-direction: row;
}

</style>

<script lang="ts">
  export let ariaLabel = "";
  export let css = "";
  let klasses: string = ["btn-group", css ? `${css}` : ""].filter((cl) => cl.length).join(' ');
</script>

<div class={klasses} role="group" aria-label={ariaLabel} on:click>
  <slot />
</div>

// agnostic-vue-ts/src/components/ButtonGroup.vue
<template>
  <div
    :class="classes"
    role="group"
    :aria-label="ariaLabel"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, useCssModule } from "vue";

export interface ButtonGroupProps {
  ariaLabel: string;
  css?: string;
}

const styles = useCssModule();

const props = withDefaults(defineProps<ButtonGroupProps>(), {
  css: "",
});

const classes = computed(() => {
  return {
    [styles["btn-group"]]: true,
    [`${props.css}`]: props.css,
  };
});
</script>

<style module>
/**
 * Button Groups. See also button-core.css which has btn-grouped which needs to be
 * applied to the buttons that are projected within a button group.
 */
.btn-group {
  display: inline-flex;
  flex-direction: row;
}

</style>
