// agnostic-svelte-ts/src/lib/components/Dialog/Dialog.svelte
<style>

  /* ---------- GLOBAL STYLES ---------- */
  /* Note this component requires global styles and doesn't get copied over from copystyles.js
  and is "locked down". Svelte no longer appears to support <style global> and CSS Modules support
  isn't built in. So, not ideal, but this is what we'll have to do for this component. */
  
  /* These are styles for the case where classNames.closeButton property was NOT
  passed in and so we're generating the default close 'X' button on the upper right. */
  :global(.dialog-close-button) {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    background-color: transparent;
    border: 0;
    border-radius: 0;
    box-shadow: none;
    width: var(--fluid-32);
    height: var(--fluid-32);
  }
  
  :global(.dialog-close-button:hover,
  .dialog-close-button:active,
  .dialog-close-button:focus) {
    background: none;
  
    /* Needed for High Contrast mode */
    outline: var(--agnostic-focus-ring-outline-width)
      var(--agnostic-focus-ring-outline-style)
      var(--agnostic-focus-ring-outline-color);
  }
  
  :global(.dialog-close-button:focus) {
    box-shadow: 0 0 0 3px var(--agnostic-focus-ring-color);
    transition: box-shadow var(--agnostic-timing-fast) ease-out;
  }
  
  @media (prefers-reduced-motion), (update: slow) {
    :global(.dialog-close-button:focus) {
      transition-duration: 0.001ms !important;
    }
  }
  
  :global(.close-button-large > .close) {
    width: var(--fluid-16);
    height: var(--fluid-16);
  }
  
  :global(.dialog-close-button:hover .close) {
    opacity: 100%;
  }
  
  
  :global(.dialog),
  :global(.dialog-overlay) {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
  
  :global(.dialog) {
    z-index: 1001;
    display: flex;
  }
  
  :global(.dialog[aria-hidden="true"]) {
    display: none;
  }
  
  :global(.dialog-overlay) {
    background-color: rgb(50 50 50 / 60%);
    animation: fade-in var(--agnostic-timing-fast) both;
  }
  
  :global(.dialog-content) {
    background-color: white;
    margin: auto;
    z-index: 1001;
    position: relative;
    padding: var(--fluid-16);
    max-width: 90%;
    width: 600px;
    border-radius: var(--agnostic-radius);
  }
  
  :global(.dialog-fade-in) {
    animation: fade-in var(--agnostic-timing-fast) both;
  }
  
  :global(.dialog-slide-up) {
    animation: slide-up var(--agnostic-timing-slow) var(--agnostic-timing-fast) both;
  }
  
  /**
   * Cannot use two separate CSS classes with animation: foo, bar
   * as the later class will overwrite the first (so this combines)
   */
  :global(.dialog-slide-up-fade-in) {
    animation:
      fade-in var(--agnostic-timing-fast) both,
      slide-up var(--agnostic-timing-slow) var(--agnostic-timing-fast) both;
  }
  
  @media screen and (min-width: 700px) {
    :global(.dialog-content) {
      padding: var(--fluid-32);
    }
  }
  
  @keyframes -global-fade-in {
    from {
      opacity: 0%;
    }
  }
  
  @keyframes -global-slide-up {
    from {
      transform: translateY(10%);
    }
  }
  
  /* Shared with AgnosticUI close buton so only need positioning and transition */
  :global(.dialog-close) {
    position: absolute;
    top: var(--fluid-8);
    right: var(--fluid-8);
  }
  
  @media (prefers-reduced-motion), (update: slow) {
    :global(.dialog-slide-up-fade-in, .dialog-fade-in, .dialog-slide-up, .dialog-content) {
      transition-duration: 0.001ms !important;
    }
  }
  
  @media only screen and (min-width: 576px) {
    :global(.dialog-close) {
      top: var(--fluid-12);
      right: var(--fluid-12);
    }
  }
  
  @media screen and (min-width: 768px) {
    :global(.dialog-close) {
      top: var(--fluid-16);
      right: var(--fluid-16);
    }
  }
  
  /* We use div.drawer-* for specificity battle :( */
  :global(div.drawer-start) {
    right: initial;
  }
  
  :global(div.drawer-start[aria-hidden]) {
    transform: none;
  }
  
  :global(div.drawer-end) {
    left: initial;
  }
  
  :global(div.drawer-end[aria-hidden]) {
    transform: none;
  }
  
  :global(div.drawer-top) {
    bottom: initial;
    transform: none;
  }
  
  :global(div.drawer-top[aria-hidden]) {
    transform: none;
  }
  
  :global(div.drawer-bottom) {
    top: initial;
    transform: none;
  }
  
  :global(div.drawer-bottom[aria-hidden]) {
    transform: none;
  }
  
  :global(div.drawer-content) {
    margin: initial;
    max-width: initial;
    border-radius: initial;
  }
  
  :global(div.drawer-start div.drawer-content, div.drawer-end div.drawer-content) {
    width: 25rem;
  }
  
  :global(div.drawer-top div.drawer-content, div.drawer-bottom div.drawer-content) {
    height: 25vh;
    width: 100%;
  }
  </style>
  
  <script lang="ts">
    import Close from "../Close/Close.svelte";
    import SvelteA11yDialog from "svelte-a11y-dialog/SvelteA11yDialog.svelte";
    import { createEventDispatcher } from "svelte";
    const dispatch = createEventDispatcher();
  
    export let id;
    export let title;
    export let dialogRoot;
    export let role: "dialog" | "alertdialog" = "dialog";
    export let titleId = "";
    export let closeButtonLabel = "Close button";
    export let closeButtonPosition: "first" | "last" | "none" = "first";
    export let drawerPlacement = "";
  
    /**
     * Animates the dialog content by fading in. Set to false to disable.
     */
    export let isAnimationFadeIn = false;
  
    /**
     * Animates the dialog content by sliding up. Set to false to disable.
     */
    export let isAnimationSlideUp = false;
  
    /**
     * Handles a11y-dialog instantiation and assigning of dialog instance
     */
    let dialogInstance;
    const assignDialogInstance = (ev) => {
      dialogInstance = ev.detail.instance;
      dispatch("instance", {
        instance: dialogInstance,
      });
    };
  
    export let classNames = {};
    const documentClasses = [
      "dialog-content",
      isAnimationFadeIn && isAnimationSlideUp ? "dialog-slide-up-fade-in" : "",
      !isAnimationFadeIn && isAnimationSlideUp ? "dialog-slide-up" : "",
      isAnimationFadeIn && !isAnimationSlideUp ? "dialog-fade-in" : "",
      drawerPlacement.length ? "drawer-content" : "",
    ]
      .filter((c) => c)
      .join(" ");
  
    const containerClasses = [
      "dialog",
      drawerPlacement ? `drawer-${drawerPlacement}` : "",
      ]
      .filter((c) => c)
      .join(" ");
  
    const defaultClassNames = {
      container: containerClasses,
      document: documentClasses,
      overlay: "dialog-overlay",
      title: "h4 mbe16",
      // Borrows .close-button (from close.css) as it gives us the transparent
      // style plus the a11y focus ring we want applied to dialog's close button
      closeButton: "dialog-close dialog-close-button",
    };
  
    $: getClassNames = () => {
      return { ...defaultClassNames, ...classNames };
    };
  </script>
  
  <SvelteA11yDialog
    id={id}
    dialogRoot={dialogRoot}
    closeButtonLabel={closeButtonLabel}
    closeButtonPosition={closeButtonPosition}
    title={title}
    titleId={titleId}
    role={role}
    classNames={getClassNames()}
    on:instance={assignDialogInstance}
  >
    <slot name="closeButtonContent" slot="closeButtonContent">
      <Close isFaux size="large" />
    </slot>
    <slot />
  </SvelteA11yDialog>

// agnostic-vue-ts/src/components/Dialog.vue
<template>
  <a11y-dialog
    :id="id"
    :dialog-root="dialogRoot"
    :close-button-label="closeButtonLabel"
    :close-button-position="closeButtonPosition"
    :title-id="titleId"
    :class-names="getClassNames()"
    :role="role"
    @dialog-ref="assignDialogRef"
  >
    <template #closeButtonContent>
      <slot name="closeButtonContent">
        <Close
          is-faux
          size="large"
        >
          Close
        </Close>
      </slot>
    </template>
    <template #title>
      <slot name="title" />
    </template>
    <template #default>
      <slot name="default" />
    </template>
  </a11y-dialog>
</template>
<script setup lang="ts">
import { A11yDialog } from "vue-a11y-dialog";
import Close from "./Close.vue";
import {
  DialogClassNames,
  DialogCloseButtonPositions,
  DialogRoles,
} from "./DialogApi";
import { useCssModule } from "vue";

const styles = useCssModule();
const emit = defineEmits(["instance"]);

interface Props {
  id: string;
  dialogRoot: string;
  classNames?: DialogClassNames;
  role?: DialogRoles;
  titleId?: string;
  closeButtonLabel?: string;
  closeButtonPosition?: DialogCloseButtonPositions;
  isAnimationFadeIn?: boolean;
  isAnimationSlideUp?: boolean;
  drawerPlacement?: DialogDrawerPlacement;
}

const props = withDefaults(defineProps<Props>(), {
  classNames: {},
  role: "dialog",
  closeButtonLabel: "Close this dialog window",
  closeButtonPosition: "first",
  isAnimationFadeIn: false,
  isAnimationSlideUp: false,
  drawerPlacement: [],
});

const assignDialogRef = (instance) => {
  emit("instance", instance);
};

/**
 * classNamesProps is passed so we can check before using our local CSS Modules styles,
 * as we don't want to overwrite consumer set classNames if passed in.
 */
// const getClassNames = (classNamesProps, isFadeIn, isSlideUp) => {
const getClassNames = () => {
  const { classNames, drawerPlacement, isAnimationFadeIn, isAnimationSlideUp } =
    props;

  const documentClasses = {
    [styles["dialog-content"]]: true,
    [styles["dialog-slide-up-fade-in"]]:
      isAnimationFadeIn && isAnimationSlideUp,
    [styles["dialog-slide-up"]]: !isAnimationFadeIn && isAnimationSlideUp,
    [styles["dialog-fade-in"]]: isAnimationFadeIn && !isAnimationSlideUp,
    [styles["drawer-content"]]: drawerPlacement.length,
  };
  const containerClasses = {
    [styles.dialog]: true,
    [styles[`drawer-${drawerPlacement}`]]: drawerPlacement,
  };
  const defaultClassNames = {
    container: containerClasses,
    overlay: styles["dialog-overlay"],
    document: documentClasses,
    title: "h4 mbe16",
    closeButton: `${styles["dialog-close"]} dialog-close-button`,
  };
  // Anything defined on classNames props passed in will override our defaults
  return { ...defaultClassNames, ...classNames };
};
</script>

<style>
/* These are styles for the case where classNames.closeButton property was NOT
passed in and so we're generating the default close 'X' button on the upper right. */
.dialog-close-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background-color: transparent;
  border: 0;
  border-radius: 0;
  box-shadow: none;
  width: var(--fluid-32);
  height: var(--fluid-32);
}

.dialog-close-button:hover,
.dialog-close-button:active,
.dialog-close-button:focus {
  background: none;

  /* Needed for High Contrast mode */
  outline: var(--agnostic-focus-ring-outline-width)
    var(--agnostic-focus-ring-outline-style)
    var(--agnostic-focus-ring-outline-color);
}

.dialog-close-button:focus {
  box-shadow: 0 0 0 3px var(--agnostic-focus-ring-color);
  transition: box-shadow var(--agnostic-timing-fast) ease-out;
}

@media (prefers-reduced-motion), (update: slow) {
  .dialog-close-button:focus {
    transition-duration: 0.001ms !important;
  }
}

.close-button-large > .close {
  width: var(--fluid-16);
  height: var(--fluid-16);
}

.dialog-close-button:hover .close {
  opacity: 100%;
}
</style>

<style module>
.dialog,
.dialog-overlay {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}

.dialog {
  z-index: 1001;
  display: flex;
}

.dialog[aria-hidden="true"] {
  display: none;
}

.dialog-overlay {
  background-color: rgb(50 50 50 / 60%);
  animation: fade-in var(--agnostic-timing-fast) both;
}

.dialog-content {
  background-color: white;
  margin: auto;
  z-index: 1001;
  position: relative;
  padding: var(--fluid-16);
  max-width: 90%;
  width: 600px;
  border-radius: var(--agnostic-radius);
}

.dialog-fade-in {
  animation: fade-in var(--agnostic-timing-fast) both;
}

.dialog-slide-up {
  animation: slide-up var(--agnostic-timing-slow) var(--agnostic-timing-fast)
    both;
}

/**
 * Cannot use two separate CSS classes with animation: foo, bar
 * as the later class will overwrite the first (so this combines)
 */
.dialog-slide-up-fade-in {
  animation: fade-in var(--agnostic-timing-fast) both,
    slide-up var(--agnostic-timing-slow) var(--agnostic-timing-fast) both;
}

@media screen and (min-width: 700px) {
  .dialog-content {
    padding: var(--fluid-32);
  }
}

@keyframes fade-in {
  from {
    opacity: 0%;
  }
}

@keyframes slide-up {
  from {
    transform: translateY(10%);
  }
}

/* Shared with AgnosticUI close buton so only need positioning and transition */
.dialog-close {
  position: absolute;
  top: var(--fluid-8);
  right: var(--fluid-8);
}

@media (prefers-reduced-motion), (update: slow) {
  .dialog-slide-up-fade-in,
  .dialog-fade-in,
  .dialog-slide-up,
  .dialog-content {
    transition-duration: 0.001ms !important;
  }
}

@media only screen and (min-width: 576px) {
  .dialog-close {
    top: var(--fluid-12);
    right: var(--fluid-12);
  }
}

@media screen and (min-width: 768px) {
  .dialog-close {
    top: var(--fluid-16);
    right: var(--fluid-16);
  }
}

.drawer-start {
  right: initial;
}

.drawer-start[aria-hidden] {
  transform: none;
}

.drawer-end {
  left: initial;
}

.drawer-end[aria-hidden] {
  transform: none;
}

.drawer-top {
  bottom: initial;
  transform: none;
}

.drawer-up[aria-hidden] {
  transform: none;
}

.drawer-bottom {
  top: initial;
  transform: none;
}

.drawer-bottom[aria-hidden] {
  transform: none;
}

.drawer-content {
  margin: initial;
  max-width: initial;
  border-radius: initial;
}

.drawer-start .drawer-content,
.drawer-end .drawer-content {
  width: 25rem;
}

.drawer-top .drawer-content,
.drawer-bottom .drawer-content {
  height: 25vh;
  width: 100%;
}
</style>
