// v2/playbooks/grid/react-example/src/panels/TanstackPanel.tsx
import { useState, useMemo, useRef } from 'react'
import {
  useReactTable,
  getCoreRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  createColumnHelper,
  flexRender,
  type SortingState,
  type ColumnFiltersState,
  type VisibilityState,
  type RowSelectionState,
} from '@tanstack/react-table'
import { Pencil, ChevronUp, ChevronDown, ChevronsUpDown } from 'lucide-react'
import { ReactButton } from '../components/ag/Button/react/ReactButton'
import { ReactIconButton } from '../components/ag/IconButton/react/ReactIconButton'
import { ReactInput } from '../components/ag/Input/react/ReactInput'
import { ReactCheckbox } from '../components/ag/Checkbox/react/ReactCheckbox'
import { ReactTag } from '../components/ag/Tag/react/ReactTag'
import { ReactDialog } from '../components/ag/Dialog/react/ReactDialog'
import { ReactPagination } from '../components/ag/Pagination/react/ReactPagination'
import { ReactToast } from '../components/ag/Toast/react/ReactToast'
import { ReactEmptyState } from '../components/ag/EmptyState/react/ReactEmptyState'
import { ReactMenuButton, ReactMenu, ReactMenuItem } from '../components/ag/Menu/react/ReactMenu'
import type { TagVariant } from '../components/ag/Tag/core/_Tag'
import type { Product } from '../data/products'

const helper = createColumnHelper<Product>()

const HIDEABLE_COLS = ['category', 'price', 'stock', 'status']

function statusVariant(status: Product['status']): TagVariant {
  if (status === 'active') return 'success'
  if (status === 'low-stock') return 'warning'
  return ''
}

export function TanstackPanel({ products: initialProducts }: { products: Product[] }) {
  const [localProducts, setLocalProducts] = useState<Product[]>(initialProducts)
  const [sorting, setSorting] = useState<SortingState>([])
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([])
  const [globalFilter, setGlobalFilter] = useState('')
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({})
  const [rowSelection, setRowSelection] = useState<RowSelectionState>({})
  const [dialogOpen, setDialogOpen] = useState(false)
  const [toastOpen, setToastOpen] = useState(false)
  const [toastMsg, setToastMsg] = useState('')
  const toastTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  function showToast(msg: string) {
    setToastMsg(msg)
    setToastOpen(true)
    if (toastTimerRef.current) clearTimeout(toastTimerRef.current)
    toastTimerRef.current = setTimeout(() => setToastOpen(false), 3000)
  }

  const columns = useMemo(
    () => [
      helper.display({
        id: 'select',
        header: ({ table }) => (
          <ReactCheckbox
            labelText=""
            checked={table.getIsAllPageRowsSelected()}
            indeterminate={table.getIsSomePageRowsSelected()}
            onChange={() => table.toggleAllPageRowsSelected()}
          />
        ),
        cell: ({ row }) => (
          <ReactCheckbox
            labelText=""
            checked={row.getIsSelected()}
            disabled={!row.getCanSelect()}
            onChange={() => row.toggleSelected()}
          />
        ),
        enableSorting: false,
        enableHiding: false,
      }),
      helper.accessor('name', {
        header: 'Name',
        enableHiding: false,
      }),
      helper.accessor('category', {
        header: 'Category',
        filterFn: 'equals',
      }),
      helper.accessor('price', {
        header: 'Price',
        cell: info => `$${info.getValue().toFixed(2)}`,
      }),
      helper.accessor('stock', {
        header: 'Stock',
      }),
      helper.accessor('status', {
        header: 'Status',
        cell: info => (
          <ReactTag variant={statusVariant(info.getValue())}>
            {info.getValue()}
          </ReactTag>
        ),
      }),
      helper.display({
        id: 'actions',
        header: 'Actions',
        enableHiding: false,
        cell: ({ row }) => (
          <ReactIconButton
            label={`Edit ${row.original.name}`}
            onIconButtonClick={() => showToast(`Editing: ${row.original.name}`)}
          >
            <Pencil size={16} />
          </ReactIconButton>
        ),
      }),
    ],
    [],
  )

  const table = useReactTable({
    data: localProducts,
    columns,
    enableMultiSort: true,
    enableRowSelection: true,
    state: {
      sorting,
      columnFilters,
      globalFilter,
      columnVisibility,
      rowSelection,
    },
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onGlobalFilterChange: setGlobalFilter,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    initialState: { pagination: { pageSize: 10 } },
  })

  const selectedCount = Object.keys(rowSelection).length
  const totalPages = table.getPageCount()
  const pageIndex = table.getState().pagination.pageIndex
  const currentPageSize = table.getState().pagination.pageSize

  function handleDeleteConfirm() {
    const selectedIds = new Set(
      table.getSelectedRowModel().rows.map(r => r.original.id)
    )
    const count = selectedIds.size
    setLocalProducts(prev => prev.filter(p => !selectedIds.has(p.id)))
    table.resetRowSelection()
    setDialogOpen(false)
    showToast(`Deleted ${count} product(s)`)
  }

  const categoryFilter = (columnFilters.find(f => f.id === 'category')?.value as string) || ''
  const nameFilter = (columnFilters.find(f => f.id === 'name')?.value as string) || ''

  function setNameFilter(val: string) {
    setColumnFilters(prev => {
      const without = prev.filter(f => f.id !== 'name')
      return val ? [...without, { id: 'name', value: val }] : without
    })
    table.setPageIndex(0)
  }

  function setCategoryFilter(val: string) {
    setColumnFilters(prev => {
      const without = prev.filter(f => f.id !== 'category')
      return val ? [...without, { id: 'category', value: val }] : without
    })
    table.setPageIndex(0)
  }

  const rows = table.getRowModel().rows

  return (
    <div>
      {/* Toolbar */}
      <div className="panel-toolbar">
        <ReactInput
          type="search"
          placeholder="Search…"
          value={globalFilter}
          onInput={(e: Event) => {
            setGlobalFilter((e.target as HTMLInputElement).value)
            table.setPageIndex(0)
          }}
        />
        <ReactInput
          placeholder="Filter name…"
          value={nameFilter}
          onInput={(e: Event) => setNameFilter((e.target as HTMLInputElement).value)}
        />
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          style={{
            border: '1px solid var(--ag-border)',
            borderRadius: 'var(--ag-radius-md)',
            padding: '0.375rem 0.75rem',
            background: 'var(--ag-background-primary)',
            color: 'var(--ag-text-primary)',
            fontSize: 'var(--ag-font-size-base)',
            fontFamily: 'inherit',
          }}
        >
          <option value="">All Categories</option>
          <option value="Electronics">Electronics</option>
          <option value="Clothing">Clothing</option>
          <option value="Food">Food</option>
          <option value="Books">Books</option>
          <option value="Tools">Tools</option>
        </select>

        <div className="panel-toolbar-right">
          <ReactMenuButton menuVariant="chevron" buttonVariant="secondary">
            Columns
            <ReactMenu slot="menu">
              {HIDEABLE_COLS.map(colId => {
                const col = table.getColumn(colId)
                if (!col) return null
                return (
                  <ReactMenuItem key={colId}>
                    <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}>
                      <input
                        type="checkbox"
                        checked={col.getIsVisible()}
                        onChange={col.getToggleVisibilityHandler()}
                      />
                      {colId.charAt(0).toUpperCase() + colId.slice(1)}
                    </label>
                  </ReactMenuItem>
                )
              })}
            </ReactMenu>
          </ReactMenuButton>
        </div>
      </div>

      {/* Delete selected */}
      {selectedCount > 0 && (
        <div className="delete-row">
          <ReactButton
            variant="danger"
            onClick={() => setDialogOpen(true)}
          >
            Delete Selected ({selectedCount})
          </ReactButton>
        </div>
      )}

      {/* Table */}
      {rows.length === 0 ? (
        <ReactEmptyState
          title="No products found."
          subtitle="Try adjusting your filters."
        />
      ) : (
        <div style={{ overflowX: 'auto' }}>
          <table className="ag-table">
            <caption className="visually-hidden">Product inventory (TanStack)</caption>
            <thead>
              {table.getHeaderGroups().map(hg => (
                <tr key={hg.id}>
                  {hg.headers.map(header => {
                    const sorted = header.column.getIsSorted()
                    const sortIdx = header.column.getSortIndex()
                    const canSort = header.column.getCanSort()
                    return (
                      <th
                        key={header.id}
                        className={`ts-th${header.column.id === 'category' ? ' col-category' : ''}`}
                        onClick={canSort ? header.column.getToggleSortingHandler() : undefined}
                      >
                        {header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
                        {canSort && (
                          <span className="sort-icon">
                            {sorted === 'asc' ? <ChevronUp size={14} /> : sorted === 'desc' ? <ChevronDown size={14} /> : <ChevronsUpDown size={12} />}
                          </span>
                        )}
                        {sorted && sorting.length > 1 && (
                          <span className="sort-order">{sortIdx + 1}</span>
                        )}
                      </th>
                    )
                  })}
                </tr>
              ))}
            </thead>
            <tbody>
              {rows.map(row => (
                <tr key={row.id}>
                  {row.getVisibleCells().map(cell => (
                    <td
                      key={cell.id}
                      className={`ts-td${cell.column.id === 'category' ? ' col-category' : ''}`}
                      data-label={cell.column.id}
                    >
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Pagination row */}
      <div className="pagination-row">
        <select
          value={String(currentPageSize)}
          onChange={(e) => {
            table.setPageSize(Number(e.target.value))
            table.setPageIndex(0)
          }}
          style={{
            border: '1px solid var(--ag-border)',
            borderRadius: 'var(--ag-radius-md)',
            padding: '0.375rem 0.75rem',
            background: 'var(--ag-background-primary)',
            color: 'var(--ag-text-primary)',
            fontSize: 'var(--ag-font-size-base)',
            fontFamily: 'inherit',
          }}
        >
          <option value="10">10 / page</option>
          <option value="25">25 / page</option>
          <option value="50">50 / page</option>
        </select>

        <ReactPagination
          current={pageIndex + 1}
          totalPages={Math.max(1, totalPages)}
          onPageChange={(e: CustomEvent) => table.setPageIndex(e.detail.page - 1)}
        />
      </div>

      {/* Delete Dialog */}
      <ReactDialog
        open={dialogOpen}
        heading="Confirm Delete"
        description={`Delete ${selectedCount} selected product(s)? This cannot be undone.`}
        showCloseButton
        onDialogClose={() => setDialogOpen(false)}
      >
        <div slot="footer" style={{ display: 'flex', gap: 'var(--ag-space-2)', justifyContent: 'flex-end' }}>
          <ReactButton variant="secondary" onClick={() => setDialogOpen(false)}>
            Cancel
          </ReactButton>
          <ReactButton variant="danger" onClick={handleDeleteConfirm}>
            Delete
          </ReactButton>
        </div>
      </ReactDialog>

      {/* Toast */}
      <ReactToast
        open={toastOpen}
        type="success"
        position="top-end"
        showCloseButton
        onToastClose={() => setToastOpen(false)}
      >
        {toastMsg}
      </ReactToast>
    </div>
  )
}

// v2/playbooks/grid/vue-example/src/panels/TanstackPanel.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  useVueTable,
  getCoreRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  createColumnHelper,
  FlexRender,
  type SortingState,
  type ColumnFiltersState,
  type VisibilityState,
  type RowSelectionState,
} from '@tanstack/vue-table'
import { Pencil, ChevronUp, ChevronDown, ChevronsUpDown } from 'lucide-vue-next'
import VueButton from '../components/ag/Button/vue/VueButton.vue'
import VueIconButton from '../components/ag/IconButton/vue/VueIconButton.vue'
import VueInput from '../components/ag/Input/vue/VueInput.vue'
import VueCheckbox from '../components/ag/Checkbox/vue/VueCheckbox.vue'
import VueTag from '../components/ag/Tag/vue/VueTag.vue'
import VueDialog from '../components/ag/Dialog/vue/VueDialog.vue'
import VuePagination from '../components/ag/Pagination/vue/VuePagination.vue'
import VueToast from '../components/ag/Toast/vue/VueToast.vue'
import VueEmptyState from '../components/ag/EmptyState/vue/VueEmptyState.vue'
import { VueMenu, VueMenuItem } from '../components/ag/Menu/vue/index'
import type { TagVariant } from '../components/ag/Tag/core/_Tag'
import type { Product } from '../data/products'

const props = defineProps<{ products: Product[] }>()

const HIDEABLE_COLS = ['category', 'price', 'stock', 'status']

function statusVariant(status: Product['status']): TagVariant {
  if (status === 'active') return 'success'
  if (status === 'low-stock') return 'warning'
  return ''
}

const localProducts = ref<Product[]>([...props.products])
const sorting = ref<SortingState>([])
const columnFilters = ref<ColumnFiltersState>([])
const globalFilter = ref('')
const columnVisibility = ref<VisibilityState>({})
const rowSelection = ref<RowSelectionState>({})
const dialogOpen = ref(false)
const toastOpen = ref(false)
const toastMsg = ref('')
let toastTimer: ReturnType<typeof setTimeout> | null = null

function showToast(msg: string) {
  toastMsg.value = msg
  toastOpen.value = true
  if (toastTimer) clearTimeout(toastTimer)
  toastTimer = setTimeout(() => { toastOpen.value = false }, 3000)
}

const helper = createColumnHelper<Product>()

const columns = [
  helper.display({
    id: 'select',
    header: () => null, // handled via slot in template
    cell: () => null,
    enableSorting: false,
    enableHiding: false,
  }),
  helper.accessor('name', {
    header: 'Name',
    enableHiding: false,
  }),
  helper.accessor('category', {
    header: 'Category',
    filterFn: 'equals',
  }),
  helper.accessor('price', {
    header: 'Price',
    cell: info => `$${info.getValue().toFixed(2)}`,
  }),
  helper.accessor('stock', {
    header: 'Stock',
  }),
  helper.accessor('status', {
    header: 'Status',
    cell: () => null, // handled in template
  }),
  helper.display({
    id: 'actions',
    header: 'Actions',
    enableHiding: false,
    cell: () => null, // handled in template
  }),
]

const table = useVueTable({
  get data() { return localProducts.value },
  columns,
  enableMultiSort: true,
  enableRowSelection: true,
  state: {
    get sorting() { return sorting.value },
    get columnFilters() { return columnFilters.value },
    get globalFilter() { return globalFilter.value },
    get columnVisibility() { return columnVisibility.value },
    get rowSelection() { return rowSelection.value },
  },
  onSortingChange: (updater) => {
    sorting.value = typeof updater === 'function' ? updater(sorting.value) : updater
  },
  onColumnFiltersChange: (updater) => {
    columnFilters.value = typeof updater === 'function' ? updater(columnFilters.value) : updater
  },
  onGlobalFilterChange: (updater) => {
    globalFilter.value = typeof updater === 'function' ? updater(globalFilter.value) : updater
  },
  onColumnVisibilityChange: (updater) => {
    columnVisibility.value = typeof updater === 'function' ? updater(columnVisibility.value) : updater
  },
  onRowSelectionChange: (updater) => {
    rowSelection.value = typeof updater === 'function' ? updater(rowSelection.value) : updater
  },
  getCoreRowModel: getCoreRowModel(),
  getFilteredRowModel: getFilteredRowModel(),
  getSortedRowModel: getSortedRowModel(),
  getPaginationRowModel: getPaginationRowModel(),
  initialState: { pagination: { pageSize: 10 } },
})

const selectedCount = computed(() => Object.keys(rowSelection.value).length)
const totalPages = computed(() => table.getPageCount())
const pageIndex = computed(() => table.getState().pagination.pageIndex)
const pageSize = computed(() => table.getState().pagination.pageSize)
const rows = computed(() => table.getRowModel().rows)
const headerGroups = computed(() => table.getHeaderGroups())

const categoryFilter = computed(() =>
  (columnFilters.value.find(f => f.id === 'category')?.value as string) || ''
)
const nameFilter = computed(() =>
  (columnFilters.value.find(f => f.id === 'name')?.value as string) || ''
)

function setNameFilter(val: string) {
  const without = columnFilters.value.filter(f => f.id !== 'name')
  columnFilters.value = val ? [...without, { id: 'name', value: val }] : without
  table.setPageIndex(0)
}

function setCategoryFilter(val: string) {
  const without = columnFilters.value.filter(f => f.id !== 'category')
  columnFilters.value = val ? [...without, { id: 'category', value: val }] : without
  table.setPageIndex(0)
}

function handleDeleteConfirm() {
  const selectedIds = new Set(
    table.getSelectedRowModel().rows.map(r => r.original.id)
  )
  const count = selectedIds.size
  localProducts.value = localProducts.value.filter(p => !selectedIds.has(p.id))
  table.resetRowSelection()
  dialogOpen.value = false
  showToast(`Deleted ${count} product(s)`)
}
</script>

<template>
  <div>
    <!-- Toolbar -->
    <div class="panel-toolbar">
      <VueInput
        type="search"
        placeholder="Search…"
        :value="globalFilter"
        @input="(e: Event) => { globalFilter = (e.target as HTMLInputElement).value; table.setPageIndex(0) }"
      />
      <VueInput
        placeholder="Filter name…"
        :value="nameFilter"
        @input="(e: Event) => setNameFilter((e.target as HTMLInputElement).value)"
      />
      <select
        :value="categoryFilter"
        @change="(e: Event) => setCategoryFilter((e.target as HTMLSelectElement).value)"
        :style="{
          border: '1px solid var(--ag-border)',
          borderRadius: 'var(--ag-radius-md)',
          padding: '0.375rem 0.75rem',
          background: 'var(--ag-background-primary)',
          color: 'var(--ag-text-primary)',
          fontSize: 'var(--ag-font-size-base)',
          fontFamily: 'inherit',
        }"
      >
        <option value="">All Categories</option>
        <option value="Electronics">Electronics</option>
        <option value="Clothing">Clothing</option>
        <option value="Food">Food</option>
        <option value="Books">Books</option>
        <option value="Tools">Tools</option>
      </select>

      <div class="panel-toolbar-right">
        <VueMenu menu-variant="chevron" button-variant="secondary">
          Columns
          <template #menu>
            <VueMenuItem
              v-for="colId in HIDEABLE_COLS"
              :key="colId"
            >
              <label style="display:flex;align-items:center;gap:0.5rem;cursor:pointer">
                <input
                  type="checkbox"
                  :checked="table.getColumn(colId)?.getIsVisible() ?? true"
                  @change="table.getColumn(colId)?.getToggleVisibilityHandler()?.($event)"
                />
                {{ colId.charAt(0).toUpperCase() + colId.slice(1) }}
              </label>
            </VueMenuItem>
          </template>
        </VueMenu>
      </div>
    </div>

    <!-- Delete selected -->
    <div v-if="selectedCount > 0" class="delete-row">
      <VueButton variant="danger" @click="dialogOpen = true">
        Delete Selected ({{ selectedCount }})
      </VueButton>
    </div>

    <!-- Table -->
    <VueEmptyState
      v-if="rows.length === 0"
      title="No products found."
      subtitle="Try adjusting your filters."
    />

    <div v-else style="overflow-x: auto">
      <table class="ag-table">
        <caption class="visually-hidden">Product inventory (TanStack)</caption>
        <thead>
          <tr v-for="hg in headerGroups" :key="hg.id">
            <th
              v-for="header in hg.headers"
              :key="header.id"
              :class="`ts-th${header.column.id === 'category' ? ' col-category' : ''}`"
              @click="header.column.getCanSort() ? header.column.getToggleSortingHandler()?.($event) : undefined"
            >
              <template v-if="header.id === 'select'">
                <VueCheckbox
                  label-text=""
                  :checked="table.getIsAllPageRowsSelected()"
                  :indeterminate="table.getIsSomePageRowsSelected()"
                  @change="table.toggleAllPageRowsSelected()"
                />
              </template>
              <template v-else>
                <FlexRender
                  v-if="!header.isPlaceholder"
                  :render="header.column.columnDef.header"
                  :props="header.getContext()"
                />
                <span v-if="header.column.getCanSort()" class="sort-icon">
                  <ChevronUp v-if="header.column.getIsSorted() === 'asc'" :size="14" />
                  <ChevronDown v-else-if="header.column.getIsSorted() === 'desc'" :size="14" />
                  <ChevronsUpDown v-else :size="12" />
                </span>
                <span
                  v-if="header.column.getIsSorted() && sorting.length > 1"
                  class="sort-order"
                >{{ header.column.getSortIndex() + 1 }}</span>
              </template>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.id">
            <td
              v-for="cell in row.getVisibleCells()"
              :key="cell.id"
              :class="`ts-td${cell.column.id === 'category' ? ' col-category' : ''}`"
              :data-label="cell.column.id"
            >
              <template v-if="cell.column.id === 'select'">
                <VueCheckbox
                  label-text=""
                  :checked="row.getIsSelected()"
                  :disabled="!row.getCanSelect()"
                  @change="row.toggleSelected()"
                />
              </template>
              <template v-else-if="cell.column.id === 'status'">
                <VueTag :variant="statusVariant(row.original.status)">
                  {{ row.original.status }}
                </VueTag>
              </template>
              <template v-else-if="cell.column.id === 'actions'">
                <VueIconButton
                  :label="`Edit ${row.original.name}`"
                  @icon-button-click="showToast(`Editing: ${row.original.name}`)"
                >
                  <Pencil :size="16" />
                </VueIconButton>
              </template>
              <template v-else>
                <FlexRender
                  :render="cell.column.columnDef.cell"
                  :props="cell.getContext()"
                />
              </template>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination row -->
    <div class="pagination-row">
      <select
        :value="String(pageSize)"
        @change="(e: Event) => { table.setPageSize(Number((e.target as HTMLSelectElement).value)); table.setPageIndex(0) }"
        :style="{
          border: '1px solid var(--ag-border)',
          borderRadius: 'var(--ag-radius-md)',
          padding: '0.375rem 0.75rem',
          background: 'var(--ag-background-primary)',
          color: 'var(--ag-text-primary)',
          fontSize: 'var(--ag-font-size-base)',
          fontFamily: 'inherit',
        }"
      >
        <option value="10">10 / page</option>
        <option value="25">25 / page</option>
        <option value="50">50 / page</option>
      </select>

      <VuePagination
        :current="pageIndex + 1"
        :total-pages="Math.max(1, totalPages)"
        @page-change="(e) => table.setPageIndex(e.page - 1)"
      />
    </div>

    <!-- Delete Dialog -->
    <VueDialog
      :open="dialogOpen"
      heading="Confirm Delete"
      :description="`Delete ${selectedCount} selected product(s)? This cannot be undone.`"
      :show-close-button="true"
      @dialog-close="dialogOpen = false"
    >
      <div slot="footer" style="display:flex;gap:var(--ag-space-2);justify-content:flex-end">
        <VueButton variant="secondary" @click="dialogOpen = false">Cancel</VueButton>
        <VueButton variant="danger" @click="handleDeleteConfirm">Delete</VueButton>
      </div>
    </VueDialog>

    <!-- Toast -->
    <VueToast
      :open="toastOpen"
      type="success"
      position="top-end"
      :show-close-button="true"
      @toast-close="toastOpen = false"
    >
      {{ toastMsg }}
    </VueToast>
  </div>
</template>
