// agnostic-react/src/Avatar.tsx
import { FC, ReactElement } from 'react';
import styles from './avatar.module.css';

export const AvatarGroupComponent: FC = ({ children }): ReactElement => (
  <div className="avatar-group">{children}</div>
);

export interface AvatarProps {
  isRounded?: boolean;
  isSquare?: boolean;
  isTransparent?: boolean;
  type?: 'warning' | 'error' | 'info' | 'success' | '';
  size?: 'small' | 'large' | 'xlarge' | '';
  text?: string;
  imgUrl?: string;
}

export const Avatar: FC<AvatarProps> = ({
  isRounded = false,
  isSquare = false,
  isTransparent = false,
  type = '',
  size = '',
  text,
  imgUrl,
  children,
}): ReactElement => {
  // Type might be empty string so we only capitalize if it's truthy
  const typeCapitalized = type ? `${type.slice(0, 1).toUpperCase()}${type.slice(1)}` : '';
  const sizeCapitalized = size ? `${size.slice(0, 1).toUpperCase()}${size.slice(1)}` : '';

  const avatarClasses = [
    styles.avatar,
    isRounded ? styles.avatarRounded : '',
    isTransparent ? styles.avatarTransparent : '',
    isSquare ? styles.avatarSquare : '',
    type ? styles[`avatar${typeCapitalized}`] : '',
    size ? styles[`avatar${sizeCapitalized}`] : '',
  ]
    .filter((cls) => cls)
    .join(' ');

  // Use an empty alt attribute for any image that is decorative or not necessary
  // for understanding the content of the page.
  return (
    <span className={avatarClasses} data-text={text || null}>
      {imgUrl && <img src={imgUrl} className={styles.avatarImage} alt="" />}
      {children}
    </span>
  );
};

// agnostic-angular/libs/ag/src/lib/avatar.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
@Component({
  selector: 'ag-avatar-group',
  template: `<div class="avatar-group"><ng-content></ng-content></div>`,
  styleUrls: ['./avatar.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarGroupComponent {}

@Component({
  selector: 'ag-avatar',
  template: `<span [ngClass]="avatarClasses" [attr.data-text]="text"
    ><ng-content></ng-content
  ></span>`,
  styleUrls: ['./avatar.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarComponent {
  @Input() isRounded = false;
  @Input() isSquare = false;
  @Input() isTransparent = false;
  @Input() type: 'warning' | 'error' | 'info' | 'success' | '' = '';
  @Input() size: 'small' | 'large' | 'xlarge' | '' = '';
  @Input() text: string = '';

  public get avatarClasses(): string {
    return [
      'avatar',
      this.size ? `avatar-${this.size}` : '',
      this.type ? `avatar-${this.type}` : '',
      this.isRounded ? 'avatar-rounded' : '',
      this.isTransparent ? 'avatar-transparent' : '',
      this.isSquare ? 'avatar-square' : '',
    ]
      .filter((c) => c.length)
      .join(' ');
  }
}
