// agnostic-react/src/Header.tsx
// import PropTypes from 'prop-types';
import { FC, ReactNode } from 'react';
import styles from './header.module.css';

export interface HeaderNavProps {
  css?: string;
  children: ReactNode;
}

export const HeaderNav: FC<HeaderNavProps> = ({ css = '', children }) => {
  const navClasses = [css ? `${css}` : ''].filter((c) => c).join(' ');
  return (
    <nav className={navClasses}>
      <ul className={styles.headerNav}>{children}</ul>
    </nav>
  );
};

export interface HeaderNavItemProps {
  css?: string;
  children: ReactNode;
}
export const HeaderNavItem: FC<HeaderNavItemProps> = ({ css = '', children }) => {
  const klasses = [styles.headerNavItem, css ? `${css}` : ''];
  const classes = klasses.filter((klass) => klass.length).join(' ');
  return <li className={classes}>{children}</li>;
};

export interface HeaderProps {
  isSticky?: boolean;
  isSkinned?: boolean;
  isHeaderContentStart?: boolean;
  isHeaderContentEnd?: boolean;
  css?: string;
  children: ReactNode;
}

export const Header: FC<HeaderProps> = ({
  css = '',
  isSticky = false,
  isSkinned = true,
  isHeaderContentStart = false,
  isHeaderContentEnd = false,
  children,
}) => {
  const headerClasses = [
    isSkinned ? styles.header : styles.headerBase,
    isSticky ? styles.sticky : '',
    css ? `${css}` : '',
  ]
    .filter((c) => c.length)
    .join(' ');

  const headerContentClasses = [
    styles.headerContent,
    isHeaderContentStart ? styles.headerContentStart : '',
    isHeaderContentEnd ? styles.headerContentEnd : '',
  ]
    .filter((c) => c.length)
    .join(' ');

  return (
    <nav className={headerClasses}>
      <div className={headerContentClasses}>{children}</div>
    </nav>
  );
};

// agnostic-angular/libs/ag/src/lib/header.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'ag-header-nav',
  template: `<nav>
    <div [ngClass]="classes">
      <ng-content></ng-content>
    </div>
  </nav>`,
  styleUrls: ['./headernav.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderNavComponent {
  @Input() css?: string;

  public get classes(): string {
    return ['header-nav', this.css ? `${this.css}` : '']
      .filter((cl) => cl.length)
      .join(' ');
  }
}

@Component({
  selector: 'ag-header-nav-item',
  template: `<div [ngClass]="classes"><ng-content></ng-content></div>`,
  styleUrls: ['./headernavitem.css'],
})
export class HeaderNavItemComponent {
  @Input() css?: string;
  public get classes(): string {
    let klasses = ['header-nav-item', this.css ? `${this.css}` : ''];
    klasses = klasses.filter((klass) => klass.length);
    return klasses.join(' ');
  }
}

@Component({
  selector: 'ag-header',
  template: `<header [ngClass]="classes">
    <div [ngClass]="headerContentClasses"><ng-content></ng-content></div>
  </header> `,
  styleUrls: ['./header.css'],
})
export class HeaderComponent {
  @Input() css?: string;
  @Input() isSkinned?: boolean = true;
  @Input() isHeaderContentStart?: boolean = false;
  @Input() isHeaderContentEnd?: boolean = false;
  @Input() isSticky?: boolean;

  public get classes(): string {
    const baseClass = this.isSkinned ? 'header' : 'header-base';
    const isStickyClass = this.isSticky ? 'header-sticky' : '';
    const overrides = this.css ? `${this.css}` : '';
    return [baseClass, isStickyClass, overrides]
      .filter((c) => c.length)
      .join(' ');
  }

  public get headerContentClasses(): string {
    const baseClass = 'header-content';
    const headerContentStart = this.isHeaderContentStart
      ? 'header-content-start'
      : '';
    const headerContentEnd = this.isHeaderContentEnd
      ? 'header-content-end'
      : '';
    return [baseClass, headerContentStart, headerContentEnd]
      .filter((c) => c.length)
      .join(' ');
  }
}
