// agnostic-react/src/Loader.tsx
import { FC, ReactElement } from 'react';
import styles from './loader.module.css';

export interface LoaderProps {
  size?: 'small' | 'large' | '';
  ariaLabel?: string;
}

export const Loader: FC<LoaderProps> = ({ ariaLabel = 'Loading…', size = '' }): ReactElement => {
  const sizeCapitalized = size ? `${size.slice(0, 1).toUpperCase()}${size.slice(1)}` : '';
  const loaderClasses = [styles.loader, size ? styles[`loader${sizeCapitalized}`] : '']
    .filter((cls) => cls)
    .join(' ');

  return (
    <div className={loaderClasses} role="status" aria-live="polite" aria-busy="true">
      <span className="screenreader-only">{ariaLabel}</span>
    </div>
  );
};

// agnostic-angular/libs/ag/src/lib/loader.component.ts
import { Input, ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'ag-loader',
  template: `<div [class]="loaderClasses" role="status" attr.aria-live="polite" [attr.aria-busy]="true">
    <span class="screenreader-only">{{ariaLabel}}</span>
  </div>`,
  styleUrls: ['./loader.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoaderComponent {
  @Input() size: 'small' | 'large' | '' = '';
  @Input() ariaLabel: string = 'Loading…';

  public get loaderClasses() {
    return [
      'loader',
      `loader-${this.size}`,
    ].filter((cl) => cl).join(' ');
  }
}
