// agnosticui-react-ts/lib/esm/Progress.js
import { jsx as _jsx } from "react/jsx-runtime";
import styles from './progress.module.css';
export var Progress = function (_a) {
    var _b = _a.value, value = _b === void 0 ? 0 : _b, max = _a.max, _c = _a.css, css = _c === void 0 ? '' : _c;
    var klasses = [styles.progressBar, css ? "" + css : ''];
    var classes = klasses.filter(function (klass) { return klass.length; }).join(' ');
    return _jsx("progress", { className: classes, value: value, max: max }, void 0);
};
//# sourceMappingURL=Progress.js.map

// agnosticui-angular/libs/ui/src/lib/progress.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
@Component({
  selector: 'ag-progress',
  template: `<progress [ngClass]="classes" [attr.value]="value" [attr.max]="max"></progress>`,
  styleUrls: ['./progress.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class ProgressComponent {
  @Input() value: number = 0;
  @Input() max: number = 100;
  @Input() css?: string;
  public get classes(): string {
    console.log(this)
    let klasses = ['progress', this.css?.length ? `${this.css}` : '']
    klasses = klasses.filter((klass) => klass.length)
    return klasses.join(' ')
  }
}
