// agnostic-react/src/Progress.tsx
import { FC } from 'react';
import styles from './progress.module.css';

export interface ProgressProps {
  max: number;
  value?: number;
  css?: string;
}

export const Progress: FC<ProgressProps> = ({ value = 0, max, css = '' }) => {
  const klasses = [styles.progressBar, css ? `${css}` : ''];
  const classes = klasses.filter((klass) => klass.length).join(' ');
  return <progress className={classes} value={value} max={max} />;
};

// agnosticui-angular/libs/ui/src/lib/progress.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
@Component({
  selector: 'ag-progress',
  template: `<progress [ngClass]="classes" [attr.value]="value" [attr.max]="max"></progress>`,
  styleUrls: ['./progress.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class ProgressComponent {
  @Input() value: number = 0;
  @Input() max: number = 100;
  @Input() css?: string;
  public get classes(): string {
    console.log(this)
    let klasses = ['progress', this.css?.length ? `${this.css}` : '']
    klasses = klasses.filter((klass) => klass.length)
    return klasses.join(' ')
  }
}
