// agnosticui-svelte/examples/src/App.svelte
<script>
	import "../node_modules/agnosticui-svelte/dist/common.min.css";
	import { Button, Card, ChoiceInput } from 'agnosticui-svelte';
	const opts = [
		{
			name: "frequency",
			value: "daily",
			label: "Daily",
		},
		{
			name: "frequency",
			value: "weekly",
			label: "Weekly",
		},
		{
			name: "frequency",
			value: "monthly",
			label: "Monthly",
		},
	];
</script>
<style>
	.container {
		margin: 2rem 5rem;
	}
	.component-container {
		padding: 1rem 2rem;
	}

</style>

<div class="container">
	<Card>
		<section class="component-container">
				<h2>Buttons</h2>
				<Button>Go</Button>
				<Button mode="primary">Go</Button>
				<Button mode="primary" isRounded>Go</Button>
				<Button mode="primary" isRounded isBordered>Go</Button>
				<Button size="large">Go</Button>
				<Button isBlock>Go</Button>
				<Button isCircle>Go</Button>
				<Button isRaised>Go</Button>
				<Button mode="primary" isRaised>Go</Button>
				<Button mode="secondary" isRaised>Go</Button>
				<Button isBlank>Blank button</Button>
				<Button isDisabled>Disabled</Button>
		</section>
	</Card>
	<Card>
			<section class="component-container">
				<h2>Checkbox</h2>
				<ChoiceInput type="checkbox" isInline options={opts} />
				<h2>Radio</h2>
				<ChoiceInput type="radio" isInline options={opts} />
			</section>
	</Card>
</div>

// agnosticui-angular/apps/examples/src/app/app.component.ts
import { Component } from '@angular/core';
// import 'agnosticui-angular/dist/common.min.css';
// import { ButtonComponent } from 'agnosticui-angular';
@Component({
  selector: 'ag-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'examples';
}

<main>
  <h1>AgnosticUI Vue</h1>
  <h3>Default Buttons</h3>
  <section>
    <ag-button>Go</ag-button>
    <ag-button [isBordered]="true">Go</ag-button>
    <ag-button [isBlank]="true">Go</ag-button>
    <ag-button [isBlock]="true">Go</ag-button>
    <ag-button [isRounded]="true">Go</ag-button>
    <ag-button [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h3>Primary</h3>
  <section>
    <ag-button mode="primary">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="primary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h3>Secondary</h3>
  <section>
    <ag-button mode="secondary">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlank]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBlock]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isRaised]="true"
               [isRounded]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isBordered]="true"
               [isRounded]="true">Go</ag-button>
  </section>
  <h3>Misc</h3>
  <section>
    <ag-button [isDisabled]="true">Go</ag-button>
    <ag-button mode="primary"
               [isDisabled]="true">Go</ag-button>
    <ag-button mode="secondary"
               [isDisabled]="true">Go</ag-button>
    <ag-button size="small">Go</ag-button>
    <ag-button size="large">Go</ag-button>
    <ag-button [isSkinned]="false">No Skin</ag-button>
  </section>

  <section>
    <h3>Button Groups</h3>
    <ag-button-group ariaLabel="A useful ariaLabel">
      <div class="btn-first-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 1</ag-button>
      </div>
      <ag-button mode="primary"
                 [isBordered]="true">Button 2</ag-button>
      <ag-button mode="primary"
                 [isBordered]="true">Button 3</ag-button>
      <div class="btn-last-wrap">
        <ag-button mode="primary"
                   [isBordered]="true">Button 4</ag-button>
      </div>
    </ag-button-group>
  </section>
  <section>
    <ag-card>
      <div style="padding: 24px;">Default</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true">
      <div style="padding: 24px;">Stacked</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isStacked]="true"
             [isAnimated]="true">
      <div style="padding: 24px;">Stacked & Animated</div>
      <div style="padding: 24px;">Card</div>
    </ag-card>
    <ag-card [isSkinned]="false">
      <div style="padding: 24px;">Base Card</div>
      <div style="padding: 24px;">No Skin</div>
    </ag-card>
    <ag-card css="addition-classes">
      <div style="padding: 24px;">Custom CSS Class Overrides</div>
      <div style="padding: 24px;">Inspect to see additional-classes</div>
    </ag-card>
  </section>
  <section>
    <ag-choice-input type="radio"
                     [options]="[{ name: 'solo', value: 'stevie', label: 'Stevie Wonder'}, { name: 'solo', value: 'whitney', label: 'Whitney Houston' }, { name: 'solo', value: 'charlie', label: 'Charlie Wilson' }]">
    </ag-choice-input>
  
    <ag-choice-input type="checkbox"
                     [options]="[{ name: 'bands', value: 'bonjovi', label: 'Bon Jovi'}, { name: 'bands', value: 'stones', label: 'Rolling Stones' }, { name: 'bands', value: 'isleybros', label: 'Isley Brothers' }]"
                     legendLabel="Large"
                     size="large"
                     [isInline]="true"></ag-choice-input>
  
  </section>
  <section>
    <ag-input
      uniqueId="aginput-123"
      placeholder="Enter name…"
      label="Default input"
      type="text"
    ></ag-input>
  </section>
  <section>
    <ag-switch label="Small" size="small" labelPosition="right"></ag-switch>
    <ag-switch label="Switch default"></ag-switch>
  </section>
  <section>
    <ag-tabs>
      <ag-tab-panel title="Tab 1">
        Tab 1 content
      </ag-tab-panel>
      <ag-tab-panel title="Tab 2">
        Tab 2 content
      </ag-tab-panel>
    </ag-tabs>
  </section>
</main>
